Veins: veins::LocalMobilityTraci Class Reference
veins::LocalMobilityTraci Class Reference
#include <LocalMobilityTraci.h>
Public Member Functions
LocalMobilityTraci ()
virtual ~LocalMobilityTraci ()
Move * getMove ()
std::string getExternal_id ()
updated by setExternalId()
double getAntennaPositionOffset ()
front offset for the antenna on this car
simtime_t getLastUpdate ()
updated by nextPosition()
Coord getNextRoadPosition ()
position of front bumper, updated by nextPosition()
std::string getNextRoad_id ()
updated by nextPosition()
double getNextSpeed ()
updated by nextPosition()
double getNextAngle ()
updated by nextPosition()
Public Member Functions inherited from veins::TraCIMobility
TraCIMobility ()
~TraCIMobility () override
void initialize (int) override
void finish () override
void handleSelfMsg (cMessage *msg) override
Called upon arrival of a self messages.
virtual void preInitialize (std::string external_id, const Coord &position, std::string road_id="", double speed=-1, Heading heading=Heading::nan)
virtual void nextPosition (const Coord &position, std::string road_id="", double speed=-1, Heading heading=Heading::nan, VehicleSignalSet signals={VehicleSignal::undefined})
virtual void changePosition ()
virtual void changeParkingState (bool)
virtual void collisionOccurred (bool newState)
virtual void setExternalId (std::string external_id)
virtual std::string getExternalId () const
virtual double getHostPositionOffset () const
virtual bool getParkingState () const
virtual std::string getRoadId () const
virtual double getSpeed () const
virtual VehicleSignalSet getSignals () const
virtual Heading getHeading () const
returns heading.
virtual TraCIScenarioManager * getManager () const
virtual TraCICommandInterface * getCommandInterface () const
virtual TraCICommandInterface::Vehicle * getVehicleCommandInterface () const
Coord getHostSpeed () const
Returns the speed of the host (likely 0 if setHostSpeed==false)
Public Member Functions inherited from veins::BaseMobility
BaseMobility ()
BaseMobility (unsigned stacksize)
void handleMessage (cMessage *msg) override
This modules should only receive self-messages.
void initialize (int) override
Initializes mobility model parameters.
void finish () override
Delete dynamically allocated objects.
virtual Coord getPositionAt (simtime_t_cref stWhen) const
Returns the current position at the given simulation time.
virtual Coord getCurrentOrientation () const
virtual Coord getCurrentDirection () const
virtual void setStartPosition (Coord pos)
Overrides start position if called before initialize()
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Additional Inherited Members
Public Types inherited from veins::BaseMobility
enum BorderPolicy { REFLECT , WRAP , PLACERANDOMLY , RAISEERROR }
Selects how a node should behave if it reaches the edge of the playground.
enum BaseMobilityMsgKinds { MOVE_HOST = 21311 , MOVE_TO_BORDER , LAST_BASE_MOBILITY_KIND }
The kind field of messages.
enum BorderHandling {
NOWHERE , X_SMALLER , X_BIGGER , Y_SMALLER ,
Y_BIGGER , Z_SMALLER , Z_BIGGER
}
Specifies which border actually has been reached.
Static Public Attributes inherited from veins::TraCIMobility
static const simsignal_t collisionSignal = registerSignal("org_car2x_veins_modules_mobility_collision")
static const simsignal_t parkingStateChangedSignal = registerSignal("org_car2x_veins_modules_mobility_parkingStateChanged")
Static Public Attributes inherited from veins::BaseMobility
static const simsignal_t mobilityStateChangedSignal = registerSignal("org_car2x_veins_base_modules_mobilityStateChanged")
Store the category of HostMove.
Protected Member Functions inherited from veins::TraCIMobility
void fixIfHostGetsOutside () override
called after each read to check for (and handle) invalid positions
double calculateCO2emission (double v, double a) const
Returns the amount of CO2 emissions in grams/second, calculated for an average Car.
Coord calculateHostPosition (const Coord &vehiclePos) const
Calculates where the OMNeT++ module position of this car should be, given its front bumper position.
Coord getCurrentSpeed () const override
Calling this method on pointers of type TraCIMobility is deprecated in favor of calling either getHostSpeed or getSpeed.
Protected Member Functions inherited from veins::BaseMobility
virtual int iconSizeTagToSize (const char *tag)
Maps the passed icon size tag (is) to an actual size in pixels.
virtual const char * iconSizeToTag (double size)
Maps the passed size in pixels to an appropriate icon size tag (is).
virtual void handleBorderMsg (cMessage *)
Called upon arrival of a border messages.
virtual void makeMove ()
Moves the host.
virtual void updatePosition ()
Update the position information for this node.
double playgroundSizeX () const
Returns the width of the playground.
double playgroundSizeY () const
Returns the height of the playground.
double playgroundSizeZ () const
Returns the height of the playground.
Coord getRandomPosition ()
Random position somewhere in the playground.
bool handleIfOutside (BorderPolicy, Coord &, Coord &, Coord &, double &)
Main border handling function.
BorderHandling checkIfOutside (Coord, Coord &)
Checks whether the host is outside the playground and returns where.
void goToBorder (BorderPolicy, BorderHandling, Coord &, Coord &)
calculate the step to reach the border
void reflectCoordinate (BorderHandling border, Coord &c)
helperfunction for reflectIfOutside() to reflect a Coordinate at a given border
void reflectIfOutside (BorderHandling, Coord &, Coord &, Coord &, double &)
Utility function to reflect the node if it goes outside the playground.
void wrapIfOutside (BorderHandling, Coord &, Coord &)
Utility function to wrap the node to the opposite edge (torus) if it goes outside the playground.
void placeRandomlyIfOutside (Coord &)
Utility function to place the node randomly if it goes outside the playground.
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes inherited from veins::TraCIMobility
int accidentCount
number of accidents
cOutVector currentPosXVec
vector plotting posx
cOutVector currentPosYVec
vector plotting posy
cOutVector currentSpeedVec
vector plotting speed
cOutVector currentAccelerationVec
vector plotting acceleration
cOutVector currentCO2EmissionVec
vector plotting current CO2 emission
Statistics statistics
everything statistics-related
bool isPreInitialized
true if preInitialize() has been called immediately before initialize()
std::string external_id
updated by setExternalId()
double hostPositionOffset
front offset for the antenna on this car
bool setHostSpeed
whether to update the speed of the host (along with its position)
simtime_t lastUpdate
updated by nextPosition()
Coord roadPosition
position of front bumper, updated by nextPosition()
std::string road_id
updated by nextPosition()
double speed
updated by nextPosition()
Heading heading
updated by nextPosition()
VehicleSignalSet signals
updated by nextPosition()
cMessage * startAccidentMsg = nullptr
cMessage * stopAccidentMsg = nullptr
TraCIScenarioManager * manager
TraCICommandInterface * commandInterface
TraCICommandInterface::Vehicle * vehicleCommandInterface
double last_speed
bool isParking
Protected Attributes inherited from veins::BaseMobility
BaseWorldUtility * world
Pointer to BaseWorldUtility – these two must know each other.
Move move
Stores the current position and move pattern of the host.
simtime_t updateInterval
Time interval (in seconds) to update the hosts position.
cMessage * moveMsg
Self message to trigger movement.
bool scaleNodeByDepth
Enable depth dependent scaling of nodes when 3d and tkenv is used.
double playgroundScaleX
Scaling of the playground in X direction.
double playgroundScaleY
Scaling of the playground in Y direction.
double origDisplayWidth
The original width the node is displayed width.
double origDisplayHeight
The original height the node is displayed width.
double origIconSize
The original size of the icon of the node.
bool hasStartPosition
Coord startPosition
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Definition at line 27 of file LocalMobilityTraci.h.
Constructor & Destructor Documentation
LocalMobilityTraci()
veins::LocalMobilityTraci::LocalMobilityTraci ()
Definition at line 20 of file LocalMobilityTraci.cc.
{
     // TODO Auto-generated constructor stub
 }
~LocalMobilityTraci()
veins::LocalMobilityTraci::~LocalMobilityTraci () virtual
Definition at line 25 of file LocalMobilityTraci.cc.
{
     // TODO Auto-generated destructor stub
 }
Member Function Documentation
getAntennaPositionOffset()
double veins::LocalMobilityTraci::getAntennaPositionOffset ()
front offset for the antenna on this car
Definition at line 38 of file LocalMobilityTraci.cc.
{
     //return this->antennaPositionOffset;
 }
getExternal_id()
std::string veins::LocalMobilityTraci::getExternal_id ()
updated by setExternalId()
Definition at line 34 of file LocalMobilityTraci.cc.
{
     return this->external_id;
 }
References veins::TraCIMobility::external_id.
getLastUpdate()
simtime_t veins::LocalMobilityTraci::getLastUpdate ()
updated by nextPosition()
Definition at line 42 of file LocalMobilityTraci.cc.
{
     return this->lastUpdate;
 }
References veins::TraCIMobility::lastUpdate.
getMove()
Move * veins::LocalMobilityTraci::getMove ()
Definition at line 29 of file LocalMobilityTraci.cc.
{
     return (& this->move);
 }
References veins::BaseMobility::move.
Referenced by veins::KnownGlobal::calcTraciDistanceMobility(), veins::KnownGlobal::getTraci(), veins::KnownGlobal::getTraciMobility(), and veins::LocalMobility::updateLocalMobilityPos().
getNextAngle()
double veins::LocalMobilityTraci::getNextAngle ()
updated by nextPosition()
Definition at line 58 of file LocalMobilityTraci.cc.
{
     //return this->angle;
 }
getNextRoad_id()
std::string veins::LocalMobilityTraci::getNextRoad_id ()
updated by nextPosition()
Definition at line 50 of file LocalMobilityTraci.cc.
{
     return this->road_id;
 }
References veins::TraCIMobility::road_id.
getNextRoadPosition()
Coord veins::LocalMobilityTraci::getNextRoadPosition ()
position of front bumper, updated by nextPosition()
Definition at line 46 of file LocalMobilityTraci.cc.
{
     return this->roadPosition;
 }
References veins::TraCIMobility::roadPosition.
getNextSpeed()
double veins::LocalMobilityTraci::getNextSpeed ()
updated by nextPosition()
Definition at line 54 of file LocalMobilityTraci.cc.
{
     return this->speed;
 }
References veins::TraCIMobility::speed.
The documentation for this class was generated from the following files:
LocalMobilityTraci.h
LocalMobilityTraci.cc