My Project: veins::RemoteAgent
veins::RemoteAgent
#include <RemoteAgent.h>
Public Member Functions
RemoteAgent ()
RemoteAgent (simtime_t tsDataUpdating, int64_t id, simtime_t sTimePosition, double x, double y, double z, double speed, double maxSpeed, double setRadius, std::string agentName, float acceleration, float angle)
RemoteAgent (simtime_t tsDataUpdating, ICRNode oIcrNode, double setRadius)
void createAgent (simtime_t tsDataUpdating, int64_t id, simtime_t tsStart, double x, double y, double z, double speed, double maxSpeed, double setRadius, std::string agentName, float acceleration, float angle)
virtual ~RemoteAgent ()
void updateRemoteAgent (simtime_t tsDataUpdating, simtime_t tsMovement, double x, double y, double z, double speed, double maxSpeed, double setRadius, float acceleration, float angle)
void updateRemoteAgent (simtime_t tsDataUpdating, ICRNode oIcrNode, double setRadius)
std::string info ()
std::string infoTrace (bool header, std::string idagent)
MobilityInfo * getMobilityInfo ()
RemoteAgentCommInfo * getRemoteAgentCommInfo ()
Public Member Functions inherited from veins::Agent
Agent (int64_t id, std::string name)
Agent ()
Construtor padrão.
std::string info ()
std::string infoTrace (bool header, std::string idagent)
int64_t getId ()
Método para obter o valor atual.
void setId (int64_t id)
Método para definir um valor.
virtual ~Agent ()
virtual void setMobilityInfo (MobilityInfo *mobilityInfo)
virtual double getSetRadius ()
virtual void setSetRadius (double setRadius)
virtual std::string getAgentName ()
virtual void setAgentName (std::string agentName)
CommInfo * getCommInfo ()
void setCommInfo (CommInfo *commInfo)
Additional Inherited Members
Public Attributes inherited from veins::Agent
MobilityInfo * mobilityInfo
CommInfo * commInfo
QoCInfo * qocInfo
Detailed Description
Definition at line 27 of file RemoteAgent.h.
Constructor & Destructor Documentation
RemoteAgent() [1/3]
veins::RemoteAgent::RemoteAgent ()
Definition at line 20 of file RemoteAgent.cc.
{
     // TODO Auto-generated constructor stub
 }
RemoteAgent() [2/3]
veins::RemoteAgent::RemoteAgent (simtime_t tsDataUpdating, int64_t id, simtime_t sTimePosition, double x, double y, double z, double speed, double maxSpeed, double setRadius, std::string agentName, float acceleration, float angle)
Definition at line 26 of file RemoteAgent.cc.
{
     this->qocInfo = new RemoteAgentQoC();
     this->setId(id);
     this->setMobilityInfo(new RemoteMobility(tsStart, x, y, z, speed, maxSpeed, acceleration, angle));
     setSetRadius(setRadius);
     this->setAgentName(agentName);
     this->setCommInfo (new RemoteAgentCommInfo());
     this->getMobilityInfo()->setAge((tsDataUpdating - tsStart).dbl());
 }
References getMobilityInfo(), veins::Agent::qocInfo, veins::MobilityInfo::setAge(), veins::Agent::setAgentName(), veins::Agent::setCommInfo(), veins::Agent::setId(), veins::Agent::setMobilityInfo(), veins::Agent::setRadius, and veins::Agent::setSetRadius().
RemoteAgent() [3/3]
veins::RemoteAgent::RemoteAgent (simtime_t tsDataUpdating, ICRNode oIcrNode, double setRadius)
Definition at line 46 of file RemoteAgent.cc.
 {
     this->createAgent(tsDataUpdating, oIcrNode.nodeId, oIcrNode.posTimeStamp,
             oIcrNode.posX, oIcrNode.posY,oIcrNode.posZ, oIcrNode.speed,
             oIcrNode.maxSpeed, setRadius, std::to_string(oIcrNode.nodeId),
             oIcrNode.aceleration, oIcrNode.angle);
 }
References veins::ICRNode::aceleration, veins::ICRNode::angle, createAgent(), veins::ICRNode::maxSpeed, veins::ICRNode::nodeId, veins::ICRNode::posTimeStamp, veins::ICRNode::posX, veins::ICRNode::posY, veins::ICRNode::posZ, veins::Agent::setRadius, and veins::ICRNode::speed.
~RemoteAgent()
veins::RemoteAgent::~RemoteAgent () virtual
Definition at line 69 of file RemoteAgent.cc.
{
   // TODO Auto-generated destructor stub
     delete(this);
 }
Member Function Documentation
createAgent()
void veins::RemoteAgent::createAgent (simtime_t tsDataUpdating, int64_t id, simtime_t tsStart, double x, double y, double z, double speed, double maxSpeed, double setRadius, std::string agentName, float acceleration, float angle)
Definition at line 36 of file RemoteAgent.cc.
{
     this->qocInfo = new RemoteAgentQoC();
     this->setId(id);
     this->setMobilityInfo(new RemoteMobility(tsStart, x, y, z, speed, maxSpeed, acceleration, angle));
     setSetRadius(setRadius);
     this->setAgentName(agentName);
     this->setCommInfo (new RemoteAgentCommInfo());
     this->getMobilityInfo()->setAge((tsDataUpdating - tsStart).dbl());
 }
References getMobilityInfo(), veins::Agent::qocInfo, veins::MobilityInfo::setAge(), veins::Agent::setAgentName(), veins::Agent::setCommInfo(), veins::Agent::setId(), veins::Agent::setMobilityInfo(), veins::Agent::setRadius, and veins::Agent::setSetRadius().
Referenced by RemoteAgent().
getMobilityInfo()
MobilityInfo * veins::RemoteAgent::getMobilityInfo () virtual
Reimplemented from veins::Agent.
Definition at line 87 of file RemoteAgent.cc.
{
     return ((MobilityInfo*) mobilityInfo);
 }
References veins::Agent::mobilityInfo.
Referenced by createAgent(), info(), RemoteAgent(), and updateRemoteAgent().
getRemoteAgentCommInfo()
RemoteAgentCommInfo * veins::RemoteAgent::getRemoteAgentCommInfo ()
Definition at line 92 of file RemoteAgent.cc.
{
     return ((RemoteAgentCommInfo*) this->commInfo);
 }
References veins::Agent::commInfo.
Referenced by veins::RemoteAgentGroup::calcRemoteAgentGroupCommPerform(), info(), infoTrace(), and updateRemoteAgent().
info()
std::string veins::RemoteAgent::info ()
Definition at line 74 of file RemoteAgent.cc.
{
     std::ostringstream ost;
     ost << Agent::info()  << "  Remote Mobility: " << ((RemoteMobility*) getMobilityInfo())->info()
                           << "  Remote CommInfo: " << this->getRemoteAgentCommInfo()->info();
     return ost.str();
 }
References getMobilityInfo(), getRemoteAgentCommInfo(), veins::Agent::info(), and veins::RemoteAgentCommInfo::info().
infoTrace()
std::string veins::RemoteAgent::infoTrace (bool header = false, std::string idagent = "")
Definition at line 81 of file RemoteAgent.cc.
{
     std::ostringstream ost;
     ost <<  Agent::infoTrace(header, idagent) << this->getRemoteAgentCommInfo()->infoTrace(header, idagent);
     return ost.str();
 }
References getRemoteAgentCommInfo(), veins::Agent::infoTrace(), and veins::RemoteAgentCommInfo::infoTrace().
Referenced by veins::RemoteAgentGroup::calcRemoteAgentGroupCommPerform().
updateRemoteAgent() [1/2]
void veins::RemoteAgent::updateRemoteAgent (simtime_t tsDataUpdating, ICRNode oIcrNode, double setRadius)
Definition at line 54 of file RemoteAgent.cc.
{
     updateRemoteAgent(tsDataUpdating, oIcrNode.posTimeStamp, oIcrNode.posX, oIcrNode.posY, oIcrNode.posZ, oIcrNode.speed, oIcrNode.maxSpeed, setRadius, oIcrNode.aceleration, oIcrNode.angle);
 }
References veins::ICRNode::aceleration, veins::ICRNode::angle, veins::ICRNode::maxSpeed, veins::ICRNode::posTimeStamp, veins::ICRNode::posX, veins::ICRNode::posY, veins::ICRNode::posZ, veins::Agent::setRadius, veins::ICRNode::speed, and updateRemoteAgent().
updateRemoteAgent() [2/2]
void veins::RemoteAgent::updateRemoteAgent (simtime_t tsDataUpdating, simtime_t tsMovement, double x, double y, double z, double speed, double maxSpeed, double setRadius, float acceleration, float angle)
Definition at line 58 of file RemoteAgent.cc.
{
     RemoteMobility* rm = ((RemoteMobility*) getMobilityInfo());
     if (rm->getActualMove()->getStartTime()< tsMobilityData){
         rm->updateMobilityInfo(tsMobilityData, x, y, z, speed, maxSpeed, acceleration, angle);
     }
     //atualizao do raio de comunicao do agente remoto
     if (radius!=0) this->getRemoteAgentCommInfo()->setRadius(radius);
     this->getMobilityInfo()->setAge((tsDataUpdating - tsMobilityData).dbl());
 }
References veins::MobilityInfo::getActualMove(), getMobilityInfo(), getRemoteAgentCommInfo(), veins::Move::getStartTime(), veins::MobilityInfo::setAge(), veins::CommInfo::setRadius(), and veins::RemoteMobility::updateMobilityInfo().
Referenced by veins::IcarContext::updateAgentGroup(), and updateRemoteAgent().
The documentation for this class was generated from the following files:
RemoteAgent.h
RemoteAgent.cc