My Project: veins::LocalMobility
veins::LocalMobility
#include <LocalMobility.h>
Public Member Functions
LocalMobility ()
LocalMobility (TraCIMobility *traci, simtime_t tsStart, double x, double y, double sensorPeriod, double speed)
LocalMobility (TraCIMobility *traci, float pMaxSpeed)
virtual ~LocalMobility ()
Move * getMove ()
Move * getLastMove ()
double getSensorPeriod ()
void setSensorPeriod (double sensorPeriod)
std::string info ()
LocalMobilityTraci * getTraci ()
void setTraci (LocalMobilityTraci *traci)
void updateLocalMobilityPos ()
std::string moveInfoTrace (bool header)
Returns information about the current state.
Public Member Functions inherited from veins::MobilityInfo
MobilityInfo ()
virtual ~MobilityInfo ()
std::string info ()
MobilityInfo (Move *mSrc)
float getMaxSpeed ()
Returns a string with the value of the coordinate.
void setMaxSpeed (float maxSpeed)
virtual double calcEuclideanDistanceAgentMoving ()
double calcEuclideanDistancelr (Coord l, Coord r)
std::string infoTrace (bool header, std::string idagent)
Returns information about the current state.
float getAcceleration ()
void setAcceleration (float acceleration)
Move * getActualMove ()
void setActualMove (Move *actualMove)
double getSensorPeriod ()
void setSensorPeriod (float sensorPeriod)
int getQuadrant (double angleRad)
float getAngle ()
Coord getPositionAtTime (simtime_t pTime)
void setAngle (float angle)
double getAge ()
void setAge (double age)
const Move * getCollectedMove ()
void setCollectedMove (Move *collectedMove)
Private Attributes
LocalMobilityTraci * traci
Move * actualTemp
Additional Inherited Members
Protected Member Functions inherited from veins::MobilityInfo
void setLastMove (Move *pMove)
void calcAcceleration ()
Protected Attributes inherited from veins::MobilityInfo
Move * actualMove = new Move()
current vehicle movement
Move * lastMove = new Move()
last vehicle movement before current position
Move * collectedMove = new Move()
collected vehicle movement
float maxSpeed =0
float sensorPeriod
float acceleration
float angle
double age
Detailed Description
Definition at line 26 of file LocalMobility.h.
Constructor & Destructor Documentation
LocalMobility() [1/3]
veins::LocalMobility::LocalMobility ()
Definition at line 21 of file LocalMobility.cc.
{
     // TODO Auto-generated constructor stub
     this->sensorPeriod = 0;
 }
References veins::MobilityInfo::sensorPeriod.
LocalMobility() [2/3]
veins::LocalMobility::LocalMobility (TraCIMobility * traci, simtime_t tsStart, double x, double y, double sensorPeriod, double speed)
LocalMobility() [3/3]
veins::LocalMobility::LocalMobility (TraCIMobility * traci, float pMaxSpeed)
Definition at line 26 of file LocalMobility.cc.
{
     this->sensorPeriod = 0;
     this->setTraci((LocalMobilityTraci *)traci);
     this->setMaxSpeed(pMaxSpeed);
     //this->actualTemp = new Move();
     this->actualMove = new Move();
     //this->actualMove = this->traci->getMove();
     updateLocalMobilityPos();
 }
References veins::MobilityInfo::actualMove, veins::MobilityInfo::sensorPeriod, veins::MobilityInfo::setMaxSpeed(), setTraci(), traci, and updateLocalMobilityPos().
~LocalMobility()
veins::LocalMobility::~LocalMobility () virtual
Definition at line 128 of file LocalMobility.cc.
{
     //delete (this);
 }
Member Function Documentation
getLastMove()
Move * veins::LocalMobility::getLastMove () virtual
Reimplemented from veins::MobilityInfo.
Definition at line 42 of file LocalMobility.cc.
{
     //this->updateLocalMobilityPos();
     return this->lastMove;
 }
References veins::MobilityInfo::lastMove.
getMove()
Move * veins::LocalMobility::getMove ()
Definition at line 37 of file LocalMobility.cc.
{
     //this->updateLocalMobilityPos();
     return this->actualMove;
 }
References veins::MobilityInfo::actualMove.
getSensorPeriod()
double veins::LocalMobility::getSensorPeriod ()
Definition at line 113 of file LocalMobility.cc.
{
     //this->updateLocalMobilityPos();
     return sensorPeriod;
 }
References veins::MobilityInfo::sensorPeriod.
getTraci()
LocalMobilityTraci * veins::LocalMobility::getTraci ()
Definition at line 123 of file LocalMobility.cc.
 {
     return (LocalMobilityTraci  * ) traci;
 }
References traci.
Referenced by veins::KnownGlobal::calcTraciDistanceMobility(), veins::KnownGlobal::getTraci(), veins::KnownGlobal::getTraciMobility(), and veins::IcarContext::textDataAgentPair().
info()
std::string veins::LocalMobility::info ()
Definition at line 139 of file LocalMobility.cc.
{
     std::ostringstream ost;
     //ost << " sensor period: " << sensorPeriod << " acceleration: " << this->acceleration << " traci: " << traci->info();
     return ost.str();
 }
Referenced by veins::LocalAgent::info().
moveInfoTrace()
std::string veins::LocalMobility::moveInfoTrace (bool header = false) virtual
Returns information about the current state.
Reimplemented from veins::MobilityInfo.
Definition at line 147 of file LocalMobility.cc.
{
        std::ostringstream ost;
        ost << ";" << MobilityInfo::moveInfoTrace(header);
        return ost.str();
 }
References veins::MobilityInfo::moveInfoTrace().
setSensorPeriod()
void veins::LocalMobility::setSensorPeriod (double sensorPeriod)
Definition at line 118 of file LocalMobility.cc.
{
     //updateLocalMobilityPos();
     this->sensorPeriod=sensorPeriod;
 }
References veins::MobilityInfo::sensorPeriod.
setTraci()
void veins::LocalMobility::setTraci (LocalMobilityTraci * traci)
Definition at line 132 of file LocalMobility.cc.
{
     this->traci = traci;
 }
References traci.
Referenced by LocalMobility().
updateLocalMobilityPos()
void veins::LocalMobility::updateLocalMobilityPos ()
Definition at line 47 of file LocalMobility.cc.
 {
      if(this->traci!=NULL)
      {
          if (!this->traci->isTerminated())
          {
              /* to keep the last move
              this->lastMove = this->actualTemp;
              this->actualTemp = new Move();
              this->actualTemp->setStart(this->actualMove->getStartPosition(), this->actualMove->getStartTime());
              this->actualTemp->setSpeed(this->actualMove->getSpeed());
              this->actualMove = this->traci->getMove();
              double ay = actualMove->getStartPosition().y - this->lastMove->getStartPosition().y;
              double ax = actualMove->getStartPosition().x - this->lastMove->getStartPosition().x;
              this->angle = std::atan2(ay, ax);
              //this->angle = traci->getAngleRad();
              this->calcAcceleration();
              */
              //double ay = this->traci->getMove()->getStartPosition().y - this->lastMove->getStartPosition().y;
              //double ax = this->traci->getMove()->getStartPosition().x - this->lastMove->getStartPosition().x;
              //this->angle = std::atan2(ay, ax);
              //this->angle = traci->getAngleRad();
              /*std::cout << endl << " velocidade= " << this->traci->getSpeed() << endl;
              std::cout << endl << " posicao= " << this->traci->getMove()->getStartPosition() << endl;
              std::cout << endl << " posicao STARTPOS= " << this->traci->getMove()->getStartPos()<< endl;
              std::cout << endl << " posicao SPEED MOVE= " << this->traci->getMove()->getSpeed()<< endl;
              std::cout << endl << " posicao TIME MOVE= " << this->traci->getMove()->getStartTime() << endl;
             */
              this->lastMove = this->actualMove;
              this->actualMove = new Move();
              this->actualMove->setStart(this->traci->getMove()->getStartPos(), this->traci->getMove()->getStartTime());
              //this->actualMove->setSpeed(this->traci->getMove()->getSpeed());
              this->actualMove->setSpeed(this->traci->getSpeed());
              //dados do sensor
              Move * om1 = new Move();
              om1->setStart( this->actualMove->getStartPos(), this->actualMove->getStartTime());
              //om1->setSpeed(this->actualMove->getSpeed());
              om1->setSpeed(this->traci->getSpeed());
              this->setCollectedMove(om1);
              double ay = actualMove->getStartPos().y - this->lastMove->getStartPos().y;
              double ax = actualMove->getStartPos().x - this->lastMove->getStartPos().x;
              if (ay!=0 || ax!=0) {
                  this->angle = std::atan2(ay, ax);
              }
              //this->angle = traci->getAngleRad();
              this->calcAcceleration();
              this->age = this->traci->getMove()->getStartTime().dbl() - actualMove->getStartTime().dbl();
              //std::cout << endl << "eixo X " << actualMove->getStartPosition().x << "  -  " << this->lastMove->getStartPosition().x;
              //std::cout << endl << "eixo Y " << actualMove->getStartPosition().y << "  -  " << this->lastMove->getStartPosition().y;
              //std::cout << endl << "angleLocal = " << this->angle;
          }
      }
 }
References veins::MobilityInfo::actualMove, veins::MobilityInfo::age, veins::MobilityInfo::angle, veins::MobilityInfo::calcAcceleration(), veins::LocalMobilityTraci::getMove(), veins::TraCIMobility::getSpeed(), veins::Move::getStartPos(), veins::Move::getStartTime(), veins::MobilityInfo::lastMove, veins::MobilityInfo::setCollectedMove(), veins::Move::setSpeed(), veins::Move::setStart(), traci, veins::Coord::x, and veins::Coord::y.
Referenced by veins::IcarContext::changeLocalMobility(), and LocalMobility().
Member Data Documentation
actualTemp
Move* veins::LocalMobility::actualTemp private
Definition at line 32 of file LocalMobility.h.
traci
LocalMobilityTraci* veins::LocalMobility::traci private
Definition at line 29 of file LocalMobility.h.
Referenced by getTraci(), LocalMobility(), setTraci(), and updateLocalMobilityPos().
The documentation for this class was generated from the following files:
LocalMobility.h
LocalMobility.cc