My Project: veins::QoCAgentPair
veins::QoCAgentPair
#include <QoCAgentPair.h>
Public Member Functions
QoCAgentPair ()
QoCAgentPair (AgentPair *c, simtime_t dataValidity)
virtual ~QoCAgentPair ()
TimelinessAgentPair * getTimelinessAgentPair ()
Public Member Functions inherited from veins::QoCInfo
QoCInfo ()
virtual ~QoCInfo ()
Timeliness * getTimeliness ()
void setTimeliness (Timeliness *timeliness)
double getAge ()
void setAge (double age)
Additional Inherited Members
Protected Attributes inherited from veins::QoCInfo
Timeliness * timeliness
double age
Detailed Description
Definition at line 29 of file QoCAgentPair.h.
Constructor & Destructor Documentation
QoCAgentPair() [1/2]
veins::QoCAgentPair::QoCAgentPair ()
QoCAgentPair() [2/2]
veins::QoCAgentPair::QoCAgentPair (AgentPair * c, simtime_t dataValidity)
Definition at line 21 of file QoCAgentPair.cc.
{
     // TODO Auto-generated constructor stub
     std::cout << endl << "begin  QoCAgentPair "<< endl;
     this->timeliness = new TimelinessAgentPair(c, dataValidity);
     std::cout << endl << "end  QoCAgentPair "<< endl;
 }
References veins::QoCInfo::timeliness.
~QoCAgentPair()
veins::QoCAgentPair::~QoCAgentPair () virtual
Definition at line 31 of file QoCAgentPair.cc.
{
     // TODO Auto-generated destructor stub
     delete (this);
 }
Member Function Documentation
getTimelinessAgentPair()
TimelinessAgentPair * veins::QoCAgentPair::getTimelinessAgentPair ()
Definition at line 37 of file QoCAgentPair.cc.
{
     return ((TimelinessAgentPair *) this->timeliness);
 }
References veins::QoCInfo::timeliness.
Referenced by veins::AgentPairList::calcMaxSlr(), veins::AgentPairList::calcMinSlr(), and veins::AgentPair::updateAgentPair().
The documentation for this class was generated from the following files:
QoCAgentPair.h
QoCAgentPair.cc