My Project: veins::LocalCommInfo
veins::LocalCommInfo
#include <LocalCommInfo.h>
Public Member Functions
LocalCommInfo ()
virtual ~LocalCommInfo ()
std::string info ()
std::string infoTrace (bool header, std::string idagent)
LocalAgentCommPerformance * getLocalAgentCommPerformance ()
Public Member Functions inherited from veins::CommInfo
CommInfo ()
virtual ~CommInfo ()
std::string info ()
std::string infoTrace (bool header, std::string idagent)
CommPerformance * getCommPerformance ()
void setCommPerformance (CommPerformance *commPerformance)
double getRadius ()
void setRadius (double radius)
double getSenseGhz ()
void setSenseGhz (double senseGhz)
Additional Inherited Members
Protected Attributes inherited from veins::CommInfo
double radius
double senseGHZ
CommPerformance * commPerformance
Detailed Description
Definition at line 24 of file LocalCommInfo.h.
Constructor & Destructor Documentation
LocalCommInfo()
veins::LocalCommInfo::LocalCommInfo ()
Definition at line 20 of file LocalCommInfo.cc.
{
     // TODO Auto-generated constructor stub
    this->commPerformance = new LocalAgentCommPerformance();
    this->radius = 0;
    this->senseGHZ = 0;
 }
References veins::CommInfo::commPerformance, veins::CommInfo::radius, and veins::CommInfo::senseGHZ.
~LocalCommInfo()
veins::LocalCommInfo::~LocalCommInfo () virtual
Definition at line 27 of file LocalCommInfo.cc.
{
     // TODO Auto-generated destructor stub
 }
Member Function Documentation
getLocalAgentCommPerformance()
LocalAgentCommPerformance * veins::LocalCommInfo::getLocalAgentCommPerformance ()
Definition at line 32 of file LocalCommInfo.cc.
 {
     return (LocalAgentCommPerformance *) this->commPerformance;
 }
References veins::CommInfo::commPerformance.
Referenced by veins::Icarqoc::finish(), info(), infoTrace(), veins::Icarqoc::initialize(), veins::MessageManager::sendICRMessage(), and veins::IcarContext::updateContextfromMsg().
info()
std::string veins::LocalCommInfo::info ()
Definition at line 37 of file LocalCommInfo.cc.
{
     std::ostringstream ost;
     ost << CommInfo::info()
         << this->getLocalAgentCommPerformance()->info();
     return ost.str();
 }
References getLocalAgentCommPerformance(), veins::CommInfo::info(), and LocalAgentCommPerformance::info().
infoTrace()
std::string veins::LocalCommInfo::infoTrace (bool header = false, std::string idagent = "")
Definition at line 44 of file LocalCommInfo.cc.
{
     std::ostringstream ost;
      ost //<< CommInfo::infoTrace(header, idagent)
         << this->getLocalAgentCommPerformance()->infoTrace(header, idagent);
     return ost.str();
 }
References getLocalAgentCommPerformance(), and LocalAgentCommPerformance::infoTrace().
Referenced by veins::LocalAgent::infoTrace().
The documentation for this class was generated from the following files:
LocalCommInfo.h
LocalCommInfo.cc