Veins: veins::LocalAgent Class Reference
veins::LocalAgent Class Reference
#include <LocalAgent.h>
Public Member Functions
LocalAgent (int64_t id, LocalMobility *lm, std::string agentName)
virtual ~LocalAgent ()
void updateLocalAgent (double maxSpeed, double setRadius)
std::string info ()
std::string infoTrace (bool header, std::string idagent)
LocalMobility * getLocalMobility ()
LocalCommInfo * getLocalCommInfo ()
Public Member Functions inherited from veins::Agent
Agent (int64_t id, std::string name)
Agent ()
std::string info ()
std::string infoTrace (bool header, std::string idagent)
int64_t getId ()
void setId (int64_t id)
virtual ~Agent ()
virtual MobilityInfo * getMobilityInfo ()
virtual void setMobilityInfo (MobilityInfo *mobilityInfo)
virtual double getSetRadius ()
virtual void setSetRadius (double setRadius)
virtual std::string getAgentName ()
virtual void setAgentName (std::string agentName)
CommInfo * getCommInfo ()
void setCommInfo (CommInfo *commInfo)
Additional Inherited Members
Public Attributes inherited from veins::Agent
MobilityInfo * mobilityInfo
CommInfo * commInfo
QoCInfo * qocInfo
Detailed Description
Definition at line 24 of file LocalAgent.h.
Constructor & Destructor Documentation
LocalAgent()
veins::LocalAgent::LocalAgent (int64_t id, LocalMobility * lm, std::string agentName)
Definition at line 20 of file LocalAgent.cc.
{
     // TODO Auto-generated constructor stub
     this->setId(id);
     this->setMobilityInfo(localMobility);
     this->setAgentName(agentName);
     this->commInfo = new LocalCommInfo();
 }
References veins::Agent::commInfo, veins::Agent::setAgentName(), veins::Agent::setId(), and veins::Agent::setMobilityInfo().
~LocalAgent()
veins::LocalAgent::~LocalAgent () virtual
Definition at line 29 of file LocalAgent.cc.
{
     // TODO Auto-generated destructor stub
     delete(this);
 }
Member Function Documentation
getLocalCommInfo()
LocalCommInfo * veins::LocalAgent::getLocalCommInfo ()
Definition at line 60 of file LocalAgent.cc.
{
     return ((LocalCommInfo*) this->commInfo);
 }
References veins::Agent::commInfo.
Referenced by veins::Icarqoc::finish(), infoTrace(), veins::Icarqoc::initialize(), veins::MessageManager::sendICRMessage(), veins::IcarContext::updateContextfromMsg(), and updateLocalAgent().
getLocalMobility()
LocalMobility * veins::LocalAgent::getLocalMobility ()
Definition at line 55 of file LocalAgent.cc.
{
     return (LocalMobility *) this->getMobilityInfo();
 }
References veins::Agent::getMobilityInfo().
Referenced by veins::KnownGlobal::calcTraciDistanceMobility(), veins::IcarContext::changeLocalMobility(), veins::KnownGlobal::getTraci(), veins::KnownGlobal::getTraciMobility(), and info().
info()
std::string veins::LocalAgent::info ()
Definition at line 34 of file LocalAgent.cc.
{
     std::ostringstream ost;
     ost << Agent::info()
         << "  Local Mobility: " << this->getLocalMobility()->info();
     return ost.str();
 }
References getLocalMobility(), veins::Agent::info(), and veins::LocalMobility::info().
infoTrace()
std::string veins::LocalAgent::infoTrace (bool header = false, std::string idagent = "")
Definition at line 41 of file LocalAgent.cc.
{
     std::ostringstream ost;
     ost <<  Agent::infoTrace(header, idagent) << this->getLocalCommInfo()->infoTrace(header, idagent);
     return ost.str();
 }
References getLocalCommInfo(), veins::Agent::infoTrace(), and veins::LocalCommInfo::infoTrace().
Referenced by veins::Icarqoc::finish(), and veins::Icarqoc::initialize().
updateLocalAgent()
void veins::LocalAgent::updateLocalAgent (double maxSpeed, double setRadius)
Definition at line 48 of file LocalAgent.cc.
{
     this->getMobilityInfo()->setMaxSpeed(maxSpeed);
     //radius
     this->getLocalCommInfo()->setRadius(radius);
 }
References getLocalCommInfo(), veins::Agent::getMobilityInfo(), veins::MobilityInfo::setMaxSpeed(), and veins::CommInfo::setRadius().
The documentation for this class was generated from the following files:
LocalAgent.h
LocalAgent.cc