Veins: veins::IcarContext Class Reference
veins::IcarContext Class Reference
#include <IcarContext.h>
Public Member Functions
IcarContext ()
IcarContext (LocalAgent *oMyData, KnownGlobal *pKnownGlobal, Icarqoc *pIcar)
virtual ~IcarContext ()
void callFinish ()
void updateAgentPairsFromMsg (ICRMessage *wsm, simtime_t pMsgReceivingTime)
double getMsgTransmitterRange (ICRMessage *m)
RemoteAgent * updateAgentGroup (ICRNode m, simtime_t pMsgReceivingTime)
void updateContextfromMsg (ICRMessage *wsm, simtime_t pMsgReceivingTime)
void changeLocalMobility ()
RemoteAgentGroup * getAgentGroup ()
void setAgentGroup (RemoteAgentGroup *agentGroup)
AgentPairList * getAgentPairList ()
void setAgentPairList (AgentPairList *agentPairList)
LocalAgent * getMyData ()
void setMyData (LocalAgent *myData)
void updateAgentPairs (Agent *agent, simtime_t timeStampData, int event)
std::string textDataAgentPair (int event, AgentPair *c, bool header)
Icarqoc * getIcarModule ()
void setIcarModule (Icarqoc *icarModule)
KnownGlobal * getKnownGlobal ()
void setKnownGlobal (KnownGlobal *knownGlobal)
IcarRouting * getRouting ()
void setRouting (IcarRouting *routing)
GeneralCommunicationService getService ()
void setService (GeneralCommunicationService service)
std::string infoTraceAgentPairList ()
Public Attributes
std::stringstream QoCQoSdataAgentPair
std::stringstream dataAgentPair
std::stringstream dataMinslr
std::stringstream dataRemoteAgent
std::stringstream dataLocalAgent
std::stringstream dataCommPerformance
LocalAgent * myData
RemoteAgentGroup * agentGroup
AgentPairList * agentPairList
KnownGlobal * oKnownGlobal
IcarRouting * routing
GeneralCommunicationService service
Icarqoc * oIcarModule
Detailed Description
Definition at line 47 of file IcarContext.h.
Constructor & Destructor Documentation
IcarContext() [1/2]
veins::IcarContext::IcarContext ()
Definition at line 33 of file IcarContext.cc.
{
 }
IcarContext() [2/2]
veins::IcarContext::IcarContext (LocalAgent * oMyData, KnownGlobal * pKnownGlobal, Icarqoc * pIcar)
Definition at line 20 of file IcarContext.cc.
{
         this->oKnownGlobal = pKnownGlobal;
         this->oIcarModule = pIcar;
         this->agentGroup = new RemoteAgentGroup();
         this->myData = oMyData;
         this->agentPairList = new AgentPairList();
         // data analysec
         AgentPair * inic = new AgentPair();
        // this->dataAgentPair
        //          << textDataAgentPair(-1, inic, true) << ";"  << std::endl;
         this->routing = new IcarRouting(agentGroup, agentPairList);
 }
References agentGroup, agentPairList, myData, oIcarModule, oKnownGlobal, and routing.
~IcarContext()
veins::IcarContext::~IcarContext () virtual
Definition at line 36 of file IcarContext.cc.
{
     // TODO Auto-generated destructor stub
 }
Member Function Documentation
callFinish()
void veins::IcarContext::callFinish ()
Definition at line 40 of file IcarContext.cc.
{
 }
changeLocalMobility()
void veins::IcarContext::changeLocalMobility ()
Definition at line 237 of file IcarContext.cc.
{
     if (!this->getMyData()->getLocalMobility()->getTraci()->isTerminated())
     {
         //update the data mobility of local agent
         this->getMyData()->getLocalMobility()->updateLocalMobilityPos();
         //update the data mobility of involved agent pairs
         this->updateAgentPairs(this->myData,this->myData->getMobilityInfo()->getActualMove()->getStartTime(), 5);
     }
 }
References veins::MobilityInfo::getActualMove(), veins::LocalAgent::getLocalMobility(), veins::Agent::getMobilityInfo(), getMyData(), veins::Move::getStartTime(), myData, updateAgentPairs(), and veins::LocalMobility::updateLocalMobilityPos().
Referenced by veins::Icarqoc::changeLocalMobility().
getAgentGroup()
RemoteAgentGroup * veins::IcarContext::getAgentGroup ()
Definition at line 408 of file IcarContext.cc.
{
     return agentGroup;
 }
References agentGroup.
getAgentPairList()
AgentPairList * veins::IcarContext::getAgentPairList ()
Definition at line 416 of file IcarContext.cc.
{
     return agentPairList;
 }
References agentPairList.
Referenced by veins::Icarqoc::finish(), and updateAgentPairs().
getIcarModule()
Icarqoc * veins::IcarContext::getIcarModule ()
Definition at line 432 of file IcarContext.cc.
{
     return oIcarModule;
 }
References oIcarModule.
getKnownGlobal()
KnownGlobal * veins::IcarContext::getKnownGlobal ()
Definition at line 440 of file IcarContext.cc.
{
     return oKnownGlobal;
 }
References oKnownGlobal.
getMsgTransmitterRange()
double veins::IcarContext::getMsgTransmitterRange (ICRMessage * m)
getMyData()
LocalAgent * veins::IcarContext::getMyData ()
Definition at line 424 of file IcarContext.cc.
{
     return myData;
 }
References myData.
Referenced by changeLocalMobility(), veins::Icarqoc::initialize(), and veins::MessageManager::sendICRMessage().
getRouting()
IcarRouting * veins::IcarContext::getRouting ()
Definition at line 448 of file IcarContext.cc.
{
     return routing;
 }
References routing.
getService()
GeneralCommunicationService veins::IcarContext::getService ()
Definition at line 456 of file IcarContext.cc.
{
     return service;
 }
References service.
infoTraceAgentPairList()
std::string veins::IcarContext::infoTraceAgentPairList ()
setAgentGroup()
void veins::IcarContext::setAgentGroup (RemoteAgentGroup * agentGroup)
Definition at line 412 of file IcarContext.cc.
{
     this->agentGroup = agentGroup;
 }
References agentGroup.
setAgentPairList()
void veins::IcarContext::setAgentPairList (AgentPairList * agentPairList)
Definition at line 420 of file IcarContext.cc.
{
     this->agentPairList = agentPairList;
 }
References agentPairList.
setIcarModule()
void veins::IcarContext::setIcarModule (Icarqoc * icarModule)
Definition at line 436 of file IcarContext.cc.
{
     oIcarModule = icarModule;
 }
References oIcarModule.
setKnownGlobal()
void veins::IcarContext::setKnownGlobal (KnownGlobal * knownGlobal)
Definition at line 444 of file IcarContext.cc.
{
     oKnownGlobal = knownGlobal;
 }
References oKnownGlobal.
setMyData()
void veins::IcarContext::setMyData (LocalAgent * myData)
Definition at line 428 of file IcarContext.cc.
{
     this->myData = myData;
 }
References myData.
setRouting()
void veins::IcarContext::setRouting (IcarRouting * routing)
Definition at line 452 of file IcarContext.cc.
{
     this->routing = routing;
 }
References routing.
setService()
void veins::IcarContext::setService (GeneralCommunicationService service)
Definition at line 460 of file IcarContext.cc.
{
     this->service = service;
 }
References service.
textDataAgentPair()
std::string veins::IcarContext::textDataAgentPair (int event, AgentPair * c, bool header = false)
Definition at line 277 of file IcarContext.cc.
{
     std::ostringstream ost, eventRel;
     int auxevent;
     //std::cout << endl << "begin : text Data AgentPair" << std::endl;
         ost << "";
             if (header){
                 ost << "simulation"
                         ";event"
                         ";timeStamp"
                         ";qtVeic"
                         ";periodApp"
                         ";PeriodMonitor"
                         ";measureAgentSX"
                         ";measureAgentSy"
                         ";measureSpeedS"
                         ";measureAgentDX"
                         ";measureAgentDy"
                         ";measurespeedD"
                         ";measureDistance" <<
                         ";calculatedDistance;distanceDifference;idLocal"<< c->infoTrace(true);
                 //std::cout << endl << "begin : head text Data AgentPair" << std::endl;
             }else
             {
                 auxevent = event;
                 // std::cout << endl << "begin : text Data AgentPair" << std::endl;
                  Move *mobAgentS = this->oKnownGlobal->getTraciMobility(c->getAgentS()->getId());
                  Move *mobAgentD = this->oKnownGlobal->getTraciMobility(c->getAgentD()->getId());
                  double measuredDistance = this->oKnownGlobal->calcTraciDistanceMobility(c->getAgentS()->getId(),c->getAgentD()->getId());
                  double Sx;
                  double Dx;
                  double Sy;
                  double Dy;
                  double Dspeed;
                  double Sspeed;
                  if (mobAgentS==NULL || mobAgentD==NULL )
                  {
                       Sx = 0;
                       Dx = 0;
                       Sy = 0;
                       Dy = 0;
                       Sspeed=0;
                       Dspeed=0;
                  }else{
                      Sx = mobAgentS->getStartPos().x;
                      Dx = mobAgentD->getStartPos().x;
                      Sy = mobAgentS->getStartPos().y;
                      Dy = mobAgentD->getStartPos().y;
                      Sspeed= this->oKnownGlobal->getTraci(c->getAgentS()->getId())->getTraci()->getSpeed();
                      Dspeed= this->oKnownGlobal->getTraci(c->getAgentD()->getId())->getTraci()->getSpeed();
                  }
                  if (c->getCalcRadius() < measuredDistance && event==this->oKnownGlobal->updatingPairFromReceivedMsg)
                  {
                      //eventRel.clear();
                      //eventRel << this->oKnownGlobal->OutOfRadiusUpdatingReceivedMsg;
                      auxevent =  this->oKnownGlobal->OutOfRadiusUpdatingReceivedMsg;
                  }
                  else {
                      if (c->getCalcRadius() < measuredDistance
                              &&  c->lastEvent!=this->oKnownGlobal->OutOfRadiusTracingChangedMobility)
                      {
                          //eventRel.clear();
                          c->lastEvent = this->oKnownGlobal->OutOfRadiusTracingChangedMobility;
                          //eventRel << this->oKnownGlobal->OutOfRadiusTracingChangedMobility;
                          auxevent =   this->oKnownGlobal->OutOfRadiusTracingChangedMobility;
                      }/*else{
                          if (this->oKnownGlobal->printUpdateChangedMobility)
{
                              eventRel << this->oKnownGlobal->updateTraceChangedMobility;
                          }else     eventRel << event;
                      }*/
                  }
                  ost     << this->oKnownGlobal->observationNameFile
                          //<< ";" << eventRel.str()
                          << ";" << auxevent
                          << ";" << simTime()
                          << ";" << this->oKnownGlobal->vehicleAmout
                          << ";" << this->oKnownGlobal->loadPeriodApp
                          << ";" << this->oIcarModule->loadPeriodMonitor
                          << ";" << Sx
                          << ";" << Sy
                          //<< ";" << mobAgentS->getSpeed()
                          << ";" << Sspeed //this->oKnownGlobal->getTraci(c->getAgentS()->getId())->getTraci()->getSpeed()
                          << ";" << Dx
                          << ";" << Dy
                          //<< ";" << mobAgentD->getSpeed()
                          << ";" << Dspeed //this->oKnownGlobal->getTraci(c->getAgentD()->getId())->getTraci()->getSpeed()
                          << ";" << measuredDistance
                          << ";" << c->getAgentPairMobility()->getDistancelr()
                          << ";" << measuredDistance - c->getAgentPairMobility()->getDistancelr()
                          << ";" << this->myData->getId()
                          << c->infoTrace(header);
             }
      return ost.str();
 }
References veins::KnownGlobal::calcTraciDistanceMobility(), veins::AgentPair::getAgentD(), veins::AgentPair::getAgentPairMobility(), veins::AgentPair::getAgentS(), veins::AgentPair::getCalcRadius(), veins::AgentPairMobility::getDistancelr(), veins::Agent::getId(), veins::TraCIMobility::getSpeed(), veins::Move::getStartPos(), veins::LocalMobility::getTraci(), veins::KnownGlobal::getTraci(), veins::KnownGlobal::getTraciMobility(), veins::AgentPair::infoTrace(), veins::AgentPair::lastEvent, veins::KnownGlobal::loadPeriodApp, veins::Icarqoc::loadPeriodMonitor, myData, veins::KnownGlobal::observationNameFile, oIcarModule, oKnownGlobal, veins::KnownGlobal::OutOfRadiusTracingChangedMobility, veins::KnownGlobal::OutOfRadiusUpdatingReceivedMsg, veins::KnownGlobal::vehicleAmout, veins::Coord::x, and veins::Coord::y.
Referenced by veins::Icarqoc::createVehicleTraces(), veins::Icarqoc::initialize(), updateAgentPairs(), and updateAgentPairsFromMsg().
updateAgentGroup()
RemoteAgent * veins::IcarContext::updateAgentGroup (ICRNode m, simtime_t pMsgReceivingTime)
Definition at line 384 of file IcarContext.cc.
{
     RemoteAgent* a = NULL;
     if (oIcrNode.nodeId!=-1)
     {
         if (myData->getId()!= oIcrNode.nodeId ){
             a = this->agentGroup->getRemoteAgent(oIcrNode.nodeId);
             if (a == NULL){
                 a = new RemoteAgent(pMsgReceivingTime, oIcrNode, 0);
                 this->agentGroup->knownRemoteAgents.push_back(a);
             }else
             {
                 a->updateRemoteAgent(pMsgReceivingTime, oIcrNode, 0);
             }
         }
     }
     return a;
 }
References agentGroup, veins::Agent::getId(), veins::RemoteAgentGroup::getRemoteAgent(), veins::RemoteAgentGroup::knownRemoteAgents, myData, veins::ICRNode::nodeId, and veins::RemoteAgent::updateRemoteAgent().
Referenced by updateAgentPairsFromMsg().
updateAgentPairs()
void veins::IcarContext::updateAgentPairs (Agent * agent, simtime_t timeStampData, int event)
Definition at line 248 of file IcarContext.cc.
{
     AgentPair *c=NULL;
     //double oldValidity=0;
     unsigned int index = 0;
         while (this->getAgentPairList()->agentPairs.size()> index)
         {
             c = dynamic_cast<AgentPair*>(this->getAgentPairList()->agentPairs[index]);
             if (c->getAgentD()->getId() == agent->getId() || c->getAgentS()->getId()== agent->getId())
             {
                 //oldValidity =c->getQoCChannel()->getTimeliness()->getValidityNow();
                 // if the channel is not fault
                 if(c->getCommnunicationState()!=CommState::faulty)
                         //&& c->getChannelMobility()->getMovementCurrentTime() <= timeStampData)
                 {
                     c->updateAgentPair();
                     this->dataAgentPair
                          << textDataAgentPair(event, c, false)<< ";" << std::endl;// << this->dataMsg  << std::endl;
                 }
             }
             ++index;
         }
     }
References veins::AgentPairList::agentPairs, dataAgentPair, CommState::faulty, veins::AgentPair::getAgentD(), getAgentPairList(), veins::AgentPair::getAgentS(), veins::AgentPair::getCommnunicationState(), veins::Agent::getId(), textDataAgentPair(), and veins::AgentPair::updateAgentPair().
Referenced by changeLocalMobility().
updateAgentPairsFromMsg()
void veins::IcarContext::updateAgentPairsFromMsg (ICRMessage * wsm, simtime_t pMsgReceivingTime)
Definition at line 44 of file IcarContext.cc.
 {
      //int sizeRouteNodes = wsm->getRouteNodeArraySize();
      ICRNode icrSource, icrDestiny;
      simtime_t  VTofNext;
      Agent * s = NULL;
      Agent * t = NULL;
      Agent * n = NULL;
      Agent * d = NULL;
      AgentPair * pair = NULL;
      //std::cout << endl << "begin updateAgentPairsFromMsg "<< wsm->getSourceNode().nodeId << endl;
      if (wsm->getSourceNode().nodeId != myData->getId())
      {
          s = updateAgentGroup(wsm->getSourceNode(), pMsgReceivingTime);
          pair = agentPairList->updatePairListFromMsg(wsm->getNumMsg(),s,
                  myData, pMsgReceivingTime, wsm->getSourceNode().msgTimeStamp,
                  this->oKnownGlobal->oRadiusEstimatorAgentPair, true,
                    0, 0.00, this->oKnownGlobal->loadPeriodApp,
                    this->oIcarModule->oMsgManager->getMsgRecvPower_dBm(wsm), this->oIcarModule->oMsgManager->getMsgRecvSnr(wsm));
          this->dataAgentPair
                   << textDataAgentPair(this->oKnownGlobal->updatingPairFromReceivedMsg, pair, false) << ";"  << std::endl;
          //std::cout << endl << "finish pair update "<< endl;
      }
      //std::cout << endl << "end updateAgentPairsFromMsg "<< wsm->getSourceNode().nodeId << endl;
 }
References agentPairList, dataAgentPair, veins::Agent::getId(), myData, oKnownGlobal, textDataAgentPair(), updateAgentGroup(), veins::AgentPairList::updatePairListFromMsg(), and veins::KnownGlobal::updatingPairFromReceivedMsg.
Referenced by updateContextfromMsg().
updateContextfromMsg()
void veins::IcarContext::updateContextfromMsg (ICRMessage * wsm, simtime_t pMsgReceivingTime)
Definition at line 464 of file IcarContext.cc.
{
     this->myData->getLocalCommInfo()->getLocalAgentCommPerformance()->addCorrectMsgRecievedMsg();
     updateAgentPairsFromMsg(wsm, pMsgReceivingTime);
 }
References LocalAgentCommPerformance::addCorrectMsgRecievedMsg(), veins::LocalCommInfo::getLocalAgentCommPerformance(), veins::LocalAgent::getLocalCommInfo(), myData, and updateAgentPairsFromMsg().
Referenced by veins::Icarqoc::handleLowerMsg().
Member Data Documentation
agentGroup
RemoteAgentGroup* veins::IcarContext::agentGroup
Definition at line 73 of file IcarContext.h.
Referenced by getAgentGroup(), IcarContext(), veins::MessageManager::sendIcarMessageService(), setAgentGroup(), and updateAgentGroup().
agentPairList
AgentPairList* veins::IcarContext::agentPairList
Definition at line 75 of file IcarContext.h.
Referenced by getAgentPairList(), IcarContext(), setAgentPairList(), and updateAgentPairsFromMsg().
dataAgentPair
std::stringstream veins::IcarContext::dataAgentPair
Definition at line 54 of file IcarContext.h.
Referenced by veins::Icarqoc::createVehicleTraces(), veins::Icarqoc::finish(), updateAgentPairs(), and updateAgentPairsFromMsg().
dataCommPerformance
std::stringstream veins::IcarContext::dataCommPerformance
Definition at line 66 of file IcarContext.h.
Referenced by veins::Icarqoc::finish(), and veins::Icarqoc::initialize().
dataLocalAgent
std::stringstream veins::IcarContext::dataLocalAgent
Definition at line 63 of file IcarContext.h.
dataMinslr
std::stringstream veins::IcarContext::dataMinslr
Definition at line 57 of file IcarContext.h.
dataRemoteAgent
std::stringstream veins::IcarContext::dataRemoteAgent
Definition at line 60 of file IcarContext.h.
Referenced by veins::Icarqoc::finish().
myData
LocalAgent* veins::IcarContext::myData
Definition at line 70 of file IcarContext.h.
Referenced by changeLocalMobility(), getMyData(), IcarContext(), veins::MessageManager::sendIcarMessageService(), setMyData(), textDataAgentPair(), updateAgentGroup(), updateAgentPairsFromMsg(), updateContextfromMsg(), and veins::Icarqoc::verifyRuleRadiusSet().
oIcarModule
Icarqoc* veins::IcarContext::oIcarModule
Definition at line 85 of file IcarContext.h.
Referenced by getIcarModule(), IcarContext(), setIcarModule(), and textDataAgentPair().
oKnownGlobal
KnownGlobal* veins::IcarContext::oKnownGlobal
Definition at line 77 of file IcarContext.h.
Referenced by getKnownGlobal(), IcarContext(), veins::MessageManager::sendICRMessage(), setKnownGlobal(), textDataAgentPair(), updateAgentPairsFromMsg(), and veins::Icarqoc::verifyRuleRadiusSet().
QoCQoSdataAgentPair
std::stringstream veins::IcarContext::QoCQoSdataAgentPair
Definition at line 51 of file IcarContext.h.
routing
IcarRouting* veins::IcarContext::routing
Definition at line 80 of file IcarContext.h.
Referenced by getRouting(), IcarContext(), and setRouting().
service
GeneralCommunicationService veins::IcarContext::service
Definition at line 83 of file IcarContext.h.
Referenced by getService(), and setService().
The documentation for this class was generated from the following files:
IcarContext.h
IcarContext.cc