Veins: veins::Routing Class Reference
veins::Routing Class Reference
#include <Routing.h>
Public Member Functions
Routing ()
virtual ~Routing ()
ForwardingNode * rule4 ()
ForwardingNode * getFowardNode (RemoteAgentGroup *groupAgent, AgentPairList *agentPairList, int64_t destinationId, int64_t sourceId, int64_t pAntecessorMsgId, double msgTimeToLive, Coord target1, Coord target2)
ForwardingNode * rule2 ()
ForwardingNode * rule3 ()
ForwardingNode * oldRule ()
Private Member Functions
ICarRoute * searchRoute (AgentPair *c)
ICarRoute * getRoute (int s, int d)
ICarRoute * getFowardNode (int s, int d)
ForwardingNode * searchNode ()
AgentPair * verifyAgentPairc (int64_t pSource, int64_t pDestination, string rule, double msgTTime)
ForwardingNode * verifyAgentPair (int64_t pSource, int64_t pDestination, string rule, double msgTTime)
ForwardingNode * verifyAgentPairInverse (int64_t pDestination, int64_t pSource, string rule, double msgTTime)
ForwardingNode * agentGeoNear (RemoteAgent *destination, string rule)
ForwardingNode * verifyAgentPairAneib (int64_t agentId, string rule, double msgTTime)
ForwardingNode * verifyConditionForwardAgent (AgentPair *c, string rule, double msgTTime)
ForwardingNode * verifyAgentPairNotNeighbor (int64_t pSource, int64_t pDestination, string rule, double msgTTime)
ForwardingNode * verifyConditionForwardNotNeighbor (AgentPair *c, string rule, double msgTTime)
Private Attributes
AgentPairList * agentPairList
int64_t destinationId
int64_t sourceId
double msgTimeToLive
Coord target1
Coord target2
double validityTime
RemoteAgentGroup * groupAgent
double userMessageLifeTime
double expectedConfidence
Detailed Description
Definition at line 29 of file Routing.h.
Constructor & Destructor Documentation
Routing()
veins::Routing::Routing ()
Definition at line 20 of file Routing.cc.
                  {
 }
~Routing()
veins::Routing::~Routing () virtual
Definition at line 23 of file Routing.cc.
                   {
 }
Member Function Documentation
agentGeoNear()
ForwardingNode* veins::Routing::agentGeoNear (RemoteAgent * destination, string rule) private
getFowardNode() [1/2]
ICarRoute * veins::Routing::getFowardNode (int s, int d) private
Definition at line 48 of file Routing.cc.
{
 }
Referenced by getRoute().
getFowardNode() [2/2]
ForwardingNode * veins::Routing::getFowardNode (RemoteAgentGroup * groupAgent, AgentPairList * agentPairList, int64_t destinationId, int64_t sourceId, int64_t pAntecessorMsgId, double msgTimeToLive, Coord target1, Coord target2)
Definition at line 73 of file Routing.cc.
 {
     this->groupAgent = groupAgent;
     this->agentPairList=pChannelList;
     this->destinationId = pDestinationId;
     //this->antecessorMsgId = pAntecessorMsgId;
     this->sourceId = pSourceId;
     this->msgTimeToLive = pMsgTimeToLive;
     this->target1 = pTarget1;
     this->target2 = pTarget2;
     return searchNode();
 }
References agentPairList, destinationId, groupAgent, msgTimeToLive, searchNode(), sourceId, target1, and target2.
getRoute()
ICarRoute * veins::Routing::getRoute (int s, int d) private
Definition at line 26 of file Routing.cc.
 {
     ICarRoute * icR=NULL;
     AgentPair * c = NULL;
     c = this->agentPairList->getAgentPair(s, d);
     if (c!=NULL)
     {
      if (c->isNeighbors())
      {
          icR = new ICarRoute(c->getQoCAgentPair()->getTimeliness()->getTimeoutValidity(),
                  c->getQoCAgentPair()->getTimeliness()->getCoConfianca(), 0);
      }else {
          icR = searchRoute(c);
      }
     }
     if (icR==NULL) icR = getFowardNode(s,d);
     return icR;
 }
References agentPairList, veins::AgentPairList::getAgentPair(), Timeliness::getCoConfianca(), getFowardNode(), veins::AgentPair::getQoCAgentPair(), veins::QoCInfo::getTimeliness(), Timeliness::getTimeoutValidity(), veins::AgentPair::isNeighbors(), and searchRoute().
oldRule()
ForwardingNode* veins::Routing::oldRule ()
rule2()
ForwardingNode * veins::Routing::rule2 ()
Definition at line 130 of file Routing.cc.
 {
     ForwardingNode * fowardNode = new ForwardingNode();
     std::vector<AgentPair *>agentPairs = agentPairList->listNeighbors(destinationId);
     bool find=false;
     unsigned int index = 0;
     AgentPair *  c =NULL;
     AgentPair * cInt = NULL;
     while (!find && agentPairs.size()> index)
     {
             c = dynamic_cast<AgentPair*>(agentPairs[index]);
             //verifica se o canal  vizinho
             if ((c->getCommnunicationState() == CommState::communicating || c->getCommnunicationState() == CommState::transmitting))
                 //&& ( simTime() + c->getMessageTTime()).dbl() <= msgTimeToLive)
                    // && ( simTime() + c->getMessageTTime())<= msgTimeToLive && (simTime() + c->getQoCChannel()->getTimeliness()->getValidity())>=msgTimeToLive)
              {
                 if (c->getAgentD()->getId()==destinationId)
                 {
                     cInt = verifyAgentPairc( sourceId, c->getAgentS()->getId(), "2", c->getMessageTTime());
                     if (cInt != NULL) {
                         fowardNode->update("2", c->getAgentS()->getId(), cInt, 0);
                     }
                     if (fowardNode->getFowardId()!=-1) find = true;
                         //std::cout << endl << "R1: " << r1_foward->getFowardId() << endl;
                     if (!find){
                         cInt = verifyAgentPairc( c->getAgentS()->getId(), sourceId, "3", c->getMessageTTime());
                         if (cInt != NULL) {
                             fowardNode->update("3", c->getAgentS()->getId(), cInt, 0);
                         }
                     }
                 }
              }
             index++;
     }
     cInt = NULL;
     if (fowardNode->getFowardId()==-1){
         index = 0;
         while (!find && agentPairs.size()> index)
         {
                 c = dynamic_cast<AgentPair*>(agentPairs[index]);
                 //verifica se o canal  vizinho
                 if ((c->getCommnunicationState() == CommState::communicating || c->getCommnunicationState() == CommState::transmitting))
                         //&& ( simTime() + c->getMessageTTime()).dbl() <= msgTimeToLive)
                        // && ( simTime() + c->getMessageTTime())<= msgTimeToLive && (simTime() + c->getQoCChannel()->getTimeliness()->getValidity())>=msgTimeToLive)
                  {
                     if (c->getAgentS()->getId()==destinationId)
                     {
                         cInt = verifyAgentPairc( sourceId, c->getAgentD()->getId(), "4", c->getMessageTTime());
                         if (cInt != NULL) {
                             fowardNode->update("4", c->getAgentD()->getId(), cInt, 0);
                         }
                         if (fowardNode->getFowardId()!=-1) find = true;
                             //std::cout << endl << "R1: " << r1_foward->getFowardId() << endl;
                         if (!find){
                             cInt = verifyAgentPairc( c->getAgentD()->getId(), sourceId, "5", c->getMessageTTime());
                             if (cInt != NULL) {
                                 fowardNode->update("5", c->getAgentD()->getId(), cInt, 0);
                             }
                         }
                     }
                  }
                 index++;
         }
     }
     return fowardNode;
 }
References agentPairList, CommState::communicating, destinationId, veins::AgentPair::getAgentD(), veins::AgentPair::getAgentS(), veins::AgentPair::getCommnunicationState(), veins::ForwardingNode::getFowardId(), veins::Agent::getId(), veins::AgentPair::getMessageTTime(), veins::AgentPairList::listNeighbors(), sourceId, CommState::transmitting, veins::ForwardingNode::update(), and verifyAgentPairc().
Referenced by searchNode().
rule3()
ForwardingNode * veins::Routing::rule3 ()
Definition at line 210 of file Routing.cc.
 {
     ForwardingNode * fowardNode = new ForwardingNode();
     std::vector<AgentPair *>agentPairs = agentPairList->listNeighbors(sourceId);
     bool find=false;
     unsigned int index = 0;
     AgentPair *  c =NULL;
     while (!find && agentPairs.size()> index)
     {
             c = dynamic_cast<AgentPair*>(agentPairs[index]);
             if ((c->getCommnunicationState() == CommState::communicating || c->getCommnunicationState() == CommState::transmitting)
                 && c->isNeighbors() ) //&& ( simTime() + c->getMessageTTime()).dbl() <= msgTimeToLive)
             {
                 if (c->getAgentS()->getId()==sourceId)
                 {
                      //  R3 - existe um agents vizinho comunivel entre o agente local e o destino
                         fowardNode=verifyAgentPairNotNeighbor(c->getAgentD()->getId(), destinationId, "6", c->getMessageTTime());
                         if (fowardNode->getFowardId()!=-1) find = true;
                         //std::cout << endl << "R1: " << r1_foward->getFowardId() << endl;
                 } else{
                     //  R3 - existe um agents vizinho comunivel entre o agente local e o destino
                        fowardNode=verifyAgentPairNotNeighbor(c->getAgentS()->getId(), destinationId, "7", c->getMessageTTime());
                        //if (fowardNode->getFowardId()!=-1) find = true;
                        //std::cout << endl << "R1: " << r1_foward->getFowardId() << endl;
                 }
              }
             index++;
     }
     return fowardNode;
 }
References agentPairList, CommState::communicating, destinationId, veins::AgentPair::getAgentD(), veins::AgentPair::getAgentS(), veins::AgentPair::getCommnunicationState(), veins::ForwardingNode::getFowardId(), veins::Agent::getId(), veins::AgentPair::getMessageTTime(), veins::AgentPair::isNeighbors(), veins::AgentPairList::listNeighbors(), sourceId, CommState::transmitting, and verifyAgentPairNotNeighbor().
Referenced by searchNode().
rule4()
ForwardingNode * veins::Routing::rule4 ()
Definition at line 246 of file Routing.cc.
 {
     ForwardingNode * fowardNode = new ForwardingNode();
     ForwardingNode * fowardNodeNotNeighbor = new ForwardingNode();
     ForwardingNode * fowardNodeNeighbor = new ForwardingNode();
     std::vector<AgentPair *>agentPairs = agentPairList->listAgentPairsWith(destinationId);
     std::vector<AgentPair *>agentPairsInt = agentPairList->listNeighbors(sourceId);
     bool find=false;
     unsigned int index = 0;
     unsigned int indexI;
     int fd, fs;
     AgentPair *  cd =NULL;
     AgentPair *  cs =NULL;
     AgentPair *  cf =NULL;
     //std::cout << channels.size() << "  routing class = " << channelsInt.size() << endl;
     while (!find && agentPairs.size()> index)
     {
             cd = dynamic_cast<AgentPair*>(agentPairs[index]);
             if ((cd->getCommnunicationState() == CommState::communicating || cd->getCommnunicationState() == CommState::transmitting)
                     && ( simTime() + cd->getMessageTTime()).dbl() <= msgTimeToLive)
              {
                 if (cd->getAgentD()->getId()==destinationId) fd =  cd->getAgentS()->getId();
                 else fd =  cd->getAgentD()->getId();
                 indexI = 0;
                 while (!find && agentPairsInt.size()> indexI)
                 {
                         cs = dynamic_cast<AgentPair*>(agentPairsInt[indexI]);
                         if ((cs->getCommnunicationState() == CommState::communicating || cs->getCommnunicationState() == CommState::transmitting))
{
                                 if (cs->getAgentD()->getId()==sourceId)
                                     fs = cs->getAgentS()->getId();
                                 else fs = cs->getAgentD()->getId();
                                 if (cd->isNeighbors())
{
                                     fowardNodeNeighbor=verifyAgentPair(fs, fd, "8", cs->getMessageTTime());
                                     if (fowardNodeNeighbor->getFowardId()!=-1) find = true;
                                     std::cout << " passei aqui routing class 1" << endl;
                                     if (fowardNodeNeighbor->getFowardId()==-1)
                                         fowardNodeNeighbor=verifyAgentPair(fd, fs, "9", cs->getMessageTTime());
                                     if (fowardNodeNeighbor->getFowardId()==-1)
                                         fowardNodeNeighbor=verifyAgentPairNotNeighbor(fd, fs, "10", cs->getMessageTTime());
                                     if (fowardNodeNeighbor->getFowardId()==-1)
                                         fowardNodeNeighbor=verifyAgentPairNotNeighbor(fs, fd, "11", cs->getMessageTTime());
                                     cf = cs;
                                     if (fowardNodeNeighbor->getFowardId()!=-1) find = true;
                                 }else
{
                                     fowardNodeNotNeighbor=verifyAgentPair(fs, fd, "12", cs->getMessageTTime());
                                     if (fowardNodeNotNeighbor->getFowardId()==-1)
                                         fowardNodeNotNeighbor=verifyAgentPair(fd, fs, "13", cs->getMessageTTime());
                                     if (fowardNodeNotNeighbor->getFowardId()==-1)
                                         fowardNodeNotNeighbor=verifyAgentPairNotNeighbor(fd, fs, "14", cs->getMessageTTime());
                                     if (fowardNodeNotNeighbor->getFowardId()==-1)
                                         fowardNodeNotNeighbor=verifyAgentPairNotNeighbor(fs, fd, "15", cs->getMessageTTime());
                                     cf = cs;
                                 }
                           }
                         indexI++;
                 }//endwhile
              }//endif
             index++;
     }//endwhile
     std::cout << " passei aqui routing class 2" << endl;
     if (fowardNodeNeighbor->getFowardId()!=-1)
     {
         fowardNode = fowardNodeNeighbor;
     }else
     {
         if (fowardNodeNotNeighbor->getFowardId()!=-1)
             fowardNode = fowardNodeNotNeighbor;
     }
     if (fowardNode->getFowardId()!=-1) {
         if (cf->getAgentD()->getId() == sourceId)
         {
             fowardNode->setFowardId(cf->getAgentS()->getId());
             fowardNode->setAgentPair(cf);
         }else{
             fowardNode->setFowardId(cf->getAgentD()->getId());
             fowardNode->setAgentPair(cf);
         }
        // std::cout << " passei aqui routing class 3  agentOrigem=" << sourceId << " agent channel f=" << fowardNode->getFowardId() << " agent channel d="
        //         << fowardNode->getChannel()->getAgentD()->getId()
        // << " agent channel S=" << fowardNode->getChannel()->getAgentS()->getId() << endl;
     }
     std::cout << " passei aqui routing class 4  agentOrigem=" << sourceId << " agent channel D=" <<
             destinationId << "   forward="<< fowardNode->getFowardId() << endl;
     return fowardNode;
 }
References agentPairList, CommState::communicating, destinationId, veins::AgentPair::getAgentD(), veins::AgentPair::getAgentS(), veins::AgentPair::getCommnunicationState(), veins::ForwardingNode::getFowardId(), veins::Agent::getId(), veins::AgentPair::getMessageTTime(), veins::AgentPair::isNeighbors(), veins::AgentPairList::listAgentPairsWith(), veins::AgentPairList::listNeighbors(), msgTimeToLive, veins::ForwardingNode::setAgentPair(), veins::ForwardingNode::setFowardId(), sourceId, CommState::transmitting, verifyAgentPair(), and verifyAgentPairNotNeighbor().
Referenced by searchNode().
searchNode()
ForwardingNode * veins::Routing::searchNode () private
Definition at line 92 of file Routing.cc.
 {
     // inicializacao dos nos
     AgentPair * c = NULL;
     ForwardingNode * foward = new ForwardingNode();
     RemoteAgent *agDestination = this->groupAgent->getRemoteAgent(destinationId);
     if (agDestination != NULL)
         if (agDestination->getId() != -1)
         {
             // s->d
             c = verifyAgentPairc( this->sourceId, this->destinationId,"0", this->msgTimeToLive);
             if (c!=NULL)
             {
                 foward->update("0", this->destinationId, c, 0);
             }else
             {
                 // d-> s
                 c = verifyAgentPairc(this->destinationId,this->sourceId, "1", this->msgTimeToLive);
                 if (c!=NULL)
                 {
                     foward->update("1", this->destinationId, c, 0);
                 }else
                 {
                     //std::cout << endl << "R0" << r0_foward->getFowardId() << endl;
                      foward = rule2();
                      if (foward->getFowardId()==-1)
                         foward = rule3();
                          if (foward->getFowardId()==-1)
                            foward = rule4();
                      //         if (foward->getFowardId()==-1)
                      //             foward = oldRule();
                 }
               }
           }
     return foward;
 }
References destinationId, veins::ForwardingNode::getFowardId(), veins::Agent::getId(), veins::RemoteAgentGroup::getRemoteAgent(), groupAgent, msgTimeToLive, rule2(), rule3(), rule4(), sourceId, veins::ForwardingNode::update(), and verifyAgentPairc().
Referenced by getFowardNode().
searchRoute()
ICarRoute * veins::Routing::searchRoute (AgentPair * c) private
Definition at line 53 of file Routing.cc.
{
     bool find = false;
     unsigned int index=0;
     ICarRoute * icR;
     icR = NULL;
     while (!find && c->pairRoutes.size() > index)
     {
         c->pairRoutes.at(index)->update();
         if (c->pairRoutes.at(index)->qocValidityTime > userMessageLifeTime
                 && c->pairRoutes.at(index)->qocConfidence >= expectedConfidence )
         {
             find = true;
             icR = c->pairRoutes.at(index);
         }
     }
     return icR;
 }
References expectedConfidence, veins::AgentPair::pairRoutes, and userMessageLifeTime.
Referenced by getRoute().
verifyAgentPair()
ForwardingNode * veins::Routing::verifyAgentPair (int64_t pSource, int64_t pDestination, string rule, double msgTTime) private
Definition at line 386 of file Routing.cc.
 {
     AgentPair *  c = agentPairList->getAgentPair(pSource, pDestination);
     return verifyConditionForwardAgent(c, rule, msgTTime);
 }
References agentPairList, veins::AgentPairList::getAgentPair(), and verifyConditionForwardAgent().
Referenced by rule4().
verifyAgentPairAneib()
ForwardingNode * veins::Routing::verifyAgentPairAneib (int64_t agentId, string rule, double msgTTime) private
Definition at line 408 of file Routing.cc.
 {
         ForwardingNode * fAgent = new ForwardingNode();
         AgentPair *c=NULL;
         bool find=false;
         unsigned int index = 0;
         while (!find && agentPairList->agentPairs.size()> index)
         {
             c = dynamic_cast<AgentPair*>(agentPairList->agentPairs[index]);
             fAgent = verifyConditionForwardAgent(c, rule, msgTTime);
             if (fAgent->getFowardId()!= -1) find = true;
             index++;
         }
     return fAgent;
 }
References agentPairList, veins::AgentPairList::agentPairs, veins::ForwardingNode::getFowardId(), and verifyConditionForwardAgent().
verifyAgentPairc()
AgentPair * veins::Routing::verifyAgentPairc (int64_t pSource, int64_t pDestination, string rule, double msgTTime) private
Definition at line 362 of file Routing.cc.
 {
     AgentPair * resp = NULL;
     AgentPair *  c = agentPairList->getAgentPair(pSource, pDestination);
     if (c!=NULL)
     {
         //if (c->getCommnunicationState()==-1)
             //std::cout << endl << c->info() << endl;
         //verify the communication state and if is neighbor
             if ((c->getCommnunicationState()== CommState::transmitting || c->getCommnunicationState()== CommState::communicating)
                 && c->isNeighbors()) //  && ( simTime() + c->getMessageTTime()).dbl() <= msgTimeToLive)
                 {
                     resp = c;
                 }
      }
     return resp;
 }
References agentPairList, CommState::communicating, veins::AgentPairList::getAgentPair(), veins::AgentPair::getCommnunicationState(), veins::AgentPair::isNeighbors(), and CommState::transmitting.
Referenced by rule2(), and searchNode().
verifyAgentPairInverse()
ForwardingNode * veins::Routing::verifyAgentPairInverse (int64_t pDestination, int64_t pSource, string rule, double msgTTime) private
Definition at line 437 of file Routing.cc.
 {
     AgentPair *  c = agentPairList->getAgentPair(pSource, pDestination);
     return verifyConditionForwardAgent(c, rule, msgTTime);
 }
References agentPairList, veins::AgentPairList::getAgentPair(), and verifyConditionForwardAgent().
verifyAgentPairNotNeighbor()
ForwardingNode * veins::Routing::verifyAgentPairNotNeighbor (int64_t pSource, int64_t pDestination, string rule, double msgTTime) private
Definition at line 398 of file Routing.cc.
 {
     AgentPair *  c = agentPairList->getAgentPair(pSource, pDestination);
     return verifyConditionForwardNotNeighbor(c, rule, msgTTime);
 }
References agentPairList, veins::AgentPairList::getAgentPair(), and verifyConditionForwardNotNeighbor().
Referenced by rule3(), and rule4().
verifyConditionForwardAgent()
ForwardingNode * veins::Routing::verifyConditionForwardAgent (AgentPair * c, string rule, double msgTTime) private
Definition at line 448 of file Routing.cc.
 {
     ForwardingNode * fAgent = new ForwardingNode();
     if (c!=NULL)
     {
         //verify the communication state and if is neighbor
             if ((c->getCommnunicationState()== CommState::transmitting || c->getCommnunicationState()== CommState::communicating)
                 && c->isNeighbors()) //  && ( simTime() + c->getMessageTTime()).dbl() <= msgTimeToLive)
                 {
                     fAgent->update(rule, c->getAgentS()->getId(), c, 0);
                 }
         }
     return fAgent;
 }
References CommState::communicating, veins::AgentPair::getAgentS(), veins::AgentPair::getCommnunicationState(), veins::Agent::getId(), veins::AgentPair::isNeighbors(), CommState::transmitting, and veins::ForwardingNode::update().
Referenced by verifyAgentPair(), verifyAgentPairAneib(), and verifyAgentPairInverse().
verifyConditionForwardNotNeighbor()
ForwardingNode * veins::Routing::verifyConditionForwardNotNeighbor (AgentPair * c, string rule, double msgTTime) private
Definition at line 468 of file Routing.cc.
 {
     ForwardingNode * fAgent = new ForwardingNode();
     if (c!=NULL)
     {
           //verify the communication state and if is neighbor
             if ((c->getCommnunicationState()== CommState::transmitting || c->getCommnunicationState()== CommState::communicating))
                    // && ( simTime() + c->getMessageTTime()).dbl() <= msgTimeToLive)
                 {
                     fAgent->update(rule, c->getAgentS()->getId(), c, 0);
                 }
         }
     return fAgent;
 }
References CommState::communicating, veins::AgentPair::getAgentS(), veins::AgentPair::getCommnunicationState(), veins::Agent::getId(), CommState::transmitting, and veins::ForwardingNode::update().
Referenced by verifyAgentPairNotNeighbor().
Member Data Documentation
agentPairList
AgentPairList* veins::Routing::agentPairList private
Definition at line 31 of file Routing.h.
Referenced by getFowardNode(), getRoute(), rule2(), rule3(), rule4(), verifyAgentPair(), verifyAgentPairAneib(), verifyAgentPairc(), verifyAgentPairInverse(), and verifyAgentPairNotNeighbor().
destinationId
int64_t veins::Routing::destinationId private
Definition at line 32 of file Routing.h.
Referenced by getFowardNode(), rule2(), rule3(), rule4(), and searchNode().
expectedConfidence
double veins::Routing::expectedConfidence private
Definition at line 42 of file Routing.h.
Referenced by searchRoute().
groupAgent
RemoteAgentGroup* veins::Routing::groupAgent private
Definition at line 40 of file Routing.h.
Referenced by getFowardNode(), and searchNode().
msgTimeToLive
double veins::Routing::msgTimeToLive private
Definition at line 36 of file Routing.h.
Referenced by getFowardNode(), rule4(), and searchNode().
sourceId
int64_t veins::Routing::sourceId private
Definition at line 33 of file Routing.h.
Referenced by getFowardNode(), rule2(), rule3(), rule4(), and searchNode().
target1
Coord veins::Routing::target1 private
Definition at line 37 of file Routing.h.
Referenced by getFowardNode().
target2
Coord veins::Routing::target2 private
Definition at line 38 of file Routing.h.
Referenced by getFowardNode().
userMessageLifeTime
double veins::Routing::userMessageLifeTime private
Definition at line 41 of file Routing.h.
Referenced by searchRoute().
validityTime
double veins::Routing::validityTime private
Definition at line 39 of file Routing.h.
The documentation for this class was generated from the following files:
Routing.h
Routing.cc