My Project: veins::Agent
veins::Agent
Uma breve descrição da classe.
#include <Agent.h>
Public Member Functions
Agent (int64_t id, std::string name)
Agent ()
Construtor padrão.
std::string info ()
std::string infoTrace (bool header, std::string idagent)
int64_t getId ()
Método para obter o valor atual.
void setId (int64_t id)
Método para definir um valor.
virtual ~Agent ()
virtual MobilityInfo * getMobilityInfo ()
virtual void setMobilityInfo (MobilityInfo *mobilityInfo)
virtual double getSetRadius ()
virtual void setSetRadius (double setRadius)
virtual std::string getAgentName ()
virtual void setAgentName (std::string agentName)
CommInfo * getCommInfo ()
void setCommInfo (CommInfo *commInfo)
Public Attributes
MobilityInfo * mobilityInfo
CommInfo * commInfo
QoCInfo * qocInfo
Private Attributes
int64_t id = -1
Armazena o valor da classe.
std::string agentName
Armazena o valor da classe.
double setRadius
Detailed Description
Uma breve descrição da classe.
Uma descrição mais detalhada da classe, explicando sua funcionalidade e propósito.
Definition at line 34 of file Agent.h.
Constructor & Destructor Documentation
Agent() [1/2]
veins::Agent::Agent (int64_t id, std::string name)
Definition at line 20 of file Agent.cc.
{
     setId(id);
     setAgentName(name);
 }
References setAgentName(), and setId().
Agent() [2/2]
veins::Agent::Agent ()
Construtor padrão.
Inicializa os membros da classe.
Definition at line 25 of file Agent.cc.
             {
     this->id = -1;
 }
~Agent()
veins::Agent::~Agent () virtual
Definition at line 56 of file Agent.cc.
               {
     delete(this);
 }
Member Function Documentation
getAgentName()
std::string veins::Agent::getAgentName () virtual
Definition at line 68 of file Agent.cc.
{
     return agentName;
 }
References agentName.
Referenced by veins::KnownGlobal::getStringNamefromIdAgent().
getCommInfo()
CommInfo * veins::Agent::getCommInfo ()
Definition at line 72 of file Agent.cc.
{
     return commInfo;
 }
References commInfo.
getId()
int64_t veins::Agent::getId ()
Método para obter o valor atual.
Returns
O valor armazenado.
Definition at line 29 of file Agent.cc.
                      {
     return id;
 }
References id.
Referenced by veins::AgentPairList::calcMaxDistancelr(), veins::AgentPairList::calcMaxSlr(), veins::AgentPairList::calcMinDistancelr(), veins::AgentPairList::calcMinSlr(), veins::Icarqoc::createVehicleTraces(), veins::Icarqoc::finish(), veins::AgentPairList::getAgentPair(), veins::AgentPairList::getAgentPairIndex(), veins::IcarRouting::getFowardNode(), veins::KnownGlobal::getIntNamefromIdAgent(), veins::RemoteAgentGroup::getRemoteAgent(), veins::RemoteAgentGroup::getRemoteAgentIndex(), veins::KnownGlobal::getStringNamefromIdAgent(), veins::Icarqoc::handleSelfMsg(), veins::AgentPair::infoTrace(), veins::Icarqoc::initialize(), veins::AgentPairList::listAgentPairsWith(), veins::AgentPairList::listNeighbors(), veins::MessageManager::prepareICRNode(), veins::Routing::rule2(), veins::Routing::rule3(), veins::Routing::rule4(), veins::Routing::searchNode(), veins::MessageManager::sendIcarMessageService(), veins::IcarContext::textDataAgentPair(), veins::ForwardingNode::update(), veins::IcarContext::updateAgentGroup(), veins::IcarContext::updateAgentPairs(), veins::IcarContext::updateAgentPairsFromMsg(), veins::AgentPairList::updatePairListFromMsg(), veins::Routing::verifyConditionForwardAgent(), and veins::Routing::verifyConditionForwardNotNeighbor().
getMobilityInfo()
MobilityInfo * veins::Agent::getMobilityInfo () virtual
Reimplemented in veins::RemoteAgent.
Definition at line 60 of file Agent.cc.
{
     return mobilityInfo;
 }
References mobilityInfo.
Referenced by veins::TimelinessAgentPair::calcAge(), veins::AgentPairMobility::calcDistance(), veins::TimelinessAgentPair::calcLeicosseno(), veins::AgentPairList::calcMaxDistancelr(), veins::AgentPairList::calcMinDistancelr(), veins::AgentPairMobility::calcRelativeSpeed(), veins::KnownGlobal::calcTraciDistanceMobility(), veins::TimelinessAgentPair::calcValidityTeste(), veins::IcarContext::changeLocalMobility(), veins::LocalAgent::getLocalMobility(), infoTrace(), veins::MessageManager::prepareICRNode(), veins::AgentPair::setCalcRadius(), and veins::LocalAgent::updateLocalAgent().
getSetRadius()
double veins::Agent::getSetRadius () virtual
Definition at line 64 of file Agent.cc.
{
     return setRadius;
 }
References setRadius.
Referenced by veins::AgentPair::AgentPair(), veins::AgentPair::updateAgentPair(), and veins::Icarqoc::verifyRuleRadiusSet().
info()
std::string veins::Agent::info ()
Definition at line 37 of file Agent.cc.
                       {
     std::ostringstream ost;
     ost << "  Agent ID: " << this->id;
     return ost.str();
 }
References id.
Referenced by veins::AgentPair::info(), veins::LocalAgent::info(), and veins::RemoteAgent::info().
infoTrace()
std::string veins::Agent::infoTrace (bool header = false, std::string idagent = "")
Definition at line 44 of file Agent.cc.
{
     std::ostringstream ost;
     if (this->getMobilityInfo()!=NULL){
     if (header)
         ost << ";AgentId" << idagent << ";agentName" << idagent << this->getMobilityInfo()->infoTrace(header, idagent) ;
     else
         ost <<";" << this->id<< ";" << this->agentName << this->getMobilityInfo()->infoTrace(header, idagent);
     }
     return ost.str();
 }
References agentName, getMobilityInfo(), and veins::MobilityInfo::infoTrace().
Referenced by veins::AgentPair::infoTrace(), veins::LocalAgent::infoTrace(), and veins::RemoteAgent::infoTrace().
setAgentName()
void veins::Agent::setAgentName (std::string agentName) virtual
Definition at line 80 of file Agent.cc.
{
     this->agentName = agentName;
 }
References agentName.
Referenced by Agent(), veins::RemoteAgent::createAgent(), veins::LocalAgent::LocalAgent(), and veins::RemoteAgent::RemoteAgent().
setCommInfo()
void veins::Agent::setCommInfo (CommInfo * commInfo)
Definition at line 76 of file Agent.cc.
{
     this->commInfo = commInfo;
 }
References commInfo.
Referenced by veins::RemoteAgent::createAgent(), and veins::RemoteAgent::RemoteAgent().
setId()
void veins::Agent::setId (int64_t id)
Método para definir um valor.
Parameters
value O valor a ser definido.
Definition at line 33 of file Agent.cc.
{
     this->id = id;
 }
References id.
Referenced by Agent(), veins::RemoteAgent::createAgent(), veins::LocalAgent::LocalAgent(), and veins::RemoteAgent::RemoteAgent().
setMobilityInfo()
void veins::Agent::setMobilityInfo (MobilityInfo * mobilityInfo) virtual
Definition at line 88 of file Agent.cc.
{
     this->mobilityInfo = mobilityInfo;
 }
References mobilityInfo.
Referenced by veins::RemoteAgent::createAgent(), veins::LocalAgent::LocalAgent(), and veins::RemoteAgent::RemoteAgent().
setSetRadius()
void veins::Agent::setSetRadius (double setRadius) virtual
Definition at line 84 of file Agent.cc.
{
     this->setRadius = setRadius;
 }
References setRadius.
Referenced by veins::RemoteAgent::createAgent(), veins::Icarqoc::initialize(), and veins::RemoteAgent::RemoteAgent().
Member Data Documentation
agentName
std::string veins::Agent::agentName private
Armazena o valor da classe.
Definition at line 37 of file Agent.h.
Referenced by getAgentName(), infoTrace(), and setAgentName().
commInfo
CommInfo* veins::Agent::commInfo
Definition at line 44 of file Agent.h.
Referenced by getCommInfo(), veins::LocalAgent::getLocalCommInfo(), veins::RemoteAgent::getRemoteAgentCommInfo(), veins::LocalAgent::LocalAgent(), and setCommInfo().
id
int64_t veins::Agent::id = -1 private
Armazena o valor da classe.
Definition at line 36 of file Agent.h.
Referenced by getId(), info(), and setId().
mobilityInfo
MobilityInfo* veins::Agent::mobilityInfo
Definition at line 43 of file Agent.h.
Referenced by getMobilityInfo(), veins::RemoteAgent::getMobilityInfo(), and setMobilityInfo().
qocInfo
QoCInfo* veins::Agent::qocInfo
Definition at line 45 of file Agent.h.
Referenced by veins::RemoteAgent::createAgent(), and veins::RemoteAgent::RemoteAgent().
setRadius
double veins::Agent::setRadius private
Definition at line 39 of file Agent.h.
Referenced by veins::RemoteAgent::createAgent(), getSetRadius(), veins::RemoteAgent::RemoteAgent(), setSetRadius(), and veins::RemoteAgent::updateRemoteAgent().
The documentation for this class was generated from the following files:
Agent.h
Agent.cc