My Project: veins::RemoteMobility
veins::RemoteMobility
#include <RemoteMobility.h>
Public Member Functions
RemoteMobility ()
virtual ~RemoteMobility ()
RemoteMobility (simtime_t tsStart, double x, double y, double z, double speed, double maxSpeed, float acceleration, float angle)
void updateMobilityInfo (simtime_t tsStart, double x, double y, double z, double speed, double maxSpeed, float acceleration, float angle)
Public Member Functions inherited from veins::MobilityInfo
MobilityInfo ()
virtual ~MobilityInfo ()
std::string info ()
MobilityInfo (Move *mSrc)
virtual Move * getLastMove ()
float getMaxSpeed ()
Returns a string with the value of the coordinate.
void setMaxSpeed (float maxSpeed)
virtual double calcEuclideanDistanceAgentMoving ()
double calcEuclideanDistancelr (Coord l, Coord r)
virtual std::string moveInfoTrace (bool header)
Returns information about the current state.
std::string infoTrace (bool header, std::string idagent)
Returns information about the current state.
float getAcceleration ()
void setAcceleration (float acceleration)
Move * getActualMove ()
void setActualMove (Move *actualMove)
double getSensorPeriod ()
void setSensorPeriod (float sensorPeriod)
int getQuadrant (double angleRad)
float getAngle ()
Coord getPositionAtTime (simtime_t pTime)
void setAngle (float angle)
double getAge ()
void setAge (double age)
const Move * getCollectedMove ()
void setCollectedMove (Move *collectedMove)
Additional Inherited Members
Protected Member Functions inherited from veins::MobilityInfo
void setLastMove (Move *pMove)
void calcAcceleration ()
Protected Attributes inherited from veins::MobilityInfo
Move * actualMove = new Move()
current vehicle movement
Move * lastMove = new Move()
last vehicle movement before current position
Move * collectedMove = new Move()
collected vehicle movement
float maxSpeed =0
float sensorPeriod
float acceleration
float angle
double age
Detailed Description
Definition at line 25 of file RemoteMobility.h.
Constructor & Destructor Documentation
RemoteMobility() [1/2]
veins::RemoteMobility::RemoteMobility ()
Definition at line 20 of file RemoteMobility.cc.
{
     // TODO Auto-generated constructor stub
 }
~RemoteMobility()
veins::RemoteMobility::~RemoteMobility () virtual
Definition at line 50 of file RemoteMobility.cc.
{
 }
RemoteMobility() [2/2]
veins::RemoteMobility::RemoteMobility (simtime_t tsStart, double x, double y, double z, double speed, double maxSpeed, float acceleration, float angle)
Definition at line 24 of file RemoteMobility.cc.
{
     this->setActualMove(new Move());
     updateMobilityInfo(tsStart, x, y, z, speed, maxSpeed, acceleration, angle);
 }
References veins::MobilityInfo::acceleration, veins::MobilityInfo::angle, veins::MobilityInfo::maxSpeed, veins::MobilityInfo::setActualMove(), and updateMobilityInfo().
Member Function Documentation
updateMobilityInfo()
void veins::RemoteMobility::updateMobilityInfo (simtime_t tsStart, double x, double y, double z, double speed, double maxSpeed, float acceleration, float angle)
Definition at line 31 of file RemoteMobility.cc.
{
     Move * om = new Move();
     om->setStart(Coord(x, y,z), tsStart);
     om->setSpeed(speed);
     this->setCollectedMove(om);
     Move * om1 = new Move();
     om1->setStart(Coord(x, y,z), tsStart);
     om1->setSpeed(speed);
     this->setActualMove(om1);
     this->setMaxSpeed(maxSpeed);
     this->setAcceleration(acceleration);
     this->setAngle(angle);
     //simtime_t timeNow = simTime();
     //this->actualMove->setStart(this->getPositionAtTime(timeNow),timeNow);
 }
References veins::MobilityInfo::setAcceleration(), veins::MobilityInfo::setActualMove(), veins::MobilityInfo::setAngle(), veins::MobilityInfo::setCollectedMove(), veins::MobilityInfo::setMaxSpeed(), veins::Move::setSpeed(), and veins::Move::setStart().
Referenced by RemoteMobility(), and veins::RemoteAgent::updateRemoteAgent().
The documentation for this class was generated from the following files:
RemoteMobility.h
RemoteMobility.cc