My Project: CommPerformance
CommPerformance
#include <CommPerformance.h>
Public Member Functions
CommPerformance ()
virtual ~CommPerformance ()
std::string info ()
std::string infoTrace (bool header)
double getMeasurementPeriod ()
void setMeasurementPeriod (double measurementPeriod)
Private Attributes
double measurementPeriod
Detailed Description
Definition at line 21 of file CommPerformance.h.
Constructor & Destructor Documentation
CommPerformance()
CommPerformance::CommPerformance ()
Definition at line 20 of file CommPerformance.cc.
{
     // TODO Auto-generated constructor stub
 }
~CommPerformance()
CommPerformance::~CommPerformance () virtual
Definition at line 33 of file CommPerformance.cc.
{
     // TODO Auto-generated destructor stub
 }
Member Function Documentation
getMeasurementPeriod()
double CommPerformance::getMeasurementPeriod ()
Definition at line 25 of file CommPerformance.cc.
{
     return measurementPeriod;
 }
info()
std::string CommPerformance::info ()
Definition at line 37 of file CommPerformance.cc.
{
     std::ostringstream ost;
     ost << "  Measurement Period: " << this->getMeasurementPeriod();
     return ost.str();
 }
Referenced by veins::CommInfo::info(), LocalAgentCommPerformance::info(), and RemoteAgentCommPerformance::info().
infoTrace()
std::string CommPerformance::infoTrace (bool header = false)
Definition at line 43 of file CommPerformance.cc.
{
     std::ostringstream ost;
     if (header)
         ost << ";Measurement Period";
     else
         ost <<";" << this->measurementPeriod;
     return ost.str();
 }
Referenced by RemoteAgentCommPerformance::infoTrace().
setMeasurementPeriod()
void CommPerformance::setMeasurementPeriod (double measurementPeriod)
Definition at line 29 of file CommPerformance.cc.
{
     this->measurementPeriod = measurementPeriod;
 }
Member Data Documentation
measurementPeriod
double CommPerformance::measurementPeriod private
Definition at line 23 of file CommPerformance.h.
The documentation for this class was generated from the following files:
CommPerformance.h
CommPerformance.cc