My Project: veins::AgentPair
veins::AgentPair
#include <AgentPair.h>
Public Member Functions
AgentPair ()
virtual ~AgentPair ()
AgentPair (Agent *agentS, Agent *agentD, simtime_t msgReceivingTime, simtime_t msgSendingTime, RadiusEstimatorAgentPair *pRadiusEstimator, int neighbor, int event, simtime_t timeoutrouteValidity, double pPeriodApp, double powerReceived_dbm, double snr)
void updateAgentPair (simtime_t msgReceivingTime, simtime_t msgSendingTime, int neighbor, int event, simtime_t timeoutdataValidity, double powerReceived_dbm, double snr)
void updateAgentPair ()
AgentPair * updatePairFromMsg (long numMsg, Agent *agentS, Agent *agentD, simtime_t msgReceivingTime, simtime_t msgSendingTime, RadiusEstimatorAgentPair *pRadiusEstimator, int neighbor, int event, simtime_t dataValidity, double pPeriodApp, double powerReceived_dbm, double snr)
void updateRoute (ICMessage *m)
void updateCommnunicationState ()
void updateNeighborhoodCondition ()
Route * getRoute (ICMessage *m)
bool isInAgentPair (int id)
void addReceivedMsg ()
long getReceivedMessageAmount ()
void setCalcRadius ()
Agent * getAgentD ()
void setAgentD (Agent *agentD)
Agent * getAgentS ()
void setAgentS (Agent *agentS)
double getCalcRadius ()
double getMessageDelay ()
AgentPairMobility * getAgentPairMobility ()
void setAgentPairMobility (AgentPairMobility *agentPairMobility)
int getCommnunicationState ()
void setCommnunicationState (int commnunicationState)
simtime_t getCurrentTMsgReceiving ()
void setCurrentTMsgReceiving (simtime_t correntTMsgReceiving)
simtime_t getLastTMsgReceiving ()
void setLastTMsgReceiving (simtime_t lastTMsgReceiving)
double getMessageTTime ()
void setMessageTTime (double messageTTime)
bool isNeighbors ()
void setNeighbors (int neighbors)
std::string info ()
int getNeighbors ()
Agent * getAgentDs ()
void setAgentDs (Agent *agentDs)
QoCAgentPair * getQoCAgentPair ()
void setQoCAgentPair (QoCAgentPair *qoCAgentPair)
std::string infoTrace (bool header)
std::string infoTraceRoutes (bool header)
double getPeriodApplication ()
void setPeriodApplication (double periodApplication)
double getTxReceivedDBm ()
void setTxReceivedDBm (double txReceivedDBm)
cMessage * getAgentPairMessage ()
void setAgentPairMessage (cMessage *channelMessage)
double getOutOfRadiusRangeState ()
void setOutOfRadiusRangeState ()
simtime_t getLastTMsgSending ()
void setLastTMsgSending (simtime_t lastTMsgSending)
void setUpdatingTime (simtime_t timeupdate)
simtime_t getUpdatingTime ()
long getLastMsgNumber ()
void setLastMsgNumber (long lastMsgNumber)
long getTransmittedMsgAmount ()
void setTransmittedMsgAmount (long msgNumber)
long getCurrentMsgNumber ()
void setCurrentMsgNumber (long currentMsgNumber)
double getSnr ()
void setSnr (double snr)
Public Attributes
char lastEvent
double drlRadius
std::vector< ICarRoute * > pairRoutes
AgentPairMobility * agentPairMobility
Private Attributes
Agent * agent_s
Agent * agent_d
Agent * agent_ds
RadiusEstimatorAgentPair * radiusEstimator
double outOfRadiusRange
double calcRadius
double txReceived_dBm
double snr
Stores the signal to noise ratio of the transmission.
int neighbors
int commnunicationState
QoCAgentPair * qoCAgentPair
double messageTTime
double oPeriodApplication
simtime_t penultTMsgSending
simtime_t lastTMsgSending
simtime_t lastTMsgReceiving
simtime_t currentTMsgReceiving
long transmittedMsgAmount
simtime_t updatingTime
cMessage * agentPairMessage
long receivedMessageAmount
long lastMSGNumber
long currentMSGNumber
Detailed Description
Definition at line 53 of file AgentPair.h.
Constructor & Destructor Documentation
AgentPair() [1/2]
veins::AgentPair::AgentPair ()
Definition at line 22 of file AgentPair.cc.
                     {
     // TODO Auto-generated constructor stub
 }
~AgentPair()
veins::AgentPair::~AgentPair () virtual
Definition at line 27 of file AgentPair.cc.
                       {
     // TODO Auto-generated destructor stub
     delete (this);
 }
AgentPair() [2/2]
veins::AgentPair::AgentPair (Agent * agentS, Agent * agentD, simtime_t msgReceivingTime, simtime_t msgSendingTime, RadiusEstimatorAgentPair * pRadiusEstimator, int neighbor, int event, simtime_t timeoutrouteValidity, double pPeriodApp, double powerReceived_dbm, double snr)
Definition at line 34 of file AgentPair.cc.
 {
  this->setUpdatingTime(simTime());
  this->setAgentS(agentS);
  this->setAgentD(agentD);
  this->currentMSGNumber = 0;
  this->lastMSGNumber=0;
  this->receivedMessageAmount = 0;
  this->oPeriodApplication = pPeriodApp;
  this->penultTMsgSending = 0;
  this->lastTMsgSending = msgSendingTime;
  this->setNeighbors(neighbor);
  this->setLastTMsgReceiving(msgReceivingTime);
  this->setCurrentTMsgReceiving(msgReceivingTime);
  this->setMessageTTime((msgReceivingTime - msgSendingTime).dbl());
  this->setTxReceivedDBm(powerReceived_dbm);
  this->setSnr(snr);
  this->radiusEstimator = pRadiusEstimator;
  //AgentPair* myAgentPair = static_cast<AgentPair*>(this);
  this->agentPairMobility = new AgentPairMobility(this);
  //this->agentPairMobility = new AgentPairMobility();
  this->addReceivedMsg();
  if (agentS->getSetRadius()<=0) // consider fixe radius
  {
      //std::cout << endl << "begin  setCalcRadius AgentPair updateAgentPairsFromMsg "<< endl;
      if (powerReceived_dbm<0 && powerReceived_dbm>-200){
          this->setCalcRadius();
      }
  } else this->calcRadius = agentS->getSetRadius();
  this->setCommnunicationState(0);
  updateCommnunicationState();
  this->qoCAgentPair = new QoCAgentPair(this,dataValidity);
 // std::cout << endl << "end  setCalcRadius AgentPair updateAgentPairsFromMsg "<< endl;
  //this->qoCAgentPair = new QoCAgentPair();
  //std::cout << endl << "testando "<< endl;
 }
References addReceivedMsg(), agentPairMobility, calcRadius, currentMSGNumber, veins::Agent::getSetRadius(), lastMSGNumber, lastTMsgSending, oPeriodApplication, penultTMsgSending, qoCAgentPair, radiusEstimator, receivedMessageAmount, setAgentD(), setAgentS(), setCalcRadius(), setCommnunicationState(), setCurrentTMsgReceiving(), setLastTMsgReceiving(), setMessageTTime(), setNeighbors(), setSnr(), setTxReceivedDBm(), setUpdatingTime(), and updateCommnunicationState().
Member Function Documentation
addReceivedMsg()
void veins::AgentPair::addReceivedMsg ()
Definition at line 79 of file AgentPair.cc.
 {
     this->receivedMessageAmount++;
 }
References receivedMessageAmount.
Referenced by AgentPair(), updateAgentPair(), and veins::AgentPairList::updatePairListFromMsg().
getAgentD()
Agent * veins::AgentPair::getAgentD ()
Parameters
Definition at line 181 of file AgentPair.cc.
{
     return agent_d;
 }
References agent_d.
Referenced by veins::TimelinessAgentPair::calcAge(), veins::AgentPairMobility::calcDistance(), veins::AgentPairList::calcMaxDistancelr(), veins::AgentPairList::calcMaxSlr(), veins::AgentPairList::calcMinDistancelr(), veins::AgentPairList::calcMinSlr(), veins::AgentPairMobility::calcRelativeSpeed(), veins::TimelinessAgentPair::calcValidityTeste(), veins::AgentPairList::getAgentPair(), veins::AgentPairList::getAgentPairIndex(), veins::IcarRouting::getFowardNode(), veins::Icarqoc::handleSelfMsg(), isInAgentPair(), veins::AgentPairList::listAgentPairsWith(), veins::AgentPairList::listNeighbors(), veins::Routing::rule2(), veins::Routing::rule3(), veins::Routing::rule4(), setCalcRadius(), veins::IcarContext::textDataAgentPair(), and veins::IcarContext::updateAgentPairs().
getAgentDs()
Agent * veins::AgentPair::getAgentDs ()
Definition at line 405 of file AgentPair.cc.
{
     return agent_ds;
 }
References agent_ds.
getAgentPairMessage()
cMessage * veins::AgentPair::getAgentPairMessage ()
Definition at line 422 of file AgentPair.cc.
{
     return agentPairMessage;
 }
References agentPairMessage.
getAgentPairMobility()
AgentPairMobility * veins::AgentPair::getAgentPairMobility ()
Parameters
Definition at line 229 of file AgentPair.cc.
{
     return agentPairMobility;
 }
References agentPairMobility.
Referenced by veins::AgentPairList::calcMaxDistancelr(), veins::AgentPairList::calcMinDistancelr(), veins::TimelinessAgentPair::calcValidityTeste(), setCalcRadius(), veins::IcarContext::textDataAgentPair(), and updateAgentPair().
getAgentS()
Agent * veins::AgentPair::getAgentS ()
Parameters
Definition at line 189 of file AgentPair.cc.
{
     return agent_s;
 }
References agent_s.
Referenced by veins::TimelinessAgentPair::calcAge(), veins::AgentPairMobility::calcDistance(), veins::TimelinessAgentPair::calcLeicosseno(), veins::AgentPairList::calcMaxDistancelr(), veins::AgentPairList::calcMaxSlr(), veins::AgentPairList::calcMinDistancelr(), veins::AgentPairList::calcMinSlr(), veins::AgentPairMobility::calcRelativeSpeed(), veins::TimelinessAgentPair::calcValidityTeste(), veins::AgentPairList::getAgentPair(), veins::AgentPairList::getAgentPairIndex(), veins::IcarRouting::getFowardNode(), veins::Icarqoc::handleSelfMsg(), isInAgentPair(), veins::AgentPairList::listAgentPairsWith(), veins::AgentPairList::listNeighbors(), veins::Routing::rule2(), veins::Routing::rule3(), veins::Routing::rule4(), setCalcRadius(), veins::IcarContext::textDataAgentPair(), updateAgentPair(), veins::IcarContext::updateAgentPairs(), veins::Routing::verifyConditionForwardAgent(), and veins::Routing::verifyConditionForwardNotNeighbor().
getCalcRadius()
double veins::AgentPair::getCalcRadius ()
Parameters
Definition at line 197 of file AgentPair.cc.
{
     return calcRadius;
 }
References calcRadius.
Referenced by veins::TimelinessAgentPair::calcValidityTeste(), and veins::IcarContext::textDataAgentPair().
getCommnunicationState()
int veins::AgentPair::getCommnunicationState ()
Parameters
Definition at line 238 of file AgentPair.cc.
{
     return commnunicationState;
 }
References commnunicationState.
Referenced by veins::AgentPairList::calcMaxDistancelr(), veins::AgentPairList::calcMaxSlr(), veins::AgentPairList::calcMinDistancelr(), veins::AgentPairList::calcMinSlr(), veins::TimelinessAgentPair::calcValidityTeste(), veins::Routing::rule2(), veins::Routing::rule3(), veins::Routing::rule4(), veins::IcarContext::updateAgentPairs(), veins::Routing::verifyAgentPairc(), veins::IcarRouting::verifyAgentPairContext(), veins::Routing::verifyConditionForwardAgent(), and veins::Routing::verifyConditionForwardNotNeighbor().
getCurrentMsgNumber()
long veins::AgentPair::getCurrentMsgNumber ()
Definition at line 452 of file AgentPair.cc.
{
     return currentMSGNumber;
 }
References currentMSGNumber.
Referenced by infoTrace().
getCurrentTMsgReceiving()
simtime_t veins::AgentPair::getCurrentTMsgReceiving ()
Parameters
Definition at line 247 of file AgentPair.cc.
{
     return currentTMsgReceiving;
 }
References currentTMsgReceiving.
Referenced by updateAgentPair().
getLastMsgNumber()
long veins::AgentPair::getLastMsgNumber ()
Definition at line 205 of file AgentPair.cc.
{
     return lastMSGNumber;
 }
References lastMSGNumber.
Referenced by infoTrace().
getLastTMsgReceiving()
simtime_t veins::AgentPair::getLastTMsgReceiving ()
Definition at line 255 of file AgentPair.cc.
{
     return lastTMsgReceiving;
 }
References lastTMsgReceiving.
getLastTMsgSending()
simtime_t veins::AgentPair::getLastTMsgSending ()
Definition at line 440 of file AgentPair.cc.
{
     return lastTMsgSending;
 }
References lastTMsgSending.
Referenced by veins::TimelinessAgentPair::calcAge().
getMessageDelay()
double veins::AgentPair::getMessageDelay ()
Definition at line 285 of file AgentPair.cc.
 {
    return (currentTMsgReceiving - lastTMsgSending).dbl();
 }
References currentTMsgReceiving, and lastTMsgSending.
getMessageTTime()
double veins::AgentPair::getMessageTTime ()
Parameters
Definition at line 264 of file AgentPair.cc.
{
     return messageTTime;
 }
References messageTTime.
Referenced by veins::TimelinessAgentPair::calcTimeoutValidity(), veins::Routing::rule2(), veins::Routing::rule3(), veins::Routing::rule4(), and veins::IcarRouting::verifyAgentPairContext().
getNeighbors()
int veins::AgentPair::getNeighbors ()
Definition at line 281 of file AgentPair.cc.
{
     return neighbors;
 }
References neighbors.
getOutOfRadiusRangeState()
double veins::AgentPair::getOutOfRadiusRangeState ()
Definition at line 426 of file AgentPair.cc.
{
     return outOfRadiusRange;
 }
References outOfRadiusRange.
getPeriodApplication()
double veins::AgentPair::getPeriodApplication ()
Definition at line 305 of file AgentPair.cc.
{
     return oPeriodApplication;
 }
References oPeriodApplication.
getQoCAgentPair()
QoCAgentPair * veins::AgentPair::getQoCAgentPair ()
Definition at line 413 of file AgentPair.cc.
{
     return qoCAgentPair;
 }
References qoCAgentPair.
Referenced by veins::AgentPairList::calcMaxSlr(), veins::AgentPairList::calcMinSlr(), veins::Routing::getRoute(), veins::ForwardingNode::update(), and updateAgentPair().
getReceivedMessageAmount()
long veins::AgentPair::getReceivedMessageAmount ()
Definition at line 84 of file AgentPair.cc.
{
     return this->receivedMessageAmount;
 }
References receivedMessageAmount.
getRoute()
Route* veins::AgentPair::getRoute (ICMessage * m)
getSnr()
double veins::AgentPair::getSnr ()
Definition at line 469 of file AgentPair.cc.
{
     return snr;
 }
References snr.
getTransmittedMsgAmount()
long veins::AgentPair::getTransmittedMsgAmount ()
Definition at line 448 of file AgentPair.cc.
{
     return this->transmittedMsgAmount;
 }
References transmittedMsgAmount.
getTxReceivedDBm()
double veins::AgentPair::getTxReceivedDBm ()
Definition at line 309 of file AgentPair.cc.
{
     return txReceived_dBm;
 }
References txReceived_dBm.
Referenced by veins::TimelinessAgentPair::calcValidityTeste().
getUpdatingTime()
simtime_t veins::AgentPair::getUpdatingTime ()
Definition at line 213 of file AgentPair.cc.
{
     return this->updatingTime;
 }
References updatingTime.
Referenced by veins::TimelinessAgentPair::calcValidityTeste().
info()
std::string veins::AgentPair::info ()
Definition at line 290 of file AgentPair.cc.
{
     std::ostringstream ost;
     ost << "  agente destino: " << this->agent_d->info()
         << "  agente origem : " << this->agent_s->info()
         << "  dados da mobie: " << this->agentPairMobility->info()
         << "  estado canal  : " << this->commnunicationState
         << "  ultimo ST Rec. MSG: " << this->currentTMsgReceiving
         << "  penultimo ST Rec.MSG:  " << this->lastTMsgReceiving
         << "  tempo viagem MSG  : " << this->messageTTime
         << "  vizinho : " << this->neighbors
         << "  QOC :: " <<  ((TimelinessAgentPair *) this->qoCAgentPair->getTimeliness())->info();
     return ost.str();
 }
References agent_d, agent_s, agentPairMobility, commnunicationState, currentTMsgReceiving, veins::QoCInfo::getTimeliness(), veins::Agent::info(), veins::AgentPairMobility::info(), lastTMsgReceiving, messageTTime, neighbors, and qoCAgentPair.
infoTrace()
std::string veins::AgentPair::infoTrace (bool header)
<< this->infoTraceRoutes(false); rotemamento depois
Definition at line 321 of file AgentPair.cc.
{
     std::ostringstream ost;
      if (header){
        ost
                << ";agOID"
                << ";agDID"
                <<";neighbor"
                  ";pairState"
                  ";delayMSG"
                ";currentReceviedMSGNumber"
                ";LastReceviedMSGNumber"
                //";lostMessage"
                <<";CurrTSMsgSending"
                << ";receivedMessageAmount"
                << ";currSTRecMSG"
                << ";lastSTRecMSG"
                << ";travelTimeMSG"
                << ";receivedPowerDbm"
                << ";snr"
                << ";radiusCalc;drlRadius"
                << ";outOfRadiusRange";
                Agent * temp = new Agent();
                AgentPairMobility* temp1 = new AgentPairMobility();
                TimelinessAgentPair * temp2 = new TimelinessAgentPair();
                ost << temp1->infoTrace(true) << temp2->infoTrace(true) <<  temp->infoTrace(true, "S") << temp->infoTrace(true, "D");
                //<< this->infoTraceRoutes(true);
    } else {
        ost
            << ";" << this->agent_s->getId()
            << ";" << this->agent_d->getId()
            << ";" << this->neighbors
            << ";" << this->commnunicationState
             //<< ";" << this->getMessageDelay()
            << ";" << this->messageTTime
            << ";" << this->getCurrentMsgNumber()
            << ";" << this->getLastMsgNumber()
            //<< ";" << this->getCurrentMsgNumber() - (this->getLastMsgNumber()-1)
            << ";" << this->lastTMsgSending
            << ";" << this->receivedMessageAmount
            << ";" << this->currentTMsgReceiving
            << ";" << this->lastTMsgReceiving
            << ";" << this->messageTTime
            << ";" << this->txReceived_dBm
            << ";" << this->snr
            << ";" << this->calcRadius
            << ";" << this->drlRadius
            << ";" << this->outOfRadiusRange
            <<  this->agentPairMobility->infoTrace(false)
            <<  ((TimelinessAgentPair *) this->qoCAgentPair->getTimeliness())->infoTrace(false)
            << this->agent_s->infoTrace(false,"")
            << this->agent_d->infoTrace(false, "");
            ///<< this->infoTraceRoutes(false); rotemamento depois
    }
     return ost.str();
 }
References agent_d, agent_s, agentPairMobility, calcRadius, commnunicationState, currentTMsgReceiving, drlRadius, getCurrentMsgNumber(), veins::Agent::getId(), getLastMsgNumber(), veins::QoCInfo::getTimeliness(), veins::AgentPairMobility::infoTrace(), veins::TimelinessAgentPair::infoTrace(), veins::Agent::infoTrace(), lastTMsgReceiving, lastTMsgSending, messageTTime, neighbors, outOfRadiusRange, qoCAgentPair, receivedMessageAmount, snr, and txReceived_dBm.
Referenced by veins::AgentPairList::infoTraceAgentPairList(), veins::Icarqoc::initialize(), and veins::IcarContext::textDataAgentPair().
infoTraceRoutes()
std::string veins::AgentPair::infoTraceRoutes (bool header)
VER COMO FICA A O VALOR MAXIMO DE SALTOS RELACIONANDO COM O PAR DE AGENTES
Definition at line 382 of file AgentPair.cc.
{
     ICarRoute *c=NULL;
     std::ostringstream ost;
     unsigned int index = 0;
     unsigned int sizeofRoute;
     /// VER COMO FICA  A O VALOR MAXIMO DE SALTOS RELACIONANDO COM O PAR DE AGENTES
     if (header) sizeofRoute = 32;
     else sizeofRoute = pairRoutes.size();
     while (sizeofRoute > index)
     {
        if (!header)
         c = dynamic_cast<ICarRoute*>(pairRoutes[index]);
         ost << c->infoTrace(header);
         ++index;
     }
      return ost.str();
 }
References veins::ICarRoute::infoTrace(), and pairRoutes.
isInAgentPair()
bool veins::AgentPair::isInAgentPair (int id)
Definition at line 172 of file AgentPair.cc.
 {
     if (id == this->getAgentS()->getId() || id == this->getAgentD()->getId())
         return true;
     else
         return false;
 }
References getAgentD(), and getAgentS().
isNeighbors()
bool veins::AgentPair::isNeighbors ()
Parameters
Definition at line 272 of file AgentPair.cc.
{
     if (neighbors==1) return true;
     else return false;
 }
References neighbors.
Referenced by veins::AgentPairList::calcMinSlr(), veins::TimelinessAgentPair::calcValidityTeste(), veins::Routing::getRoute(), veins::AgentPairList::listNeighbors(), veins::Routing::rule3(), veins::Routing::rule4(), veins::TimelinessAgentPair::update(), veins::Routing::verifyAgentPairc(), and veins::Routing::verifyConditionForwardAgent().
setAgentD()
void veins::AgentPair::setAgentD (Agent * agentD)
Parameters
Definition at line 185 of file AgentPair.cc.
{
     agent_d = agentD;
 }
References agent_d.
Referenced by AgentPair().
setAgentDs()
void veins::AgentPair::setAgentDs (Agent * agentDs)
Definition at line 409 of file AgentPair.cc.
{
     agent_ds = agentDs;
 }
References agent_ds.
setAgentPairMessage()
void veins::AgentPair::setAgentPairMessage (cMessage * channelMessage)
Definition at line 436 of file AgentPair.cc.
{
     this->agentPairMessage = agentPairMessage;
 }
References agentPairMessage.
setAgentPairMobility()
void veins::AgentPair::setAgentPairMobility (AgentPairMobility * agentPairMobility)
Parameters
Definition at line 233 of file AgentPair.cc.
{
     this->agentPairMobility = agentPairMobility;
 }
References agentPairMobility.
setAgentS()
void veins::AgentPair::setAgentS (Agent * agentS)
Parameters
Definition at line 193 of file AgentPair.cc.
{
     agent_s = agentS;
 }
References agent_s.
Referenced by AgentPair().
setCalcRadius()
void veins::AgentPair::setCalcRadius ()
Definition at line 216 of file AgentPair.cc.
{
     //this->calcRadius = this->radiusEstimator->getSignalRange(this->txReceived_dBm,
     //        this->channelMobility->getDistancelr(this->agent_s->getMobilityInfo()->getActualMove(),
    //         this->agent_d->getMobilityInfo()->getActualMove()));
     Coord r = this->getAgentS()->getMobilityInfo()->getPositionAtTime(simTime());
     Coord l = this->getAgentD()->getMobilityInfo()->getPositionAtTime(simTime());
     drlRadius = this->getAgentPairMobility()->calcEuclideanDistancelr(this->getAgentD()->getMobilityInfo()->getActualMove()->getStartPos(), r);
     //double drlNext = this->getAgentPairMobility()->calcEuclideanDistancelr(l, r);
     //this->calcRadius = this->radiusEstimator->getSignalRange(this->txReceived_dBm,
     //        this->agentPairMobility->getDistancelr());
     this->calcRadius = this->radiusEstimator->getSignalRange(this->txReceived_dBm, drlRadius);
 }
References veins::AgentPairMobility::calcEuclideanDistancelr(), calcRadius, drlRadius, getAgentD(), getAgentPairMobility(), getAgentS(), veins::Agent::getMobilityInfo(), veins::MobilityInfo::getPositionAtTime(), RadiusEstimatorAgentPair::getSignalRange(), radiusEstimator, and txReceived_dBm.
Referenced by AgentPair(), and updateAgentPair().
setCommnunicationState()
void veins::AgentPair::setCommnunicationState (int commnunicationState)
Parameters
Definition at line 243 of file AgentPair.cc.
{
     this->commnunicationState = pcommnunicationState;
 }
References commnunicationState.
Referenced by AgentPair(), and updateCommnunicationState().
setCurrentMsgNumber()
void veins::AgentPair::setCurrentMsgNumber (long currentMsgNumber)
Definition at line 456 of file AgentPair.cc.
{
     if (currentMsgNumber > this->currentMSGNumber)
     {
         this->lastMSGNumber = this->currentMSGNumber;
         this->currentMSGNumber = currentMsgNumber;
     }
 }
References currentMSGNumber, and lastMSGNumber.
Referenced by veins::AgentPairList::updatePairListFromMsg().
setCurrentTMsgReceiving()
void veins::AgentPair::setCurrentTMsgReceiving (simtime_t correntTMsgReceiving)
Parameters
Definition at line 251 of file AgentPair.cc.
{
     this->currentTMsgReceiving = correntTMsgReceiving;
 }
References currentTMsgReceiving.
Referenced by AgentPair(), and updateAgentPair().
setLastMsgNumber()
void veins::AgentPair::setLastMsgNumber (long lastMsgNumber)
Definition at line 209 of file AgentPair.cc.
{
     lastMSGNumber = lastMsgNumber;
 }
References lastMSGNumber.
setLastTMsgReceiving()
void veins::AgentPair::setLastTMsgReceiving (simtime_t lastTMsgReceiving)
Parameters
Definition at line 259 of file AgentPair.cc.
{
     this->lastTMsgReceiving = lastTMsgReceiving;
 }
References lastTMsgReceiving.
Referenced by AgentPair(), and updateAgentPair().
setLastTMsgSending()
void veins::AgentPair::setLastTMsgSending (simtime_t lastTMsgSending)
Definition at line 444 of file AgentPair.cc.
{
     this->lastTMsgSending = lastTMsgSending;
 }
References lastTMsgSending.
setMessageTTime()
void veins::AgentPair::setMessageTTime (double messageTTime)
Parameters
Definition at line 268 of file AgentPair.cc.
{
     this->messageTTime = messageTTime;
 }
References messageTTime.
Referenced by AgentPair(), and updateAgentPair().
setNeighbors()
void veins::AgentPair::setNeighbors (int neighbors)
Parameters
Definition at line 277 of file AgentPair.cc.
{
     this->neighbors = neighbors;
 }
References neighbors.
Referenced by AgentPair().
setOutOfRadiusRangeState()
void veins::AgentPair::setOutOfRadiusRangeState ()
Definition at line 430 of file AgentPair.cc.
{
     //this->outOfRadiusRange = this->channelMobility->getDistancelr(this->agent_s->getMobilityInfo()->getActualMove(),
     //        this->agent_d->getMobilityInfo()->getActualMove()) - this->calcRadius;
     this->outOfRadiusRange = this->agentPairMobility->getDistancelr() - this->calcRadius;
 }
References agentPairMobility, calcRadius, veins::AgentPairMobility::getDistancelr(), and outOfRadiusRange.
Referenced by updateAgentPair().
setPeriodApplication()
void veins::AgentPair::setPeriodApplication (double periodApplication)
Definition at line 317 of file AgentPair.cc.
{
     oPeriodApplication = periodApplication;
 }
References oPeriodApplication.
setQoCAgentPair()
void veins::AgentPair::setQoCAgentPair (QoCAgentPair * qoCAgentPair)
Definition at line 418 of file AgentPair.cc.
{
     this->qoCAgentPair = qoCAgentPair;
 }
References qoCAgentPair.
setSnr()
void veins::AgentPair::setSnr (double snr)
Definition at line 473 of file AgentPair.cc.
{
     this->snr = snr;
 }
References snr.
Referenced by AgentPair(), and updateAgentPair().
setTransmittedMsgAmount()
void veins::AgentPair::setTransmittedMsgAmount (long msgNumber)
Definition at line 464 of file AgentPair.cc.
{
     if (msgNumber > this->transmittedMsgAmount)
         this->transmittedMsgAmount = msgNumber;
 }
References transmittedMsgAmount.
setTxReceivedDBm()
void veins::AgentPair::setTxReceivedDBm (double txReceivedDBm)
Definition at line 313 of file AgentPair.cc.
{
     txReceived_dBm = txReceivedDBm;
 }
References txReceived_dBm.
Referenced by AgentPair(), and updateAgentPair().
setUpdatingTime()
void veins::AgentPair::setUpdatingTime (simtime_t timeupdate)
Definition at line 201 of file AgentPair.cc.
{
     this->updatingTime=timeupdate;
 }
References updatingTime.
Referenced by AgentPair(), and updateAgentPair().
updateAgentPair() [1/2]
void veins::AgentPair::updateAgentPair ()
Definition at line 137 of file AgentPair.cc.
 {
     // updating communication context of AgentPair
     this->setUpdatingTime(simTime());
      //update distance between S and D
      getAgentPairMobility()->updateAgentPairMobility();
      this->setOutOfRadiusRangeState();
      // updating QoC of AgentPair
      this->getQoCAgentPair()->getTimelinessAgentPair()->update(-1);
 }
References getAgentPairMobility(), getQoCAgentPair(), veins::QoCAgentPair::getTimelinessAgentPair(), setOutOfRadiusRangeState(), setUpdatingTime(), veins::TimelinessAgentPair::update(), and veins::AgentPairMobility::updateAgentPairMobility().
updateAgentPair() [2/2]
void veins::AgentPair::updateAgentPair (simtime_t msgReceivingTime, simtime_t msgSendingTime, int neighbor, int event, simtime_t timeoutdataValidity, double powerReceived_dbm, double snr)
Definition at line 91 of file AgentPair.cc.
 {
  if (lastTMsgSending <= msgSendingTime)
  {
      // updating communication context of AgentPair
      this->setUpdatingTime(simTime());
      this->penultTMsgSending = this->lastTMsgSending;
      this->lastTMsgSending = msgSendingTime;
      this->setLastTMsgReceiving(getCurrentTMsgReceiving());
      this->setCurrentTMsgReceiving(msgReceivingTime);
      this->setMessageTTime((msgReceivingTime - msgSendingTime).dbl());
      this->setTxReceivedDBm(powerReceived_dbm);
      this->setSnr(snr);
      this->addReceivedMsg();
       // updating mobility context of AgentPair
       this->agentPairMobility->updateAgentPairMobility();
       if (this->getAgentS()->getSetRadius()<=0)
        {
              if (powerReceived_dbm<0 && powerReceived_dbm>-200)
              {
                  this->setCalcRadius();
              }else {
                  this->calcRadius = 0;
              }
        } else this->calcRadius = this->getAgentS()->getSetRadius();
      this->setOutOfRadiusRangeState();
      // updating neighbor condition
      this->updateNeighborhoodCondition();
      // updating AgentPair communication state
      updateCommnunicationState();
      // updating QoC of AgentPair
      this->getQoCAgentPair()->getTimelinessAgentPair()->update(dataValidity);
   }
 }
References addReceivedMsg(), agentPairMobility, calcRadius, getAgentS(), getCurrentTMsgReceiving(), getQoCAgentPair(), veins::Agent::getSetRadius(), veins::QoCAgentPair::getTimelinessAgentPair(), lastTMsgSending, penultTMsgSending, setCalcRadius(), setCurrentTMsgReceiving(), setLastTMsgReceiving(), setMessageTTime(), setOutOfRadiusRangeState(), setSnr(), setTxReceivedDBm(), setUpdatingTime(), veins::TimelinessAgentPair::update(), veins::AgentPairMobility::updateAgentPairMobility(), updateCommnunicationState(), and updateNeighborhoodCondition().
Referenced by veins::IcarContext::updateAgentPairs(), and veins::AgentPairList::updatePairListFromMsg().
updateCommnunicationState()
void veins::AgentPair::updateCommnunicationState ()
Definition at line 160 of file AgentPair.cc.
{
     if (this->neighbors==false) //&& there is no communication route
         this->setCommnunicationState(CommState::noCommunicating);
     else
         this->setCommnunicationState(CommState::communicating);
     /*int cstate = CommState::updateCommnunicationState(event, this->getCommnunicationState());
     if (cstate >= 0) this->setCommnunicationState(cstate);
     else this->setCommnunicationState(-1);
     */
 }
References CommState::communicating, neighbors, CommState::noCommunicating, and setCommnunicationState().
Referenced by AgentPair(), and updateAgentPair().
updateNeighborhoodCondition()
void veins::AgentPair::updateNeighborhoodCondition ()
Definition at line 152 of file AgentPair.cc.
{
     if (this->agentPairMobility->getDistancelr() > this->getCalcRadius())
             this->neighbors = false;
     else this->neighbors = true;
 }
References agentPairMobility, veins::AgentPairMobility::getDistancelr(), and neighbors.
Referenced by updateAgentPair().
updatePairFromMsg()
AgentPair* veins::AgentPair::updatePairFromMsg (long numMsg, Agent * agentS, Agent * agentD, simtime_t msgReceivingTime, simtime_t msgSendingTime, RadiusEstimatorAgentPair * pRadiusEstimator, int neighbor, int event, simtime_t dataValidity, double pPeriodApp, double powerReceived_dbm, double snr)
updateRoute()
void veins::AgentPair::updateRoute (ICMessage * m)
Member Data Documentation
agent_d
Agent* veins::AgentPair::agent_d private
Definition at line 63 of file AgentPair.h.
Referenced by getAgentD(), info(), infoTrace(), and setAgentD().
agent_ds
Agent* veins::AgentPair::agent_ds private
Definition at line 68 of file AgentPair.h.
Referenced by getAgentDs(), and setAgentDs().
agent_s
Agent* veins::AgentPair::agent_s private
Definition at line 58 of file AgentPair.h.
Referenced by getAgentS(), info(), infoTrace(), and setAgentS().
agentPairMessage
cMessage* veins::AgentPair::agentPairMessage private
Definition at line 133 of file AgentPair.h.
Referenced by getAgentPairMessage(), and setAgentPairMessage().
agentPairMobility
AgentPairMobility* veins::AgentPair::agentPairMobility
Definition at line 146 of file AgentPair.h.
Referenced by AgentPair(), getAgentPairMobility(), info(), infoTrace(), setAgentPairMobility(), setOutOfRadiusRangeState(), updateAgentPair(), and updateNeighborhoodCondition().
calcRadius
double veins::AgentPair::calcRadius private
Definition at line 84 of file AgentPair.h.
Referenced by AgentPair(), getCalcRadius(), infoTrace(), setCalcRadius(), setOutOfRadiusRangeState(), and updateAgentPair().
commnunicationState
int veins::AgentPair::commnunicationState private
Definition at line 99 of file AgentPair.h.
Referenced by getCommnunicationState(), info(), infoTrace(), and setCommnunicationState().
currentMSGNumber
long veins::AgentPair::currentMSGNumber private
Definition at line 138 of file AgentPair.h.
Referenced by AgentPair(), getCurrentMsgNumber(), and setCurrentMsgNumber().
currentTMsgReceiving
simtime_t veins::AgentPair::currentTMsgReceiving private
Definition at line 122 of file AgentPair.h.
Referenced by getCurrentTMsgReceiving(), getMessageDelay(), info(), infoTrace(), and setCurrentTMsgReceiving().
drlRadius
double veins::AgentPair::drlRadius
Definition at line 144 of file AgentPair.h.
Referenced by infoTrace(), and setCalcRadius().
lastEvent
char veins::AgentPair::lastEvent
Definition at line 143 of file AgentPair.h.
Referenced by veins::IcarContext::textDataAgentPair().
lastMSGNumber
long veins::AgentPair::lastMSGNumber private
Definition at line 137 of file AgentPair.h.
Referenced by AgentPair(), getLastMsgNumber(), setCurrentMsgNumber(), and setLastMsgNumber().
lastTMsgReceiving
simtime_t veins::AgentPair::lastTMsgReceiving private
Definition at line 118 of file AgentPair.h.
Referenced by getLastTMsgReceiving(), info(), infoTrace(), and setLastTMsgReceiving().
lastTMsgSending
simtime_t veins::AgentPair::lastTMsgSending private
Definition at line 114 of file AgentPair.h.
Referenced by AgentPair(), getLastTMsgSending(), getMessageDelay(), infoTrace(), setLastTMsgSending(), and updateAgentPair().
messageTTime
double veins::AgentPair::messageTTime private
Definition at line 106 of file AgentPair.h.
Referenced by getMessageTTime(), info(), infoTrace(), and setMessageTTime().
neighbors
int veins::AgentPair::neighbors private
Definition at line 97 of file AgentPair.h.
Referenced by getNeighbors(), info(), infoTrace(), isNeighbors(), setNeighbors(), updateCommnunicationState(), and updateNeighborhoodCondition().
oPeriodApplication
double veins::AgentPair::oPeriodApplication private
Definition at line 108 of file AgentPair.h.
Referenced by AgentPair(), getPeriodApplication(), and setPeriodApplication().
outOfRadiusRange
double veins::AgentPair::outOfRadiusRange private
Definition at line 78 of file AgentPair.h.
Referenced by getOutOfRadiusRangeState(), infoTrace(), and setOutOfRadiusRangeState().
pairRoutes
std::vector<ICarRoute *> veins::AgentPair::pairRoutes
Definition at line 145 of file AgentPair.h.
Referenced by infoTraceRoutes(), veins::Routing::searchRoute(), and veins::IcarRouting::verifyAgentPairRoute().
penultTMsgSending
simtime_t veins::AgentPair::penultTMsgSending private
Definition at line 110 of file AgentPair.h.
Referenced by AgentPair(), and updateAgentPair().
qoCAgentPair
QoCAgentPair* veins::AgentPair::qoCAgentPair private
Definition at line 101 of file AgentPair.h.
Referenced by AgentPair(), getQoCAgentPair(), info(), infoTrace(), and setQoCAgentPair().
radiusEstimator
RadiusEstimatorAgentPair* veins::AgentPair::radiusEstimator private
Definition at line 76 of file AgentPair.h.
Referenced by AgentPair(), and setCalcRadius().
receivedMessageAmount
long veins::AgentPair::receivedMessageAmount private
Definition at line 135 of file AgentPair.h.
Referenced by addReceivedMsg(), AgentPair(), getReceivedMessageAmount(), and infoTrace().
snr
double veins::AgentPair::snr private
Stores the signal to noise ratio of the transmission.
Definition at line 93 of file AgentPair.h.
Referenced by getSnr(), infoTrace(), and setSnr().
transmittedMsgAmount
long veins::AgentPair::transmittedMsgAmount private
Definition at line 127 of file AgentPair.h.
Referenced by getTransmittedMsgAmount(), and setTransmittedMsgAmount().
txReceived_dBm
double veins::AgentPair::txReceived_dBm private
Definition at line 88 of file AgentPair.h.
Referenced by getTxReceivedDBm(), infoTrace(), setCalcRadius(), and setTxReceivedDBm().
updatingTime
simtime_t veins::AgentPair::updatingTime private
Definition at line 131 of file AgentPair.h.
Referenced by getUpdatingTime(), and setUpdatingTime().
The documentation for this class was generated from the following files:
AgentPair.h
AgentPair.cc