My Project: veins::Move
veins::Move
Class to store object position and movement.
#include <Move.h>
Public Member Functions
Move ()
Move (const Move &mSrc)
double getSpeed () const
Returns the current speed.
void setSpeed (double speed)
Sets the current speed in meters per second.
const Coord & getStartPos () const
Returns the start position.
simtime_t_cref getStartTime () const
Returns start time, i.e.
void setStart (const Coord &startPos, simtime_t_cref startTime)
Sets start position (components in meters) and start time.
void setStart (const Coord &startPos)
Sets start position to passed value (components in meters), start time will be set to current simulation-time.
const Coord & getDirection () const
Returns the direction vector (which is unit less, because of normalization).
const Coord & getOrientation () const
Returns the orientation vector, i.e.
void setOrientationByVector (const Coord &orientation)
Sets the orientation to the passed vector.
void setDirectionByVector (const Coord &direction)
Sets the direction to the passed vector, which must be already normalized or the 0-vector.
void setDirectionByTarget (const Coord &target)
Sets the direction to the normalized vector pointing from the current start position to the passed target point.
virtual Coord getPositionAt (simtime_t_cref actualTime=simTime()) const
Returns the position of the Move (Host) at the specified point in time.
virtual const Coord & getStartPosition () const
std::string info () const override
Returns information about the current state.
Protected Attributes
Coord startPos
Start position of the host (in meters)
Coord lastPos
Last position which was set.
simtime_t startTime
start time at which host started at startPos
Coord orientation
orientation the host is pointing to
Coord direction
direction the host is moving to, must be normalized
double speed
speed of the host in meters per second
Detailed Description
Class to store object position and movement.
Author
Andreas Koepke, Michael Swigulski
Definition at line 44 of file Move.h.
Constructor & Destructor Documentation
Move() [1/2]
veins::Move::Move () inline
Definition at line 60 of file Move.h.
         : startPos()
         , lastPos(0.0, 0.0, DBL_MAX)
         , startTime()
         , orientation()
         , direction()
         , speed(0.0)
     {
     }
Move() [2/2]
veins::Move::Move (const Move & mSrc) inline
Definition at line 69 of file Move.h.
         : startPos(mSrc.startPos)
         , lastPos(mSrc.lastPos)
         , startTime(mSrc.startTime)
         , orientation(mSrc.orientation)
         , direction(mSrc.direction)
         , speed(mSrc.speed)
     {
     }
Member Function Documentation
getDirection()
const Coord& veins::Move::getDirection () const inline
Returns the direction vector (which is unit less, because of normalization).
Definition at line 133 of file Move.h.
     {
         return direction;
     }
Referenced by veins::BaseMobility::checkIfOutside(), veins::BaseMobility::getCurrentDirection(), veins::BaseMobility::getCurrentSpeed(), and veins::BaseMobility::goToBorder().
getOrientation()
const Coord& veins::Move::getOrientation () const inline
Returns the orientation vector, i.e.
the direction the host is pointing in. The difference to direction is that the x and y components are never both 0, which is important for the calculation of the antenna gain. At simulation start, it is initialized with a (user defined) value. If the host stops during simulation, the last direction is stored in the orientation field.
Definition at line 145 of file Move.h.
     {
         return orientation;
     }
Referenced by veins::BaseMobility::getCurrentOrientation().
getPositionAt()
virtual Coord veins::Move::getPositionAt (simtime_t_cref actualTime = simTime()) const inline virtual
Returns the position of the Move (Host) at the specified point in time.
It is intended to be passed simTime() as actualTime and returns the actual position.
Assumes that direction represents a normalized vector (length equals 1.0). Further this function does not check whether the given time point is before the startTime of the actual move pattern. So in this case one might obtain an unintended result.
Definition at line 195 of file Move.h.
     {
         // if speed is very close to 0.0, the host is practically standing still
         if (math::almost_equal(speed, 0.0)) return startPos;
         // otherwise: actualPos = startPos + ( direction * v * t )
         return startPos + (direction * speed * SIMTIME_DBL(actualTime - startTime));
     }
References veins::math::almost_equal().
Referenced by veins::BaseMobility::getPositionAt().
getSpeed()
double veins::Move::getSpeed () const inline
Returns the current speed.
Definition at line 82 of file Move.h.
     {
         return speed;
     }
Referenced by veins::MobilityInfo::calcAcceleration(), veins::TimelinessAgentPair::calcLeicosseno(), veins::AgentPairMobility::calcRelativeSpeed(), veins::BaseMobility::getCurrentSpeed(), veins::MobilityInfo::getPositionAtTime(), veins::BaseMobility::handleIfOutside(), veins::BaseMobility::handleSelfMsg(), veins::MobilityInfo::infoTrace(), veins::BaseMobility::initialize(), veins::LinearMobility::makeMove(), and veins::MessageManager::prepareICRNode().
getStartPos()
const Coord& veins::Move::getStartPos () const inline
Returns the start position.
Definition at line 98 of file Move.h.
     {
         return startPos;
     }
Referenced by veins::AgentPairMobility::calcDistance(), veins::MobilityInfo::calcEuclideanDistanceAgentMoving(), veins::KnownGlobal::calcTraciDistanceMobility(), veins::TraCIMobility::changePosition(), veins::BaseMobility::checkIfOutside(), veins::TraCIMobility::fixIfHostGetsOutside(), veins::AgentPairMobility::getDistancelr(), veins::MobilityInfo::getPositionAtTime(), veins::BaseMobility::goToBorder(), veins::BaseMobility::handleBorderMsg(), veins::BaseMobility::handleIfOutside(), veins::MobilityInfo::infoTrace(), veins::BaseMobility::initialize(), veins::LinearMobility::initialize(), veins::LinearMobility::makeMove(), veins::MessageManager::prepareICRNode(), veins::IcarContext::textDataAgentPair(), veins::LocalMobility::updateLocalMobilityPos(), and veins::BaseMobility::updatePosition().
getStartPosition()
virtual const Coord& veins::Move::getStartPosition () const inline virtual
Definition at line 203 of file Move.h.
     {
         if (lastPos.z != DBL_MAX) return lastPos;
         return startPos;
     }
References veins::Coord::z.
Referenced by veins::TraCIMobility::changePosition(), veins::TraCIMobility::initialize(), and veins::TraCIMobility::preInitialize().
getStartTime()
simtime_t_cref veins::Move::getStartTime () const inline
Returns start time, i.e.
time point of the start at start position.
Definition at line 106 of file Move.h.
     {
         return startTime;
     }
Referenced by veins::MobilityInfo::calcAcceleration(), veins::TimelinessAgentPair::calcAge(), veins::IcarContext::changeLocalMobility(), veins::MobilityInfo::getPositionAtTime(), veins::MobilityInfo::infoTrace(), veins::MessageManager::prepareICRNode(), veins::LocalMobility::updateLocalMobilityPos(), and veins::RemoteAgent::updateRemoteAgent().
info()
std::string veins::Move::info () const inline override
Returns information about the current state.
Definition at line 214 of file Move.h.
     {
         return info();
     }
     std::string info() const
 #endif
     {
         std::ostringstream ost;
         ost << " HostMove "
             << " startPos: " << startPos.info() << " direction: " << direction.info() << " orientation: " << orientation.info() << " startTime: " << startTime << " speed: " << speed;
         return ost.str();
     }
Referenced by veins::BaseMobility::handleBorderMsg(), veins::MobilityInfo::info(), veins::LinearMobility::makeMove(), and veins::BaseMobility::updatePosition().
setDirectionByTarget()
void veins::Move::setDirectionByTarget (const Coord & target) inline
Sets the direction to the normalized vector pointing from the current start position to the passed target point.
NOTE: The target point must not be the current start position or too close to it.
Definition at line 177 of file Move.h.
     {
         direction = target - startPos;
         ASSERT(!math::almost_equal(direction.length(), 0.0));
         direction /= direction.length();
     }
References veins::math::almost_equal(), and veins::Coord::length().
Referenced by veins::LinearMobility::makeMove().
setDirectionByVector()
void veins::Move::setDirectionByVector (const Coord & direction) inline
Sets the direction to the passed vector, which must be already normalized or the 0-vector.
Definition at line 164 of file Move.h.
     {
         ASSERT(math::almost_equal(direction.squareLength(), 1.0) || math::almost_equal(direction.squareLength(), 0.0));
         this->direction = direction;
     }
References veins::math::almost_equal(), and veins::Coord::squareLength().
Referenced by veins::TraCIMobility::changePosition(), veins::BaseMobility::handleBorderMsg(), veins::BaseMobility::initialize(), veins::TraCIMobility::initialize(), and veins::TraCIMobility::preInitialize().
setOrientationByVector()
void veins::Move::setOrientationByVector (const Coord & orientation) inline
Sets the orientation to the passed vector.
At least one of the x or y component has to be nonzero.
Definition at line 154 of file Move.h.
     {
         ASSERT(orientation.x != 0 || orientation.y != 0);
         this->orientation = orientation;
     }
References veins::Coord::x, and veins::Coord::y.
Referenced by veins::TraCIMobility::changePosition(), veins::BaseMobility::initialize(), veins::TraCIMobility::initialize(), and veins::TraCIMobility::preInitialize().
setSpeed()
void veins::Move::setSpeed (double speed) inline
Sets the current speed in meters per second.
Definition at line 90 of file Move.h.
     {
         this->speed = speed;
     }
Referenced by veins::TraCIMobility::changePosition(), veins::BaseMobility::initialize(), veins::LinearMobility::initialize(), veins::TraCIMobility::initialize(), veins::LinearMobility::makeMove(), veins::TraCIMobility::preInitialize(), veins::LocalMobility::updateLocalMobilityPos(), and veins::RemoteMobility::updateMobilityInfo().
setStart() [1/2]
void veins::Move::setStart (const Coord & startPos) inline
Sets start position to passed value (components in meters), start time will be set to current simulation-time.
Definition at line 125 of file Move.h.
     {
         setStart(startPos, simTime());
     }
setStart() [2/2]
void veins::Move::setStart (const Coord & startPos, simtime_t_cref startTime) inline
Sets start position (components in meters) and start time.
Definition at line 114 of file Move.h.
     {
         this->lastPos = startPos;
         this->startPos = startPos;
         this->startTime = startTime;
     }
Referenced by veins::TraCIMobility::changePosition(), veins::BaseMobility::handleBorderMsg(), veins::BaseMobility::initialize(), veins::TraCIMobility::initialize(), veins::LinearMobility::makeMove(), veins::TraCIMobility::preInitialize(), veins::LocalMobility::updateLocalMobilityPos(), and veins::RemoteMobility::updateMobilityInfo().
Member Data Documentation
direction
Coord veins::Move::direction protected
direction the host is moving to, must be normalized
Definition at line 55 of file Move.h.
lastPos
Coord veins::Move::lastPos protected
Last position which was set.
Definition at line 49 of file Move.h.
orientation
Coord veins::Move::orientation protected
orientation the host is pointing to
Definition at line 53 of file Move.h.
speed
double veins::Move::speed protected
speed of the host in meters per second
Definition at line 57 of file Move.h.
startPos
Coord veins::Move::startPos protected
Start position of the host (in meters)
Definition at line 47 of file Move.h.
startTime
simtime_t veins::Move::startTime protected
start time at which host started at startPos
Definition at line 51 of file Move.h.
The documentation for this class was generated from the following file:
Move.h