Contexto de Comunicação em VANET: veins::AgentPairList
veins::AgentPairList
Public Member Functions
double calcMaxDistancelr (int64_t agent)
double calcMaxSlr (int64_t agent)
double calcMinDistancelr (int64_t agent)
double calcMinSlr (int64_t agent)
AgentPair * getAgentPair (int64_t sourceId, int64_t destinationId)
AgentPair * getAgentPair (int64_t sourceId, int64_t destinationId, std::vector< AgentPair * > aAgentPairs)
int getAgentPairIndex (int64_t sourceId, int64_t destinationId)
std::string infoTraceAgentPairList ()
std::vector< AgentPair * > listAgentPairsWith (int64_t agentId)
std::vector< AgentPair * > listNeighbors (int64_t agentId)
AgentPair * updatePairListFromMsg (long numMsg, Agent *agentS, Agent *agentD, simtime_t pMsgReceivingTime, simtime_t msgSendingTime, RadiusEstimatorAgentPair *pRadiusEstimator, int neighbor, int event, simtime_t dataValidity, double pPeriodApp, double powerReceived_dbm, double snr)
Public Attributes
std::vector< AgentPair * > agentPairs
Member Function Documentation
calcMaxDistancelr()
double veins::AgentPairList::calcMaxDistancelr (int64_t agent)
Parameters
{
     AgentPair *c=NULL;
     double maxDistance = 0;
     unsigned int index = 0;
     while (agentPairs.size()> index)
     {
         c = dynamic_cast<AgentPair*>(agentPairs[index]);
          if (c->getCommnunicationState()!=CommState::faulty
                  && (c->getAgentD()->getId() == agent || c->getAgentS()->getId())
                  && c->getAgentPairMobility()->getDistancelr(c->getAgentS()->getMobilityInfo()->getActualMove(),c->getAgentD()->getMobilityInfo()->getActualMove())
                          > maxDistance )
          {
              maxDistance = c->getAgentPairMobility()->getDistancelr(c->getAgentS()->getMobilityInfo()->getActualMove(),c->getAgentD()->getMobilityInfo()->getActualMove());
            //std::cout << endl << "  destino: " << c->getAgentD()->getId() << "   origem: " << c->getAgentS()->getId() << endl;
          }
         ++index;
     }
     return  maxDistance;
 }
References veins::AgentPair::getAgentD(), veins::AgentPair::getAgentPairMobility(), veins::AgentPair::getAgentS(), veins::AgentPair::getCommnunicationState(), veins::AgentPairMobility::getDistancelr(), and veins::Agent::getId().
calcMaxSlr()
double veins::AgentPairList::calcMaxSlr (int64_t agent)
Parameters
{
     AgentPair *c=NULL;
     double maxSlr = 0;
     unsigned int index = 0;
     double aux;
     while (agentPairs.size()> index)
     {
         c = dynamic_cast<AgentPair*>(agentPairs[index]);
         aux = fabs(c->getQoCAgentPair()->getTimelinessAgentPair()->getSlr());
          if (c->getCommnunicationState()!=CommState::faulty
                  && (c->getAgentD()->getId() == agent || c->getAgentS()->getId())
                  && aux > maxSlr )
          {
              maxSlr = aux;
            //std::cout << endl << "  destino: " << c->getAgentD()->getId() << "   origem: " << c->getAgentS()->getId() << endl;
          }
         ++index;
     }
     return  maxSlr;
 }
References veins::AgentPair::getAgentD(), veins::AgentPair::getAgentS(), veins::AgentPair::getCommnunicationState(), and veins::Agent::getId().
calcMinDistancelr()
double veins::AgentPairList::calcMinDistancelr (int64_t agent)
Parameters
{
     AgentPair *c=NULL;
     double minDistance = 0;
     unsigned int index = 0;
     while (agentPairs.size()> index)
     {
         c = dynamic_cast<AgentPair*>(agentPairs[index]);
         if (index == 0 ) minDistance = c->getAgentPairMobility()->getDistancelr(c->getAgentS()->getMobilityInfo()->getActualMove(),c->getAgentD()->getMobilityInfo()->getActualMove());
          if (c->getCommnunicationState()!=CommState::faulty
                  && (c->getAgentD()->getId() == agent || c->getAgentS()->getId())
                  && c->getAgentPairMobility()->getDistancelr(c->getAgentS()->getMobilityInfo()->getActualMove(),c->getAgentD()->getMobilityInfo()->getActualMove()) < minDistance )
          {
              minDistance = c->getAgentPairMobility()->getDistancelr(c->getAgentS()->getMobilityInfo()->getActualMove(),c->getAgentD()->getMobilityInfo()->getActualMove());
            //std::cout << endl << "  destino: " << c->getAgentD()->getId() << "   origem: " << c->getAgentS()->getId() << endl;
          }
         ++index;
     }
     return  minDistance;
 }
References veins::AgentPair::getAgentD(), veins::AgentPair::getAgentPairMobility(), veins::AgentPair::getAgentS(), veins::AgentPair::getCommnunicationState(), veins::AgentPairMobility::getDistancelr(), and veins::Agent::getId().
calcMinSlr()
double veins::AgentPairList::calcMinSlr (int64_t agent)
Parameters
{
     AgentPair *c=NULL;
     double minSlr = -1;
     unsigned int index = 0;
     double aux;
     while (agentPairs.size()> index)
     {
         c = dynamic_cast<AgentPair*>(agentPairs[index]);
          if ((c->getAgentD()->getId() == agent || c->getAgentS()->getId())
                  && c->getCommnunicationState()!=CommState::faulty
                  && c->isNeighbors())
                  {
                  aux = fabs(c->getQoCAgentPair()->getTimelinessAgentPair()->getSlr());
                  if (minSlr == -1)
                   {
                      minSlr = aux;
                   }
                   if (aux < minSlr )
                      {
                       minSlr = aux;
                      }
                  // std::cout << endl << "  destino: " << c->getAgentD()->getId() << "   origem: " << c->getAgentS()->getId()
                 //          << " min slr " << minSlr;
                  }
         ++index;
     }
     return  minSlr;
 }
References veins::AgentPair::getAgentD(), veins::AgentPair::getAgentS(), veins::AgentPair::getCommnunicationState(), veins::Agent::getId(), and veins::AgentPair::isNeighbors().
The documentation for this class was generated from the following files:
AgentPairList.h
AgentPairList.cc