My Project: veins::FWMath
veins::FWMath
Support functions for mathematical operations.
#include <FWMath.h>
Static Public Member Functions
static double mod (double dividend, double divisor)
Returns the rest of a whole-numbered division.
static double div (double dividend, double divisor)
Returns the result of a whole-numbered division.
static double modulo (double a, double n)
Returns the remainder r on division of dividend a by divisor n, using floored division.
static VEINS_DEPRECATED bool close (double one, double two)
Tests whether two doubles are close enough to be declared equal.
static int stepfunction (double i)
Returns 0 if i is close to 0, 1 if i is positive and greater than epsilon, or -1 if it is negative and less than epsilon.
static int sign (double i)
Returns 1 if the parameter is greater or equal to zero, -1 otherwise.
static int round (double d)
Returns an integer that corresponds to rounded double parameter.
static double floorToZero (double d)
Discards the fractional part of the parameter, e.g.
static double max (double a, double b)
Returns the greater of the given parameters.
static double dBm2mW (double dBm)
Converts a dBm value into milliwatts.
static double mW2dBm (double mW)
Convert a mW value to dBm.
Detailed Description
Support functions for mathematical operations.
This class contains all kind of mathematical support functions
Author
Christian Frank
Definition at line 137 of file FWMath.h.
Member Function Documentation
close()
static VEINS_DEPRECATED bool veins::FWMath::close (double one, double two) inline static
Tests whether two doubles are close enough to be declared equal.
Returns true if parameters are at most epsilon apart, false otherwise
See also
veins::math::almost_equal
Definition at line 176 of file FWMath.h.
     {
         return fabs(one - two) < EPSILON;
     }
References EPSILON.
dBm2mW()
static double veins::FWMath::dBm2mW (double dBm) inline static
Converts a dBm value into milliwatts.
Definition at line 234 of file FWMath.h.
     {
         return pow(10.0, dBm / 10.0);
     }
Referenced by veins::SampledAntenna1D::getGain(), and veins::BasePhyLayer::initialize().
div()
static double veins::FWMath::div (double dividend, double divisor) inline static
Returns the result of a whole-numbered division.
Definition at line 152 of file FWMath.h.
     {
         double i;
         modf(dividend / divisor, &i);
         return i;
     }
floorToZero()
static double veins::FWMath::floorToZero (double d) inline static
Discards the fractional part of the parameter, e.g.
-3.8 becomes -3
Definition at line 218 of file FWMath.h.
     {
         return (d >= 0.0) ? floor(d) : ceil(d);
     }
max()
static double veins::FWMath::max (double a, double b) inline static
Returns the greater of the given parameters.
Definition at line 226 of file FWMath.h.
     {
         return (a < b) ? b : a;
     }
mod()
static double veins::FWMath::mod (double dividend, double divisor) inline static
Returns the rest of a whole-numbered division.
Definition at line 143 of file FWMath.h.
     {
         double i;
         return modf(dividend / divisor, &i) * divisor;
     }
modulo()
static double veins::FWMath::modulo (double a, double n) inline static
Returns the remainder r on division of dividend a by divisor n, using floored division.
The remainder r has the same sign as the divisor n.
Definition at line 163 of file FWMath.h.
     {
         return (a - n * floor(a / n));
     }
Referenced by veins::BaseMobility::wrapIfOutside().
mW2dBm()
static double veins::FWMath::mW2dBm (double mW) inline static
Convert a mW value to dBm.
Definition at line 242 of file FWMath.h.
     {
         return (10 * log10(mW));
     }
Referenced by veins::NakagamiFading::filterSignal(), and veins::TwoRayInterferenceModel::filterSignal().
round()
static int veins::FWMath::round (double d) inline static
Returns an integer that corresponds to rounded double parameter.
Definition at line 210 of file FWMath.h.
     {
         return (int) (ceil(d - 0.5));
     }
sign()
static int veins::FWMath::sign (double i) inline static
Returns 1 if the parameter is greater or equal to zero, -1 otherwise.
Definition at line 202 of file FWMath.h.
     {
         return (i >= 0) ? 1 : -1;
     };
stepfunction()
static int veins::FWMath::stepfunction (double i) inline static
Returns 0 if i is close to 0, 1 if i is positive and greater than epsilon, or -1 if it is negative and less than epsilon.
Definition at line 185 of file FWMath.h.
     {
         if (math::almost_equal<double>(i, 0)) {
             return 0;
         }
         if (std::signbit(i) == 1) {
             return -1;
         }
         else {
             return 1;
         }
     };
The documentation for this class was generated from the following file:
FWMath.h