My Project: veins::QoCInfo
veins::QoCInfo
#include <QoCInfo.h>
Public Member Functions
QoCInfo ()
virtual ~QoCInfo ()
Timeliness * getTimeliness ()
void setTimeliness (Timeliness *timeliness)
double getAge ()
void setAge (double age)
Protected Attributes
Timeliness * timeliness
double age
Detailed Description
Definition at line 24 of file QoCInfo.h.
Constructor & Destructor Documentation
QoCInfo()
veins::QoCInfo::QoCInfo ()
Definition at line 20 of file QoCInfo.cc.
                  {
     // TODO Auto-generated constructor stub
     this->age =0;
 }
References age.
~QoCInfo()
veins::QoCInfo::~QoCInfo () virtual
Definition at line 35 of file QoCInfo.cc.
                   {
     // TODO Auto-generated destructor stub
     delete(this);
 }
Member Function Documentation
getAge()
double veins::QoCInfo::getAge ()
Definition at line 41 of file QoCInfo.cc.
                       {
     return age;
 }
References age.
getTimeliness()
Timeliness * veins::QoCInfo::getTimeliness ()
Definition at line 27 of file QoCInfo.cc.
{
     return timeliness;
 }
References timeliness.
Referenced by veins::Routing::getRoute(), veins::AgentPair::info(), veins::AgentPair::infoTrace(), and veins::ForwardingNode::update().
setAge()
void veins::QoCInfo::setAge (double age)
Definition at line 45 of file QoCInfo.cc.
{
     this->age = age;
 }
References age.
setTimeliness()
void veins::QoCInfo::setTimeliness (Timeliness * timeliness)
Definition at line 31 of file QoCInfo.cc.
{
     this->timeliness = timeliness;
 }
References timeliness.
Member Data Documentation
age
double veins::QoCInfo::age protected
Definition at line 27 of file QoCInfo.h.
Referenced by getAge(), QoCInfo(), and setAge().
timeliness
Timeliness* veins::QoCInfo::timeliness protected
Definition at line 26 of file QoCInfo.h.
Referenced by getTimeliness(), veins::QoCAgentPair::getTimelinessAgentPair(), veins::QoCAgentPair::QoCAgentPair(), and setTimeliness().
The documentation for this class was generated from the following files:
QoCInfo.h
QoCInfo.cc