Veins: veins::TimelinessAgentPair Class Reference
veins::TimelinessAgentPair Class Reference
#include <TimelinessAgentPair.h>
Public Member Functions
double calcAngleQuadrant (double angleRad)
double calcLeicosseno (double angle)
TimelinessAgentPair ()
TimelinessAgentPair (AgentPair *c, simtime_t dataValidity)
std::string infoTrace (bool header)
virtual ~TimelinessAgentPair ()
double calcValidity (simtime_t dataValidity)
double calcAge ()
void update (simtime_t dataValidity)
std::string info ()
double getSlr ()
void setSlr (double slr)
double calcValidityTeste (simtime_t dataValidity)
double getAgeCommState ()
void setAgeCommState (double ageCommState)
double getAgeMobilityCondition ()
void setAgeMobilityCondition (double ageMobilityCondition)
double getAgeNeighberCondition ()
void setAgeNeighberCondition (double ageNeighberCondition)
simtime_t getTimeoutValidityCommState ()
void setTimeoutValidityCommState (simtime_t timeoutValidityCommState)
simtime_t getTimeoutValidityMobilityCondition ()
void setTimeoutValidityMobilityCondition (simtime_t timeoutValidityMobilityCondition)
simtime_t getTimeoutValidityNeighberCondition ()
void setTimeoutValidityNeighberCondition (simtime_t timeoutValidityNeighberCondition)
simtime_t getTimeStampUpdateCommState ()
void setTimeStampUpdateCommState (simtime_t timeStampUpdateCommState)
simtime_t getTimeStampUpdateMobilityCondition ()
void setTimeStampUpdateMobilityCondition (simtime_t timeStampUpdateMobilityCondition)
simtime_t getTimeStampUpdateNeighberCondition ()
void setTimeStampUpdateNeighberCondition (simtime_t timeStampUpdateNeighberCondition)
double getValidityCommState ()
void setValidityCommState (double validityCommState)
double getValidityMobilityCondition ()
void setValidityMobilityCondition (double validityMobilityCondition)
double getValidityNeighberCondition ()
void setValidityNeighberCondition (double validityNeighberCondition)
double getRelativeSpeedX ()
double getRelativeSpeedY ()
double getRelativeSpeed ()
double getRelativeSpeedAngle ()
Public Member Functions inherited from Timeliness
Timeliness ()
virtual ~Timeliness ()
virtual double getAge ()
virtual void setAge (double age)
virtual double getValidity ()
virtual double getValidityNow ()
virtual void setValidity (double validity)
std::string infoTrace (bool header)
std::string info ()
simtime_t getTimeoutValidity ()
void setTimeoutValidity (simtime_t timeoutValidity)
simtime_t getTimeStampUpdate ()
void setTimeStampUpdate (simtime_t timeStampUpdate)
double getCoConfianca ()
void setCoConfianca (double coConfianca)
double getValidityCoConfianca ()
Private Member Functions
void calcTimeoutValidity ()
double rounding (double src, int precision)
Private Attributes
AgentPair * c
double ageLastMsgReceiving
double ageAgentPair
double ageMobility
double SrlMin
double Srl
double slrmenos
double slrmais
double alfa
double maxRelativeSpeed =0
double timeliness
Coord sNext
Coord dNext
double VTmin
double VTminST
double VTTeste
double priorVTminST
double priorvalidity
double priorVTmin
double priorcoConfianca
double priortimeliness
double priorValidityST
double ValidityST
double coConfedenceTimeliness
double radiusR
double drl
double angler
double anglel
double tetarl
double tetarv
double vxr
double vyr
double vxl
double vyl
Coord r
Coord l
double vRX
double vRY
double vR
simtime_t timeStampAgentPair
double alphaQuadrant
double drlQuadrant
double vrlQuadrant
double Squadrant
double Dquadrant
Additional Inherited Members
Protected Attributes inherited from Timeliness
double validity
double coConfianca
double age
double priorAge
simtime_t timeoutValidity
simtime_t timeStampUpdate
double timeCommSignal
Detailed Description
Definition at line 36 of file TimelinessAgentPair.h.
Constructor & Destructor Documentation
TimelinessAgentPair() [1/2]
veins::TimelinessAgentPair::TimelinessAgentPair ()
Definition at line 319 of file TimelinessAgentPair.cc.
{
 }
TimelinessAgentPair() [2/2]
veins::TimelinessAgentPair::TimelinessAgentPair (AgentPair * c, simtime_t dataValidity)
Definition at line 20 of file TimelinessAgentPair.cc.
{
     // TODO Auto-generated constructor stub
     this->priorAge=0;
     priorValidityST = 0;
     priorvalidity = 0;
     priorVTmin = 0;
     priorVTminST=0;
     priorAge=0;
     priorcoConfianca = 0;
     priortimeliness = 0;
     validity = 0;
     ValidityST = 0;
     VTmin=0;
     coConfianca=0;
     coConfedenceTimeliness=0;
     timeliness = 0;
     this->c = c;
     update(dataValidity);
 }
References c, coConfedenceTimeliness, Timeliness::coConfianca, Timeliness::priorAge, priorcoConfianca, priortimeliness, priorvalidity, priorValidityST, priorVTmin, priorVTminST, timeliness, update(), Timeliness::validity, ValidityST, and VTmin.
~TimelinessAgentPair()
veins::TimelinessAgentPair::~TimelinessAgentPair () virtual
Definition at line 42 of file TimelinessAgentPair.cc.
{
     // TODO Auto-generated destructor stub
     delete(this);
 }
Member Function Documentation
calcAge()
double veins::TimelinessAgentPair::calcAge ()
Definition at line 239 of file TimelinessAgentPair.cc.
 {
     //ATENCAO -- TEMPORARIAMENTE ASSIM
    // double i = this->c->getAgentS()->getMobilityInfo()->getActualMove()->getStartTime().dbl();
    // double j = this->c->getAgentD()->getMobilityInfo()->getActualMove()->getStartTime().dbl();
     double i = this->c->getAgentS()->getMobilityInfo()->getCollectedMove()->getStartTime().dbl();
     double j = this->c->getAgentD()->getMobilityInfo()->getCollectedMove()->getStartTime().dbl();
     double k = this->c->getLastTMsgSending().dbl();
     this->priorAge = this->ageAgentPair;
     double vNow = simTime().dbl();
     double menor =i;
     if (i<j && i<k) menor = i;
     if (j<i && j<k) menor = j;
     if (k<j && k<i) menor = k;
     this->ageAgentPair = vNow - menor;
     if (i<j) menor = i;
     else menor = j;
     this->ageMobility = vNow - menor;
     this->ageLastMsgReceiving = vNow - k;
     this->age = this->ageAgentPair;
     return this->ageAgentPair;
 }
References Timeliness::age, ageAgentPair, ageLastMsgReceiving, ageMobility, c, veins::AgentPair::getAgentD(), veins::AgentPair::getAgentS(), veins::MobilityInfo::getCollectedMove(), veins::AgentPair::getLastTMsgSending(), veins::Agent::getMobilityInfo(), veins::Move::getStartTime(), and Timeliness::priorAge.
Referenced by info(), and update().
calcAngleQuadrant()
double veins::TimelinessAgentPair::calcAngleQuadrant (double angleRad)
Definition at line 223 of file TimelinessAgentPair.cc.
 {
     double anglec=oAngle;
     if (oAngle<0) anglec = 2*M_PI +oAngle;
     anglec = floor(anglec * 1000)/1000;
     //cout << endl << "  floor " << floor(anglec * 100)/100 << "  << " << anglec;
    //if (oAngle<=0.09 && oAngle>-0.09) anglec=0;
     double angleQuadrant = ceil(anglec/(M_PI/2));
     return angleQuadrant;
 }
References M_PI.
Referenced by calcLeicosseno().
calcLeicosseno()
double veins::TimelinessAgentPair::calcLeicosseno (double angle)
Definition at line 149 of file TimelinessAgentPair.cc.
 {
     double final = std::sqrt((drl*drl)*(std::cos(angle)*std::cos(angle))-(drl*drl)+(radiusR*radiusR));
     slrmais= drl*-1.0 *std::cos(angle) + final;
     slrmenos=drl*-1.0 *std::cos(angle) - final;
     double vSrl = 0;
     //if (slrmais<0)
     //    vSrl = slrmenos;
     //else
     //    if (slrmenos<0)
     //        vSrl = slrmais;
    // if (vSrl <0 )
    //     vSrl = 0;
    // std::cout << endl << c->getAgentD()->getId()<< "  mais = " << slrmais << "    slrmenos = " << slrmenos << "    Vslr ="
     //        << vSrl << std::endl;
     alphaQuadrant=calcAngleQuadrant(alfa);
     drlQuadrant=calcAngleQuadrant(tetarl);
     vrlQuadrant=calcAngleQuadrant(tetarv);
     Squadrant=calcAngleQuadrant(angler);
     Dquadrant=calcAngleQuadrant(anglel);
     if (this->Dquadrant==this->vrlQuadrant){
         vSrl = std::abs(slrmenos);
         if (this->c->getAgentS()->getMobilityInfo()->getActualMove()->getSpeed() >
             this->c->getAgentD()->getMobilityInfo()->getActualMove()->getSpeed())
             vSrl = std::abs(slrmais);
     }else
         vSrl = std::abs(slrmais);
     return vSrl;
 }
References alfa, alphaQuadrant, anglel, angler, c, calcAngleQuadrant(), Dquadrant, drl, drlQuadrant, veins::MobilityInfo::getActualMove(), veins::AgentPair::getAgentS(), veins::Agent::getMobilityInfo(), veins::Move::getSpeed(), radiusR, slrmais, slrmenos, Squadrant, tetarl, tetarv, and vrlQuadrant.
Referenced by calcValidityTeste().
calcTimeoutValidity()
void veins::TimelinessAgentPair::calcTimeoutValidity () private
Definition at line 216 of file TimelinessAgentPair.cc.
 {
     if (this->getValidity() > 0)
         this->timeoutValidity = this->timeStampUpdate + this->getValidity() + c->getMessageTTime();
     else  this->timeoutValidity = 0;
 }
References c, veins::AgentPair::getMessageTTime(), Timeliness::getValidity(), Timeliness::timeoutValidity, and Timeliness::timeStampUpdate.
calcValidity()
double veins::TimelinessAgentPair::calcValidity (simtime_t dataValidity)
Definition at line 185 of file TimelinessAgentPair.cc.
{
     calcValidityTeste(dataValidity);
      return (-1);
 }
References calcValidityTeste().
Referenced by update().
calcValidityTeste()
double veins::TimelinessAgentPair::calcValidityTeste (simtime_t dataValidity)
Definition at line 49 of file TimelinessAgentPair.cc.
{
     priorValidityST = ValidityST;
     priorvalidity = validity;
     priorVTmin = VTmin;
     priorVTminST = VTminST;
     priorcoConfianca = coConfianca;
     priortimeliness = timeliness;
     alfa =0;
     Srl = 0;
     slrmenos=0;
     slrmais=0;
     vRX =0;
     vRY =0;
     vR = 0;
     validity = 0;
     ValidityST = 0;
     VTTeste = 0;
     VTmin=0;
     coConfianca=0;
     coConfedenceTimeliness=0;
     timeliness = 0;
     timeStampAgentPair = c->getUpdatingTime();
     SrlMin = 0;
     //std::cout << endl << "begin  calcValidityTeste "<< endl;
     if (c->isNeighbors()
             && c->getCommnunicationState()!=CommState::faulty
             && c->getTxReceivedDBm()<0
             && (c->getCalcRadius() - this->c->getAgentPairMobility()->getDistancelr())>=0)
       {
             angler = c->getAgentS()->getMobilityInfo()->getAngle();
             anglel = c->getAgentD()->getMobilityInfo()->getAngle();
             radiusR = c->getCalcRadius();
             //Calc vehicles distance
             drl = this->c->getAgentPairMobility()->getDistancelr();
             tetarl = this->c->getAgentPairMobility()->getDistancelrAngleRad(); //rl Distance angle
             vRX =this->c->getAgentPairMobility()->getRelativeSpeedX();
             vRY =this->c->getAgentPairMobility()->getRelativeSpeedY();
             vR = this->c->getAgentPairMobility()->getRelativeSpeed();
             tetarv =this->c->getAgentPairMobility()->getRelativeSpeedAngle(); //Relative Velocity angle
             //Max Relative Speed
             this->maxRelativeSpeed = c->getAgentS()->getMobilityInfo()->getMaxSpeed()
                     + c->getAgentD()->getMobilityInfo()->getMaxSpeed();
             //srl calc - using movement direction applying
             alfa = tetarl - tetarv;
             Srl = calcLeicosseno(alfa);
             //SrlMin = (radiusR - drl);
             //if (SrlMin < 0) SrlMin =0;
             SrlMin = std::abs(slrmais) > std::abs(slrmenos)? std::abs(slrmenos) : std::abs(slrmais);
             double vrvt;
             if (vR <0.001) vrvt=0.001;
             else vrvt = vR;
             validity = (Srl/vrvt);
             if (validity<age) ValidityST = 0;
             else ValidityST = validity - age;
             //conservative validity time -- max Relative Speed
             if (maxRelativeSpeed!=0)
             {
                 //conservative validity time Minimum Validity Time -- considering only vehicles approaching
                 this->VTmin = SrlMin/maxRelativeSpeed;
                 if (VTmin < age) VTminST=0;
                 else VTminST=VTmin - age;
             }
             if (validity!=0)
             {
                 if (age<validity) timeliness = 1-(this->age/validity);
                 if (VTmin<=age && age<validity)
                 {
                     this->coConfianca = (1-(age - VTmin)/(validity - VTmin));
                 }
                 else
                     if (VTmin > age)
                     {
                         this->coConfianca=1;
                     }
             }
         }
         //std::cout << endl << "end  calcValidityTeste "<< endl;
         return -1;
     }
References Timeliness::age, alfa, anglel, angler, c, calcLeicosseno(), coConfedenceTimeliness, Timeliness::coConfianca, drl, CommState::faulty, veins::AgentPair::getAgentD(), veins::AgentPair::getAgentPairMobility(), veins::AgentPair::getAgentS(), veins::MobilityInfo::getAngle(), veins::AgentPair::getCalcRadius(), veins::AgentPair::getCommnunicationState(), veins::AgentPairMobility::getDistancelr(), veins::AgentPairMobility::getDistancelrAngleRad(), veins::MobilityInfo::getMaxSpeed(), veins::Agent::getMobilityInfo(), veins::AgentPairMobility::getRelativeSpeed(), veins::AgentPairMobility::getRelativeSpeedAngle(), veins::AgentPairMobility::getRelativeSpeedX(), veins::AgentPairMobility::getRelativeSpeedY(), veins::AgentPair::getTxReceivedDBm(), veins::AgentPair::getUpdatingTime(), veins::AgentPair::isNeighbors(), maxRelativeSpeed, priorcoConfianca, priortimeliness, priorvalidity, priorValidityST, priorVTmin, priorVTminST, radiusR, slrmais, slrmenos, Srl, SrlMin, tetarl, tetarv, timeliness, timeStampAgentPair, Timeliness::validity, ValidityST, vR, vRX, vRY, VTmin, VTminST, and VTTeste.
Referenced by calcValidity().
getAgeCommState()
double veins::TimelinessAgentPair::getAgeCommState ()
getAgeMobilityCondition()
double veins::TimelinessAgentPair::getAgeMobilityCondition ()
getAgeNeighberCondition()
double veins::TimelinessAgentPair::getAgeNeighberCondition ()
getRelativeSpeed()
double veins::TimelinessAgentPair::getRelativeSpeed ()
getRelativeSpeedAngle()
double veins::TimelinessAgentPair::getRelativeSpeedAngle ()
getRelativeSpeedX()
double veins::TimelinessAgentPair::getRelativeSpeedX ()
getRelativeSpeedY()
double veins::TimelinessAgentPair::getRelativeSpeedY ()
getSlr()
double veins::TimelinessAgentPair::getSlr ()
Definition at line 322 of file TimelinessAgentPair.cc.
{
     return this->Srl;
 }
References Srl.
Referenced by veins::AgentPairList::calcMaxSlr(), and veins::AgentPairList::calcMinSlr().
getTimeoutValidityCommState()
simtime_t veins::TimelinessAgentPair::getTimeoutValidityCommState ()
getTimeoutValidityMobilityCondition()
simtime_t veins::TimelinessAgentPair::getTimeoutValidityMobilityCondition ()
getTimeoutValidityNeighberCondition()
simtime_t veins::TimelinessAgentPair::getTimeoutValidityNeighberCondition ()
getTimeStampUpdateCommState()
simtime_t veins::TimelinessAgentPair::getTimeStampUpdateCommState ()
getTimeStampUpdateMobilityCondition()
simtime_t veins::TimelinessAgentPair::getTimeStampUpdateMobilityCondition ()
getTimeStampUpdateNeighberCondition()
simtime_t veins::TimelinessAgentPair::getTimeStampUpdateNeighberCondition ()
getValidityCommState()
double veins::TimelinessAgentPair::getValidityCommState ()
getValidityMobilityCondition()
double veins::TimelinessAgentPair::getValidityMobilityCondition ()
getValidityNeighberCondition()
double veins::TimelinessAgentPair::getValidityNeighberCondition ()
info()
std::string veins::TimelinessAgentPair::info ()
Definition at line 267 of file TimelinessAgentPair.cc.
{
     std::ostringstream ost;
     ost << "  TIMELINESS: "
         << "  VALIDITY - " << this->validity
         << "  AGE - " << this->calcAge();
     return ost.str();
 }
References calcAge(), and Timeliness::validity.
infoTrace()
std::string veins::TimelinessAgentPair::infoTrace (bool header)
Definition at line 275 of file TimelinessAgentPair.cc.
{
     std::ostringstream ost;
     if (header)
         ost <<  ";timeStampAgentPair;"
                 "alfa;"
                 "alfaGrau;"
                 "Srl;srlmais;srlmenos;SrlMin;priorVTinT;VTinT;priorVT;VT;"
                 "priorVTmin;VTmin;priorVTminT;VTminT;"
                 "AnteriorAgePair;ageAgentPair;"
                 "priorcoConfianca;coConfianca;"
                 "priortimeliness;timeliness;alpha;quadranteDrl;quadranteVrl;quadranteS;quadranteD";
     else{
         ost
         <<";" << this->timeStampAgentPair
         <<";" << alfa
         <<";" << alfa*180/M_PI
         <<";" << Srl
         <<";" << slrmais
         <<";" << slrmenos
         <<";" << SrlMin
         <<";" << priorValidityST
         <<";" << ValidityST
         <<";" << priorvalidity
         <<";" << validity
         <<";" << priorVTmin
         <<";" << VTmin
         <<";" << priorVTminST
         <<";" << VTminST
         <<";" << priorAge
         <<";" << ageAgentPair
         <<";" << priorcoConfianca
         <<";" << coConfianca
         <<";" << priortimeliness
         <<";" << timeliness
         <<";" << alphaQuadrant
         <<";" << drlQuadrant
         <<";" << vrlQuadrant
         <<";" << Squadrant
         <<";" << Dquadrant;
     }
     return ost.str();
 }
References ageAgentPair, alfa, alphaQuadrant, Timeliness::coConfianca, Dquadrant, drlQuadrant, M_PI, Timeliness::priorAge, priorcoConfianca, priortimeliness, priorvalidity, priorValidityST, priorVTmin, priorVTminST, slrmais, slrmenos, Squadrant, Srl, SrlMin, timeliness, timeStampAgentPair, Timeliness::validity, ValidityST, vrlQuadrant, VTmin, and VTminST.
Referenced by veins::AgentPair::infoTrace().
rounding()
double veins::TimelinessAgentPair::rounding (double src, int precision) private
setAgeCommState()
void veins::TimelinessAgentPair::setAgeCommState (double ageCommState)
setAgeMobilityCondition()
void veins::TimelinessAgentPair::setAgeMobilityCondition (double ageMobilityCondition)
setAgeNeighberCondition()
void veins::TimelinessAgentPair::setAgeNeighberCondition (double ageNeighberCondition)
setSlr()
void veins::TimelinessAgentPair::setSlr (double slr)
Definition at line 326 of file TimelinessAgentPair.cc.
{
     this->Srl = Srl;
 }
References Srl.
setTimeoutValidityCommState()
void veins::TimelinessAgentPair::setTimeoutValidityCommState (simtime_t timeoutValidityCommState)
setTimeoutValidityMobilityCondition()
void veins::TimelinessAgentPair::setTimeoutValidityMobilityCondition (simtime_t timeoutValidityMobilityCondition)
setTimeoutValidityNeighberCondition()
void veins::TimelinessAgentPair::setTimeoutValidityNeighberCondition (simtime_t timeoutValidityNeighberCondition)
setTimeStampUpdateCommState()
void veins::TimelinessAgentPair::setTimeStampUpdateCommState (simtime_t timeStampUpdateCommState)
setTimeStampUpdateMobilityCondition()
void veins::TimelinessAgentPair::setTimeStampUpdateMobilityCondition (simtime_t timeStampUpdateMobilityCondition)
setTimeStampUpdateNeighberCondition()
void veins::TimelinessAgentPair::setTimeStampUpdateNeighberCondition (simtime_t timeStampUpdateNeighberCondition)
setValidityCommState()
void veins::TimelinessAgentPair::setValidityCommState (double validityCommState)
setValidityMobilityCondition()
void veins::TimelinessAgentPair::setValidityMobilityCondition (double validityMobilityCondition)
setValidityNeighberCondition()
void veins::TimelinessAgentPair::setValidityNeighberCondition (double validityNeighberCondition)
update()
void veins::TimelinessAgentPair::update (simtime_t dataValidity)
Definition at line 193 of file TimelinessAgentPair.cc.
{
     //std::cout << endl << "begin  TimelinessAgentPair::update setCalcRadius AgentPair updateAgentPairsFromMsg "<< endl;
     this->calcAge();
     if (c->isNeighbors()) this->calcValidity(dataValidity);
     /*else {
         ICarRoute * icR;
         for (int index=0; index < c->pairRoutes.size();index++){
             icR = c->pairRoutes.at(index);
             icR->update();
             if (icR->qocValidityTime > c->getQoCAgentPair()->getTimelinessAgentPair()->timeoutValidity )
             {
                 c->getQoCAgentPair()->getTimelinessAgentPair()->timeoutValidity = icR->qocValidityTime;
             }
         }
     }*/
     //std::cout << endl << "end  TimelinessAgentPair::update setCalcRadius AgentPair updateAgentPairsFromMsg "<< endl;
 }
References c, calcAge(), calcValidity(), and veins::AgentPair::isNeighbors().
Referenced by TimelinessAgentPair(), and veins::AgentPair::updateAgentPair().
Member Data Documentation
ageAgentPair
double veins::TimelinessAgentPair::ageAgentPair private
Definition at line 40 of file TimelinessAgentPair.h.
Referenced by calcAge(), and infoTrace().
ageLastMsgReceiving
double veins::TimelinessAgentPair::ageLastMsgReceiving private
Definition at line 39 of file TimelinessAgentPair.h.
Referenced by calcAge().
ageMobility
double veins::TimelinessAgentPair::ageMobility private
Definition at line 41 of file TimelinessAgentPair.h.
Referenced by calcAge().
alfa
double veins::TimelinessAgentPair::alfa private
Definition at line 47 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), calcValidityTeste(), and infoTrace().
alphaQuadrant
double veins::TimelinessAgentPair::alphaQuadrant private
Definition at line 81 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and infoTrace().
anglel
double veins::TimelinessAgentPair::anglel private
Definition at line 69 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and calcValidityTeste().
angler
double veins::TimelinessAgentPair::angler private
Definition at line 67 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and calcValidityTeste().
c
AgentPair* veins::TimelinessAgentPair::c private
Definition at line 38 of file TimelinessAgentPair.h.
Referenced by calcAge(), calcLeicosseno(), calcTimeoutValidity(), calcValidityTeste(), TimelinessAgentPair(), and update().
coConfedenceTimeliness
double veins::TimelinessAgentPair::coConfedenceTimeliness private
Definition at line 62 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), and TimelinessAgentPair().
dNext
Coord veins::TimelinessAgentPair::dNext private
Definition at line 51 of file TimelinessAgentPair.h.
Dquadrant
double veins::TimelinessAgentPair::Dquadrant private
Definition at line 85 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and infoTrace().
drl
double veins::TimelinessAgentPair::drl private
Definition at line 66 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and calcValidityTeste().
drlQuadrant
double veins::TimelinessAgentPair::drlQuadrant private
Definition at line 82 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and infoTrace().
l
Coord veins::TimelinessAgentPair::l private
Definition at line 76 of file TimelinessAgentPair.h.
maxRelativeSpeed
double veins::TimelinessAgentPair::maxRelativeSpeed =0 private
Definition at line 48 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste().
priorcoConfianca
double veins::TimelinessAgentPair::priorcoConfianca private
Definition at line 58 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), infoTrace(), and TimelinessAgentPair().
priortimeliness
double veins::TimelinessAgentPair::priortimeliness private
Definition at line 59 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), infoTrace(), and TimelinessAgentPair().
priorvalidity
double veins::TimelinessAgentPair::priorvalidity private
Definition at line 56 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), infoTrace(), and TimelinessAgentPair().
priorValidityST
double veins::TimelinessAgentPair::priorValidityST private
Definition at line 60 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), infoTrace(), and TimelinessAgentPair().
priorVTmin
double veins::TimelinessAgentPair::priorVTmin private
Definition at line 57 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), infoTrace(), and TimelinessAgentPair().
priorVTminST
double veins::TimelinessAgentPair::priorVTminST private
Definition at line 55 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), infoTrace(), and TimelinessAgentPair().
r
Coord veins::TimelinessAgentPair::r private
Definition at line 76 of file TimelinessAgentPair.h.
radiusR
double veins::TimelinessAgentPair::radiusR private
Definition at line 65 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and calcValidityTeste().
slrmais
double veins::TimelinessAgentPair::slrmais private
Definition at line 46 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), calcValidityTeste(), and infoTrace().
slrmenos
double veins::TimelinessAgentPair::slrmenos private
Definition at line 45 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), calcValidityTeste(), and infoTrace().
sNext
Coord veins::TimelinessAgentPair::sNext private
Definition at line 50 of file TimelinessAgentPair.h.
Squadrant
double veins::TimelinessAgentPair::Squadrant private
Definition at line 84 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and infoTrace().
Srl
double veins::TimelinessAgentPair::Srl private
Definition at line 44 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), getSlr(), infoTrace(), and setSlr().
SrlMin
double veins::TimelinessAgentPair::SrlMin private
Definition at line 42 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), and infoTrace().
tetarl
double veins::TimelinessAgentPair::tetarl private
Definition at line 70 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and calcValidityTeste().
tetarv
double veins::TimelinessAgentPair::tetarv private
Definition at line 71 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and calcValidityTeste().
timeliness
double veins::TimelinessAgentPair::timeliness private
Definition at line 49 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), infoTrace(), and TimelinessAgentPair().
timeStampAgentPair
simtime_t veins::TimelinessAgentPair::timeStampAgentPair private
Definition at line 80 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), and infoTrace().
ValidityST
double veins::TimelinessAgentPair::ValidityST private
Definition at line 61 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), infoTrace(), and TimelinessAgentPair().
vR
double veins::TimelinessAgentPair::vR private
Definition at line 79 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste().
vrlQuadrant
double veins::TimelinessAgentPair::vrlQuadrant private
Definition at line 83 of file TimelinessAgentPair.h.
Referenced by calcLeicosseno(), and infoTrace().
vRX
double veins::TimelinessAgentPair::vRX private
Definition at line 77 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste().
vRY
double veins::TimelinessAgentPair::vRY private
Definition at line 78 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste().
VTmin
double veins::TimelinessAgentPair::VTmin private
Definition at line 52 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), infoTrace(), and TimelinessAgentPair().
VTminST
double veins::TimelinessAgentPair::VTminST private
Definition at line 53 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste(), and infoTrace().
VTTeste
double veins::TimelinessAgentPair::VTTeste private
Definition at line 54 of file TimelinessAgentPair.h.
Referenced by calcValidityTeste().
vxl
double veins::TimelinessAgentPair::vxl private
Definition at line 74 of file TimelinessAgentPair.h.
vxr
double veins::TimelinessAgentPair::vxr private
Definition at line 72 of file TimelinessAgentPair.h.
vyl
double veins::TimelinessAgentPair::vyl private
Definition at line 75 of file TimelinessAgentPair.h.
vyr
double veins::TimelinessAgentPair::vyr private
Definition at line 73 of file TimelinessAgentPair.h.
The documentation for this class was generated from the following files:
TimelinessAgentPair.h
TimelinessAgentPair.cc