My Project: veins::AgentPairMobility
veins::AgentPairMobility
#include <AgentPairMobility.h>
Public Member Functions
AgentPairMobility ()
virtual ~AgentPairMobility ()
AgentPairMobility (AgentPair *c)
std::string info ()
void calcRelativeSpeed ()
std::string infoTrace (bool header)
void updateAgentPairMobility ()
double getDistancelr (Move *l, Move *r)
double getDistancelr ()
TEMPORARIO velocidade calculo da referencia vref e do movel v.
void calcDistance ()
double calcEuclideanDistancelr (Coord l, Coord r)
float getLastDistancelr ()
double getRelativeSpeedX ()
double getRelativeSpeedY ()
double getRelativeSpeed ()
double getRelativeSpeedAngle ()
void setRelativeSpeed (double relativeSpeed)
AgentPair * getC ()
void setC (AgentPair *c)
double getDistancelrAngleRad ()
void setDistancelrAngleRad (double distancelrAngle)
simtime_t getLasDistanceTime ()
void setLasDistanceTime (simtime_t lasDistanceTime)
void setLastDistancelr (double lastDistancelr)
double getRelativeSpeedAngleRad ()
void setRelativeSpeedAngleRad (double relativeSpeedAngle)
void setRelativeSpeedX (double relativeSpeedX)
void setRelativeSpeedY (double relativeSpeedY)
double getDistancelrX ()
double getDistancelrY ()
double getMaxRelativeSpeed ()
void setMaxRelativeSpeed (double maxRelativeSpeed)
double getMaxAngleRelativeSpeed ()
void setMaxAngleRelativeSpeed (double maxAngleRelativeSpeed)
Public Member Functions inherited from veins::MobilityInfo
MobilityInfo ()
virtual ~MobilityInfo ()
std::string info ()
MobilityInfo (Move *mSrc)
virtual Move * getLastMove ()
float getMaxSpeed ()
Returns a string with the value of the coordinate.
void setMaxSpeed (float maxSpeed)
virtual double calcEuclideanDistanceAgentMoving ()
double calcEuclideanDistancelr (Coord l, Coord r)
virtual std::string moveInfoTrace (bool header)
Returns information about the current state.
std::string infoTrace (bool header, std::string idagent)
Returns information about the current state.
float getAcceleration ()
void setAcceleration (float acceleration)
Move * getActualMove ()
void setActualMove (Move *actualMove)
double getSensorPeriod ()
void setSensorPeriod (float sensorPeriod)
int getQuadrant (double angleRad)
float getAngle ()
Coord getPositionAtTime (simtime_t pTime)
void setAngle (float angle)
double getAge ()
void setAge (double age)
const Move * getCollectedMove ()
void setCollectedMove (Move *collectedMove)
Private Attributes
AgentPair * c
relative speed between l and r
double relativeSpeed
relative speed between l and r
double relativeSpeedX
X relative speed between l and r.
double relativeSpeedY
Y relative speed between l and r.
double relativeSpeedAngleRad
relative speed angle between l and r
double distancelrAngleRad
double distancelr
double distancelrX
double distancelrY
double distancelrZ
double lastDistancelr
double maxRelativeSpeed
double maxAngleRelativeSpeed
Additional Inherited Members
Protected Member Functions inherited from veins::MobilityInfo
void setLastMove (Move *pMove)
void calcAcceleration ()
Protected Attributes inherited from veins::MobilityInfo
Move * actualMove = new Move()
current vehicle movement
Move * lastMove = new Move()
last vehicle movement before current position
Move * collectedMove = new Move()
collected vehicle movement
float maxSpeed =0
float sensorPeriod
float acceleration
float angle
double age
Detailed Description
Definition at line 32 of file AgentPairMobility.h.
Constructor & Destructor Documentation
AgentPairMobility() [1/2]
veins::AgentPairMobility::AgentPairMobility ()
Parameters
Definition at line 21 of file AgentPairMobility.cc.
{
     // TODO Auto-generated constructor stub
 }
~AgentPairMobility()
veins::AgentPairMobility::~AgentPairMobility () virtual
Parameters
Definition at line 26 of file AgentPairMobility.cc.
{
     // TODO Auto-generated destructor stub
 }
AgentPairMobility() [2/2]
veins::AgentPairMobility::AgentPairMobility (AgentPair * c)
Parameters
Definition at line 59 of file AgentPairMobility.cc.
 {
     this->c = c;
     this->calcDistance();
     this->lastDistancelr = this->distancelr;
     this->calcRelativeSpeed();
 }
References c, calcDistance(), calcRelativeSpeed(), distancelr, and lastDistancelr.
Member Function Documentation
calcDistance()
void veins::AgentPairMobility::calcDistance ()
Definition at line 100 of file AgentPairMobility.cc.
{
     //Calc vehicles distance
     Coord s = c->getAgentS()->getMobilityInfo()->getActualMove()->getStartPos();
     Coord d = c->getAgentD()->getMobilityInfo()->getActualMove()->getStartPos();
     this->distancelrX = (s.x - d.x);
     this->distancelrY = (s.y - d.y);
     this->distancelrZ = (s.z - d.z);
     //this->distancelrZ = 0;
     this->distancelr = std::sqrt((this->distancelrX*this->distancelrX) + (this->distancelrY*this->distancelrY));
     this->distancelrAngleRad = std::atan2(this->distancelrY,this->distancelrX); //rl Distance angle
 }
References c, distancelr, distancelrAngleRad, distancelrX, distancelrY, distancelrZ, veins::MobilityInfo::getActualMove(), veins::AgentPair::getAgentD(), veins::AgentPair::getAgentS(), veins::Agent::getMobilityInfo(), veins::Move::getStartPos(), veins::Coord::x, veins::Coord::y, and veins::Coord::z.
Referenced by AgentPairMobility(), and updateAgentPairMobility().
calcEuclideanDistancelr()
double veins::AgentPairMobility::calcEuclideanDistancelr (Coord l, Coord r)
Definition at line 200 of file AgentPairMobility.cc.
{
     return std::sqrt((r.x - l.x)*(r.x - l.x) + (r.y - l.y)*(r.y - l.y));
 }
References veins::Coord::x, and veins::Coord::y.
Referenced by getDistancelr(), and veins::AgentPair::setCalcRadius().
calcRelativeSpeed()
void veins::AgentPairMobility::calcRelativeSpeed ()
Parameters
Definition at line 74 of file AgentPairMobility.cc.
{
     double angleS = c->getAgentS()->getMobilityInfo()->getAngle();
     double angleD = c->getAgentD()->getMobilityInfo()->getAngle();
     double vxS=c->getAgentS()->getMobilityInfo()->getActualMove()->getSpeed()* std::cos(angleS);
     double vyS=c->getAgentS()->getMobilityInfo()->getActualMove()->getSpeed()* std::sin(angleS);
     double vxD=c->getAgentD()->getMobilityInfo()->getActualMove()->getSpeed()* std::cos(angleD);
     double vyD=c->getAgentD()->getMobilityInfo()->getActualMove()->getSpeed()* std::sin(angleD);
     relativeSpeedX =vxS-vxD;
     relativeSpeedY =vyS-vyD;
     relativeSpeed = std::sqrt((relativeSpeedX*relativeSpeedX) + (relativeSpeedY*relativeSpeedY));
     relativeSpeedAngleRad = std::atan2(relativeSpeedY, relativeSpeedX); //Relative Velocity angle
     //Max Relative Speed
     this->maxRelativeSpeed = c->getAgentS()->getMobilityInfo()->getMaxSpeed()
             + c->getAgentD()->getMobilityInfo()->getMaxSpeed();
     double vxSMax=c->getAgentS()->getMobilityInfo()->getMaxSpeed() * std::cos(angleS);
     double vySMax=c->getAgentS()->getMobilityInfo()->getMaxSpeed() * std::sin(angleS);
     double vxDMax=c->getAgentD()->getMobilityInfo()->getMaxSpeed() * std::cos(angleD);
     double vyDMax=c->getAgentD()->getMobilityInfo()->getMaxSpeed() * std::sin(angleD);
     double relativeSpeedXMax =vxSMax-vxDMax;
     double relativeSpeedYMax =vxSMax- vyDMax;
     this->maxAngleRelativeSpeed  = std::sqrt((relativeSpeedXMax*relativeSpeedXMax) + (relativeSpeedYMax*relativeSpeedYMax));
 }
References c, veins::MobilityInfo::getActualMove(), veins::AgentPair::getAgentD(), veins::AgentPair::getAgentS(), veins::MobilityInfo::getAngle(), veins::MobilityInfo::getMaxSpeed(), veins::Agent::getMobilityInfo(), veins::Move::getSpeed(), maxAngleRelativeSpeed, maxRelativeSpeed, relativeSpeed, relativeSpeedAngleRad, relativeSpeedX, and relativeSpeedY.
Referenced by AgentPairMobility(), and updateAgentPairMobility().
getC()
AgentPair * veins::AgentPairMobility::getC ()
Definition at line 117 of file AgentPairMobility.cc.
{
     return c;
 }
References c.
getDistancelr() [1/2]
double veins::AgentPairMobility::getDistancelr ()
TEMPORARIO velocidade calculo da referencia vref e do movel v.
Parameters
Definition at line 192 of file AgentPairMobility.cc.
{
     return distancelr;
 }
References distancelr.
getDistancelr() [2/2]
double veins::AgentPairMobility::getDistancelr (Move * l, Move * r)
Parameters
Definition at line 196 of file AgentPairMobility.cc.
{
     return this->calcEuclideanDistancelr(l->getStartPos(), r->getStartPos());
 }
References calcEuclideanDistancelr(), and veins::Move::getStartPos().
Referenced by veins::AgentPairList::calcMaxDistancelr(), veins::AgentPairList::calcMinDistancelr(), veins::TimelinessAgentPair::calcValidityTeste(), veins::AgentPair::setOutOfRadiusRangeState(), veins::IcarContext::textDataAgentPair(), and veins::AgentPair::updateNeighborhoodCondition().
getDistancelrAngleRad()
double veins::AgentPairMobility::getDistancelrAngleRad ()
Definition at line 126 of file AgentPairMobility.cc.
{
     return distancelrAngleRad;
 }
References distancelrAngleRad.
Referenced by veins::TimelinessAgentPair::calcValidityTeste().
getDistancelrX()
double veins::AgentPairMobility::getDistancelrX ()
Definition at line 155 of file AgentPairMobility.cc.
{
     return distancelrX;
 }
References distancelrX.
getDistancelrY()
double veins::AgentPairMobility::getDistancelrY ()
Definition at line 159 of file AgentPairMobility.cc.
{
     return distancelrY;
 }
References distancelrY.
getLasDistanceTime()
simtime_t veins::AgentPairMobility::getLasDistanceTime ()
getLastDistancelr()
float veins::AgentPairMobility::getLastDistancelr ()
Parameters
Definition at line 188 of file AgentPairMobility.cc.
{
     return lastDistancelr;
 }
References lastDistancelr.
getMaxAngleRelativeSpeed()
double veins::AgentPairMobility::getMaxAngleRelativeSpeed ()
Definition at line 204 of file AgentPairMobility.cc.
{
     return maxAngleRelativeSpeed;
 }
References maxAngleRelativeSpeed.
getMaxRelativeSpeed()
double veins::AgentPairMobility::getMaxRelativeSpeed ()
Definition at line 163 of file AgentPairMobility.cc.
{
     return maxRelativeSpeed;
 }
References maxRelativeSpeed.
getRelativeSpeed()
double veins::AgentPairMobility::getRelativeSpeed ()
Definition at line 179 of file AgentPairMobility.cc.
{
     return relativeSpeed;
 }
References relativeSpeed.
Referenced by veins::TimelinessAgentPair::calcValidityTeste().
getRelativeSpeedAngle()
double veins::AgentPairMobility::getRelativeSpeedAngle ()
Definition at line 183 of file AgentPairMobility.cc.
{
     return relativeSpeedAngleRad;
 }
References relativeSpeedAngleRad.
Referenced by veins::TimelinessAgentPair::calcValidityTeste().
getRelativeSpeedAngleRad()
double veins::AgentPairMobility::getRelativeSpeedAngleRad ()
Definition at line 143 of file AgentPairMobility.cc.
{
     return relativeSpeedAngleRad;
 }
References relativeSpeedAngleRad.
getRelativeSpeedX()
double veins::AgentPairMobility::getRelativeSpeedX ()
Definition at line 113 of file AgentPairMobility.cc.
{
     return relativeSpeedX;
 }
References relativeSpeedX.
Referenced by veins::TimelinessAgentPair::calcValidityTeste().
getRelativeSpeedY()
double veins::AgentPairMobility::getRelativeSpeedY ()
Definition at line 175 of file AgentPairMobility.cc.
{
     return relativeSpeedY;
 }
References relativeSpeedY.
Referenced by veins::TimelinessAgentPair::calcValidityTeste().
info()
std::string veins::AgentPairMobility::info ()
Parameters
Definition at line 30 of file AgentPairMobility.cc.
{
     std::ostringstream ost;
     ost << "  l r agents distance: " << this->distancelr
         << "  l r relative speed : " << this->relativeSpeed;
      //   << "  l r agents movement time: " << this->movementCurrentTime;
     return ost.str();
 }
References distancelr, and relativeSpeed.
Referenced by veins::AgentPair::info().
infoTrace()
std::string veins::AgentPairMobility::infoTrace (bool header)
Parameters
Definition at line 38 of file AgentPairMobility.cc.
 {
     std::ostringstream ost;
     if (header)
        ost << ";drl;drlAngleRad;drlX;drlY;rSpeed_rl;rSpeedrlAngle;rSpeedXrl;rSpeedYrl";
     else
     {
         ost << ";" << this->distancelr
             << ";" << this->distancelrAngleRad
             << ";" << this->distancelrX
             << ";" << this->distancelrY
             << ";" << this->relativeSpeed
             << ";" << this->relativeSpeedAngleRad
             << ";" << this->relativeSpeedX
             << ";" << this->relativeSpeedY;
     }
     return ost.str();
 }
References distancelr, distancelrAngleRad, distancelrX, distancelrY, relativeSpeed, relativeSpeedAngleRad, relativeSpeedX, and relativeSpeedY.
Referenced by veins::AgentPair::infoTrace().
setC()
void veins::AgentPairMobility::setC (AgentPair * c)
Definition at line 121 of file AgentPairMobility.cc.
{
     this->c = c;
 }
References c.
setDistancelrAngleRad()
void veins::AgentPairMobility::setDistancelrAngleRad (double distancelrAngle)
Definition at line 130 of file AgentPairMobility.cc.
{
     this->distancelrAngleRad = distancelrAngle;
 }
References distancelrAngleRad.
setLasDistanceTime()
void veins::AgentPairMobility::setLasDistanceTime (simtime_t lasDistanceTime)
setLastDistancelr()
void veins::AgentPairMobility::setLastDistancelr (double lastDistancelr)
Definition at line 135 of file AgentPairMobility.cc.
{
     this->lastDistancelr = lastDistancelr;
 }
References lastDistancelr.
setMaxAngleRelativeSpeed()
void veins::AgentPairMobility::setMaxAngleRelativeSpeed (double maxAngleRelativeSpeed)
Definition at line 208 of file AgentPairMobility.cc.
{
     this->maxAngleRelativeSpeed = maxAngleRelativeSpeed;
 }
References maxAngleRelativeSpeed.
setMaxRelativeSpeed()
void veins::AgentPairMobility::setMaxRelativeSpeed (double maxRelativeSpeed)
Definition at line 167 of file AgentPairMobility.cc.
{
     this->maxRelativeSpeed = maxRelativeSpeed;
 }
References maxRelativeSpeed.
setRelativeSpeed()
void veins::AgentPairMobility::setRelativeSpeed (double relativeSpeed)
Definition at line 139 of file AgentPairMobility.cc.
{
     this->relativeSpeed = relativeSpeed;
 }
References relativeSpeed.
setRelativeSpeedAngleRad()
void veins::AgentPairMobility::setRelativeSpeedAngleRad (double relativeSpeedAngle)
Definition at line 147 of file AgentPairMobility.cc.
{
     this->relativeSpeedAngleRad = relativeSpeedAngle;
 }
References relativeSpeedAngleRad.
setRelativeSpeedX()
void veins::AgentPairMobility::setRelativeSpeedX (double relativeSpeedX)
Definition at line 151 of file AgentPairMobility.cc.
{
     this->relativeSpeedX = relativeSpeedX;
 }
References relativeSpeedX.
setRelativeSpeedY()
void veins::AgentPairMobility::setRelativeSpeedY (double relativeSpeedY)
Definition at line 171 of file AgentPairMobility.cc.
{
     this->relativeSpeedY = relativeSpeedY;
 }
References relativeSpeedY.
updateAgentPairMobility()
void veins::AgentPairMobility::updateAgentPairMobility ()
Parameters
Definition at line 67 of file AgentPairMobility.cc.
 {
     this->lastDistancelr = this->distancelr;
     this->calcDistance();
     this->calcRelativeSpeed();
 }
References calcDistance(), calcRelativeSpeed(), distancelr, and lastDistancelr.
Referenced by veins::AgentPair::updateAgentPair().
Member Data Documentation
c
AgentPair* veins::AgentPairMobility::c private
relative speed between l and r
Definition at line 39 of file AgentPairMobility.h.
Referenced by AgentPairMobility(), calcDistance(), calcRelativeSpeed(), getC(), and setC().
distancelr
double veins::AgentPairMobility::distancelr private
Definition at line 68 of file AgentPairMobility.h.
Referenced by AgentPairMobility(), calcDistance(), getDistancelr(), info(), infoTrace(), and updateAgentPairMobility().
distancelrAngleRad
double veins::AgentPairMobility::distancelrAngleRad private
Definition at line 63 of file AgentPairMobility.h.
Referenced by calcDistance(), getDistancelrAngleRad(), infoTrace(), and setDistancelrAngleRad().
distancelrX
double veins::AgentPairMobility::distancelrX private
Definition at line 73 of file AgentPairMobility.h.
Referenced by calcDistance(), getDistancelrX(), and infoTrace().
distancelrY
double veins::AgentPairMobility::distancelrY private
Definition at line 78 of file AgentPairMobility.h.
Referenced by calcDistance(), getDistancelrY(), and infoTrace().
distancelrZ
double veins::AgentPairMobility::distancelrZ private
Definition at line 83 of file AgentPairMobility.h.
Referenced by calcDistance().
lastDistancelr
double veins::AgentPairMobility::lastDistancelr private
Definition at line 87 of file AgentPairMobility.h.
Referenced by AgentPairMobility(), getLastDistancelr(), setLastDistancelr(), and updateAgentPairMobility().
maxAngleRelativeSpeed
double veins::AgentPairMobility::maxAngleRelativeSpeed private
Definition at line 98 of file AgentPairMobility.h.
Referenced by calcRelativeSpeed(), getMaxAngleRelativeSpeed(), and setMaxAngleRelativeSpeed().
maxRelativeSpeed
double veins::AgentPairMobility::maxRelativeSpeed private
Definition at line 95 of file AgentPairMobility.h.
Referenced by calcRelativeSpeed(), getMaxRelativeSpeed(), and setMaxRelativeSpeed().
relativeSpeed
double veins::AgentPairMobility::relativeSpeed private
relative speed between l and r
Definition at line 43 of file AgentPairMobility.h.
Referenced by calcRelativeSpeed(), getRelativeSpeed(), info(), infoTrace(), and setRelativeSpeed().
relativeSpeedAngleRad
double veins::AgentPairMobility::relativeSpeedAngleRad private
relative speed angle between l and r
Definition at line 58 of file AgentPairMobility.h.
Referenced by calcRelativeSpeed(), getRelativeSpeedAngle(), getRelativeSpeedAngleRad(), infoTrace(), and setRelativeSpeedAngleRad().
relativeSpeedX
double veins::AgentPairMobility::relativeSpeedX private
X relative speed between l and r.
Definition at line 48 of file AgentPairMobility.h.
Referenced by calcRelativeSpeed(), getRelativeSpeedX(), infoTrace(), and setRelativeSpeedX().
relativeSpeedY
double veins::AgentPairMobility::relativeSpeedY private
Y relative speed between l and r.
Definition at line 53 of file AgentPairMobility.h.
Referenced by calcRelativeSpeed(), getRelativeSpeedY(), infoTrace(), and setRelativeSpeedY().
The documentation for this class was generated from the following files:
AgentPairMobility.h
AgentPairMobility.cc