My Project: veins::IcarRouting
veins::IcarRouting
#include <IcarRouting.h>
Public Member Functions
IcarRouting ()
ForwardingNode * selectForwardingNode ()
virtual ~IcarRouting ()
IcarRouting (RemoteAgentGroup *pGroupAgent, AgentPairList *pAgentPairList)
AgentPair * verifyAgentPairContext (int64_t pSource, int64_t pDestination, string rule, double msgTTime)
bool verifyAgentPairContext (AgentPair *c, double msgTTime)
AgentPair * verifyAgentPairRoute (int64_t pSource, int64_t pDestination, double msgTTime)
ForwardingNode * getFowardNode (int64_t destinationId, int64_t sourceId, int64_t localId, double msgTimeToLive, Coord target1, Coord target2)
Private Attributes
AgentPairList * agentPairList
int64_t destinationId
int64_t sourceId
double msgTimeToLive
Coord target1
Coord target2
double validityTime
RemoteAgentGroup * groupAgent
double userMessageLifeTime
double expectedConfidence
Detailed Description
Definition at line 25 of file IcarRouting.h.
Constructor & Destructor Documentation
IcarRouting() [1/2]
veins::IcarRouting::IcarRouting ()
Definition at line 27 of file IcarRouting.cc.
{
     // TODO Auto-generated constructor stub
 }
~IcarRouting()
veins::IcarRouting::~IcarRouting () virtual
Definition at line 31 of file IcarRouting.cc.
{
     // TODO Auto-generated destructor stub
 }
IcarRouting() [2/2]
veins::IcarRouting::IcarRouting (RemoteAgentGroup * pGroupAgent, AgentPairList * pAgentPairList)
Definition at line 20 of file IcarRouting.cc.
{
     // TODO Auto-generated constructor stub
     this->agentPairList = pAgentPairList;
     this->groupAgent = pGroupAgent;
 }
References agentPairList, and groupAgent.
Member Function Documentation
getFowardNode()
ForwardingNode * veins::IcarRouting::getFowardNode (int64_t destinationId, int64_t sourceId, int64_t localId, double msgTimeToLive, Coord target1, Coord target2)
Definition at line 113 of file IcarRouting.cc.
{
         Agent * fowardingAgent;
         ForwardingNode* fw=NULL;
         AgentPair * c = verifyAgentPairContext(sourceId, destinationId, "teste", msgTimeToLive);
         if (c!=NULL){
             if (c->getAgentS()->getId()==localId ){
                 fowardingAgent = c->getAgentD();
             }else fowardingAgent = c->getAgentS();
             fw = new ForwardingNode();
             fw->update("teste", fowardingAgent, c, 0);
         }
         return fw;
 }
References destinationId, veins::AgentPair::getAgentD(), veins::AgentPair::getAgentS(), veins::Agent::getId(), msgTimeToLive, sourceId, veins::ForwardingNode::update(), and verifyAgentPairContext().
selectForwardingNode()
ForwardingNode* veins::IcarRouting::selectForwardingNode ()
verifyAgentPairContext() [1/2]
bool veins::IcarRouting::verifyAgentPairContext (AgentPair * c, double msgTTime)
Definition at line 70 of file IcarRouting.cc.
 {
     bool resp = false;
     if (c!=NULL)
     {
         //verify the communication state and if is neighbor
         if ((c->getCommnunicationState()!= CommState::noCommunicating
                 && c->getCommnunicationState()!= CommState::faulty)
                 && ( simTime() + c->getMessageTTime()).dbl() <= msgTimeToLive)
             {
                 resp = true;
             }
      }
     return resp;
 }
References CommState::faulty, veins::AgentPair::getCommnunicationState(), veins::AgentPair::getMessageTTime(), msgTimeToLive, and CommState::noCommunicating.
verifyAgentPairContext() [2/2]
AgentPair * veins::IcarRouting::verifyAgentPairContext (int64_t pSource, int64_t pDestination, string rule, double msgTTime)
Definition at line 91 of file IcarRouting.cc.
 {
     AgentPair * resp = NULL;
     AgentPair *  c;
     if (pDestination!=-1)
         c = agentPairList->getAgentPair(pSource, pDestination);
     if (c!=NULL)
     {
         //verify the communication state and if is neighbor
             if ((c->getCommnunicationState()!= CommState::noCommunicating
                     && c->getCommnunicationState()!= CommState::faulty))
                     //&& c->isNeighbors() && ( simTime() + c->getMessageTTime()).dbl() <= msgTimeToLive)
                 {
                     resp = c;
                 }
         }
     return resp;
 }
References agentPairList, CommState::faulty, veins::AgentPairList::getAgentPair(), veins::AgentPair::getCommnunicationState(), and CommState::noCommunicating.
Referenced by getFowardNode(), and verifyAgentPairRoute().
verifyAgentPairRoute()
AgentPair * veins::IcarRouting::verifyAgentPairRoute (int64_t pSource, int64_t pDestination, double msgTTime)
Definition at line 38 of file IcarRouting.cc.
 {
     AgentPair *  pair= NULL;;
     AgentPair * c = this->agentPairList->getAgentPair(pSource, pDestination);
     c = agentPairList->getAgentPair(pSource, pDestination);
     if (c!=NULL)
       {
         bool answer=false;
         unsigned int i=0;
         while (i < c->pairRoutes.size() && !answer)
                 {
                     ICarRoute * wRoute =  c->pairRoutes.at(i);
                     if (wRoute->qocValidityTime > simTime()) {
                             answer=verifyAgentPairContext( wRoute->routeAgentPairs.at(0), msgTTime);
                             if (answer)
                                 pair = wRoute->routeAgentPairs.at(0);
                     }
                     i++;
                 }
       }
     return pair;
 }
References agentPairList, veins::AgentPairList::getAgentPair(), veins::AgentPair::pairRoutes, veins::ICarRoute::qocValidityTime, veins::ICarRoute::routeAgentPairs, and verifyAgentPairContext().
Member Data Documentation
agentPairList
AgentPairList* veins::IcarRouting::agentPairList private
Definition at line 27 of file IcarRouting.h.
Referenced by IcarRouting(), verifyAgentPairContext(), and verifyAgentPairRoute().
destinationId
int64_t veins::IcarRouting::destinationId private
Definition at line 28 of file IcarRouting.h.
Referenced by getFowardNode().
expectedConfidence
double veins::IcarRouting::expectedConfidence private
Definition at line 36 of file IcarRouting.h.
groupAgent
RemoteAgentGroup* veins::IcarRouting::groupAgent private
Definition at line 34 of file IcarRouting.h.
Referenced by IcarRouting().
msgTimeToLive
double veins::IcarRouting::msgTimeToLive private
Definition at line 30 of file IcarRouting.h.
Referenced by getFowardNode(), and verifyAgentPairContext().
sourceId
int64_t veins::IcarRouting::sourceId private
Definition at line 29 of file IcarRouting.h.
Referenced by getFowardNode().
target1
Coord veins::IcarRouting::target1 private
Definition at line 31 of file IcarRouting.h.
target2
Coord veins::IcarRouting::target2 private
Definition at line 32 of file IcarRouting.h.
userMessageLifeTime
double veins::IcarRouting::userMessageLifeTime private
Definition at line 35 of file IcarRouting.h.
validityTime
double veins::IcarRouting::validityTime private
Definition at line 33 of file IcarRouting.h.
The documentation for this class was generated from the following files:
IcarRouting.h
IcarRouting.cc