My Project: veins::Icarqoc
veins::Icarqoc
TODO - Generated class.
#include <Icarqoc.h>
Public Types
enum WaveApplMessageKinds {
SEND_ICM_EVT = 2 , SEND_MONITOR_EVT , SEND_ICAR_PROTOCOL , SEND_FORMATION_VEHIC ,
SEND_IMAGES_STREAMS , MEASURE_COMM_PERFORMANCE , AGENTPAIR_MONITOR_MESSAGE , COLLECT_MOBILITY
}
Public Types inherited from veins::BaseApplLayer
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Public Member Functions
virtual void sendDown (cMessage *msg)
virtual void initialize (int stage)
virtual void finish ()
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
void scheduleLoad (double appPeriod, int AppTypeId, string name, cMessage *m1)
std::string getMsgHeaderInfoTrace (ICMessage *wsm, std::string evento, bool header, simtime_t pEventTime)
void loadMonitor (cMessage *msg)
void scheduleLoadMobility ()
bool verifyRuleRadiusSet (ICRMessage *wsm)
void loadApp (cMessage *msg)
void addLostMsgAmount ()
double calcDelaySendLoadApp ()
std::string msgInfoTraceTransmitting (ICMessage *wsm, std::string event, std::string ruleRoute, bool header, simtime_t eventTime)
LocalAgent * getMyData ()
void setMyData (LocalAgent *myData)
long getLostMsgAmount ()
Public Member Functions inherited from veins::BaseApplLayer
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
void initialize (int) override
Initialization of the module and some variables.
Public Member Functions inherited from veins::BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
~BaseLayer () override
void initialize (int) override
Initialization of the module and some variables.
void handleMessage (cMessage *) override
Called every time a message arrives.
void finish () override
Called when the simulation has finished.
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Public Attributes
IcarContext * oIcarContext
MessageManager * oMsgManager
std::stringstream dataNetwork
long seqMsg
KnownGlobal * oKnownGlobal
CommState constanceValues
double loadPeriodApp
long lostMsgAmount
int64_t tempNode
long vehicleAmout
double perforMesurementPeriod
cMessage * monitorMsg
GeneralCommunicationService vfs
IcarContext * oVision
LocalAgent * myData
TraCIScenarioManager * managerx
std::stringstream dataMsgTeste
fstream fileNetwork
TraCICommandInterface * traciComm
TraCICommandInterface::Vehicle * traciVehicle
TraCICommandInterface::Lane * laneTraci
double tempLoadPeriodMonitor
cMessage * msgCollectMobility
bool integratedScenario
double loadPeriodMonitor
Protected Member Functions
void handleLowerMsg (cMessage *wsm) override
void handleSelfMsg (cMessage *msg) override
ICMessage * prepareWSM (int lengthBits, AgentPair agentPair, int priority)
void sendMessageApplication (ForwardingNode *fowardNode, int64_t destination, double timetoLiveApp, unsigned int pMsgType, int64_t lastNodeNext, int64_t lastNextNodeRequestMsg)
void sendForwardMessage (ICMessage *pWsm)
void changeLocalMobility ()
void createVehicleTraces ()
Protected Member Functions inherited from veins::BaseApplLayer
void handleLowerControl (cMessage *msg) override
Handle control messages from lower layer.
void handleUpperMsg (cMessage *msg) override
Handle messages from upper layer.
void handleUpperControl (cMessage *msg) override
Handle control messages from upper layer.
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
Protected Member Functions inherited from veins::BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
LocalMobility * locality
TraCIMobility * mobility
Protected Attributes inherited from veins::BaseApplLayer
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from veins::BaseLayer
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
PassedMessage * passedMsg
The last message passed through this layer.
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Static Protected Attributes
static const simsignal_t mobilityStateChangedSignal
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Additional Inherited Members
Static Public Attributes inherited from veins::BaseLayer
static const simsignal_t catPacketSignal = registerSignal("org_car2x_veins_modules_utility_packet")
SignalID for packets.
static const simsignal_t catPassedMsgSignal = registerSignal("org_car2x_veins_base_utils_passedmsg")
Signal for passed messages.
static const simsignal_t catDroppedPacketSignal = registerSignal("org_car2x_veins_modules_utility_droppedpacket")
Signal for dropped packets.
Detailed Description
TODO - Generated class.
Definition at line 59 of file Icarqoc.h.
Member Enumeration Documentation
WaveApplMessageKinds
enum veins::Icarqoc::WaveApplMessageKinds
Enumerator
SEND_ICM_EVT
SEND_MONITOR_EVT
SEND_ICAR_PROTOCOL
SEND_FORMATION_VEHIC
SEND_IMAGES_STREAMS
MEASURE_COMM_PERFORMANCE
AGENTPAIR_MONITOR_MESSAGE
COLLECT_MOBILITY
Definition at line 106 of file Icarqoc.h.
{
                      SEND_ICM_EVT = 2,
                      SEND_MONITOR_EVT,
                      SEND_ICAR_PROTOCOL,
                      SEND_FORMATION_VEHIC,
                      SEND_IMAGES_STREAMS,
                      MEASURE_COMM_PERFORMANCE,
                      AGENTPAIR_MONITOR_MESSAGE,
                      COLLECT_MOBILITY
                      };
Member Function Documentation
addLostMsgAmount()
void veins::Icarqoc::addLostMsgAmount ()
Definition at line 443 of file Icarqoc.cc.
{
     ++lostMsgAmount;
 }
References lostMsgAmount.
Referenced by veins::MessageManager::sendICRMessage().
calcDelaySendLoadApp()
double veins::Icarqoc::calcDelaySendLoadApp ()
Definition at line 350 of file Icarqoc.cc.
 {
     return ((double(rand()%10)+1)/100);
 }
changeLocalMobility()
void veins::Icarqoc::changeLocalMobility () protected
Parameters
Definition at line 283 of file Icarqoc.cc.
{
         this->oIcarContext->changeLocalMobility();
 }
References veins::IcarContext::changeLocalMobility(), and oIcarContext.
Referenced by handleSelfMsg(), and receiveSignal().
createVehicleTraces()
void veins::Icarqoc::createVehicleTraces () protected
Definition at line 405 of file Icarqoc.cc.
{
     // trace message file
     stringstream nameFileMessage;
     string aux=this->oKnownGlobal->getFilePreFix(this->myData->getId()).str();
     nameFileMessage.str("");
     nameFileMessage << aux << "PairAgents.csv"  ;
     fstream fileChannels;
     fileChannels.open(nameFileMessage.str(), fstream::in | fstream::out | fstream::app);
     fileChannels << oIcarContext->textDataAgentPair(-1, new AgentPair(), true) << ";"  << std::endl << oVision->dataAgentPair.str();
 }
References veins::IcarContext::dataAgentPair, veins::KnownGlobal::getFilePreFix(), veins::Agent::getId(), myData, oIcarContext, oKnownGlobal, oVision, and veins::IcarContext::textDataAgentPair().
Referenced by finish().
finish()
void veins::Icarqoc::finish () virtual
Definition at line 417 of file Icarqoc.cc.
                      {
     cancelAndDelete(monitorMsg);
     createVehicleTraces();
     //oVision->dataCommPerformance.clear();
     oVision->dataCommPerformance << oKnownGlobal->observationNameFile << ";" << simTime()<<";" << this->myData->getId()<< ";"<< this->myData->getLocalCommInfo()->getLocalAgentCommPerformance()->infoTrace(false, "") << std::endl;
     //oVision->dataMinslr << oVision->getAgentPairList()->infoTraceAgentPairList();
     this->oKnownGlobal->fileChannelsMinslr << ";" << myData->getId() <<  oVision->getAgentPairList()->infoTraceAgentPairList();;
     this->oKnownGlobal->knownVehicles.at(myData->getId())=NULL;
     this->oKnownGlobal->fileMessages << dataNetwork.str();
     this->oKnownGlobal->fileChannels << oVision->dataAgentPair.str();
     this->oKnownGlobal->fileRemoteAgents << oVision->dataRemoteAgent.str();
     this->oKnownGlobal->fileLocalAgents << this->myData->infoTrace(false, std::to_string(this->myData->getId())) << endl;
     this->oKnownGlobal->fileCommPerformance << oVision->dataCommPerformance.str();
     this->oKnownGlobal->fileReceivedMessages << dataMsgTeste.str();
 }
References createVehicleTraces(), veins::IcarContext::dataAgentPair, veins::IcarContext::dataCommPerformance, dataMsgTeste, dataNetwork, veins::IcarContext::dataRemoteAgent, veins::KnownGlobal::fileChannels, veins::KnownGlobal::fileChannelsMinslr, veins::KnownGlobal::fileCommPerformance, veins::KnownGlobal::fileLocalAgents, veins::KnownGlobal::fileMessages, veins::KnownGlobal::fileReceivedMessages, veins::KnownGlobal::fileRemoteAgents, veins::IcarContext::getAgentPairList(), veins::Agent::getId(), veins::LocalCommInfo::getLocalAgentCommPerformance(), veins::LocalAgent::getLocalCommInfo(), veins::LocalAgent::infoTrace(), LocalAgentCommPerformance::infoTrace(), veins::AgentPairList::infoTraceAgentPairList(), veins::KnownGlobal::knownVehicles, monitorMsg, myData, veins::KnownGlobal::observationNameFile, oKnownGlobal, and oVision.
getLostMsgAmount()
long veins::Icarqoc::getLostMsgAmount ()
Definition at line 447 of file Icarqoc.cc.
{
     return this->lostMsgAmount;
 }
References lostMsgAmount.
getMsgHeaderInfoTrace()
std::string veins::Icarqoc::getMsgHeaderInfoTrace (ICMessage * wsm, std::string evento, bool header, simtime_t pEventTime)
getMyData()
LocalAgent * veins::Icarqoc::getMyData ()
Definition at line 435 of file Icarqoc.cc.
{
     return myData;
 }
References myData.
handleLowerMsg()
void veins::Icarqoc::handleLowerMsg (cMessage * wsm) override protected virtual
Parameters
Reimplemented from veins::BaseApplLayer.
Definition at line 254 of file Icarqoc.cc.
 {
     //std::cout << endl << "begin receive network message "<< endl;
     BaseFrame1609_4* icm = dynamic_cast<BaseFrame1609_4 *>(msg);
         ASSERT(icm);
     ICRMessage * wsm=dynamic_cast<ICRMessage*>(icm);
     ASSERT(wsm);
     if (wsm != NULL)
     {
         //std::cout << endl << "begin update Context from message "<< wsm->detailedInfo() << endl;
         this->oIcarContext->updateContextfromMsg(wsm, simTime());
         //Nao e o local adequado
         //if (verifyRuleRadiusSet(wsm)) this->oIcarContext->updateContextfromMsg(wsm, simTime());
         this->dataMsgTeste  << this->oMsgManager->getMsgHeaderInfoTrace( wsm, "receiving", false, wsm->getTimestamp(), 4, this->myData->getId()) << std::endl;
         cancelAndDelete(wsm);
     } else {
         std::cout << " msg e null" << std::endl;
     }
     //std::cout << endl << "end receive network message "<< endl;
 }
References dataMsgTeste, veins::MessageManager::getMsgHeaderInfoTrace(), oIcarContext, oMsgManager, and veins::IcarContext::updateContextfromMsg().
handleSelfMsg()
void veins::Icarqoc::handleSelfMsg (cMessage * msg) override protected virtual
Parameters
Reimplemented from veins::BaseApplLayer.
Definition at line 169 of file Icarqoc.cc.
{
     //BaseWaveApplLayer::handleSelfMsg(msg);
     //this method is for self messages (mostly timers)
     //it is important to call the BaseWaveApplLayer function for BSM and WSM transmission
     //SEND_ICM_EVT, // general event of IC Message
     //SEND/-*--_ICAR_PROTOCOL, //Data dissemination
     //SEND_FORMATION_VEHIC, // vehicular formation
     //SEND_IMAGES_STREAMS // images streams
     //MEASURE_COMM_PERFORMANCE // event to measure the environment communication performance
     //AGENTPAIR_MONITOR_MESSAGE = For each knowed CHANNEL when need to update communication state (communicatin, non-communicating, fault etc.)
     // verify the simulation time.
     if (simTime().dbl() <= this->oKnownGlobal->finishSimulation)
     {
         switch (msg->getKind())
         {
             case MEASURE_COMM_PERFORMANCE:
             {
                 // calc performance measurement
                 //if (msg->getName()=="firstLoad") this->oVision->calcCommPerformVision(true);
                 //else this->oVision->calcCommPerformVision(false);
                 //schedule new performance measurement
                 //this->scheduleLoad(this->perforMesurementPeriod, MEASURE_COMM_PERFORMANCE, "commperform", msg);
             }break;
             case AGENTPAIR_MONITOR_MESSAGE:
             {
                 AgentPair * c = (AgentPair *)(msg->getContextPointer());
                 int64_t s = c->getAgentS()->getId();
                 int64_t d = c->getAgentD()->getId();
                 //oVision->updateCommunicationState(s,d);
             }break;
             case COLLECT_MOBILITY:
             {
                 //std::cout << endl << "begin schedule new  mobility collect "<< endl;
                 //schedule new  mobility collect
                 if (oKnownGlobal->mobilityPeriod == -1){
                     double  tempx = (double(rand()%100+1)/10)/2.5;
                     this->scheduleLoad(tempx, COLLECT_MOBILITY, "collectMobility", msg);
                     //std::cout << endl << "range Mobility= "<< tempx << endl;
                 }
                 if (oKnownGlobal->mobilityPeriod >0)
                     this->scheduleLoad(this->oKnownGlobal->mobilityPeriod, COLLECT_MOBILITY, "collectMobility", msg);
                 this->changeLocalMobility();
                 //std::cout << endl << "end schedule new  mobility collect "<< endl;
             }break;
             case SEND_MONITOR_EVT:
             {
                 //std::cout << endl << "begin send monitor message "<< endl;
                 //send monitor message
                 loadMonitor(msg);
                 //std::cout << endl << "end send monitor message "<< endl;
             }break;
             case SEND_ICM_EVT:
             {
                 //std::cout << endl << "begin send load Application message "<< endl;
                 loadApp(msg);
                 this->scheduleLoad(this->loadPeriodApp, SEND_ICM_EVT, "appMessage", msg);
                 //std::cout << endl << "end send load Application message "<< endl;
             }break;
            default:
             {
                 if (msg)
                     EV << "APP: Error: Got Self Message of unknown kind! Name: " << msg->getName() << endl;
             }break;
         }//end switchcase
     }//endif
 }
References AGENTPAIR_MONITOR_MESSAGE, changeLocalMobility(), COLLECT_MOBILITY, veins::KnownGlobal::finishSimulation, veins::AgentPair::getAgentD(), veins::AgentPair::getAgentS(), veins::Agent::getId(), loadApp(), loadMonitor(), loadPeriodApp, MEASURE_COMM_PERFORMANCE, veins::KnownGlobal::mobilityPeriod, oKnownGlobal, scheduleLoad(), SEND_ICM_EVT, and SEND_MONITOR_EVT.
initialize()
void veins::Icarqoc::initialize (int stage) virtual
Definition at line 23 of file Icarqoc.cc.
{
 BaseApplLayer::initialize(stage);
    if (stage == 0) {
        //Initializing members and pointers of your application goes here
         EV << "Initializing " << par("appName").stringValue() << std::endl;
        this->seqMsg=0;
        this->lostMsgAmount=0;
        this->tempNode=-1;
        if (FindModule<KnownGlobal*>::findGlobalModule())
        {
            oKnownGlobal = FindModule<KnownGlobal*>::findGlobalModule();
            double maxSpeed;
            if   (oKnownGlobal->knownVehicles.size() % 2 == 0)
                 maxSpeed = par("maxSpeedRoute1").doubleValue();
            else maxSpeed = par("maxSpeedRoute0").doubleValue();
            integratedScenario = par("integratedScenario").boolValue();
            //LocalMobility * locality = new LocalMobility(TraCIMobilityAccess().get(getParentModule()), maxSpeed);
            locality = NULL;
            mobility = NULL;
            if (FindModule<TraCIMobility*>::findSubModule(getParentModule())) {
                mobility = TraCIMobilityAccess().get(getParentModule());
                locality = new LocalMobility(mobility, maxSpeed);
                traciComm = mobility->getCommandInterface();
                traciVehicle = mobility->getVehicleCommandInterface();
            }
            //get configuration from physic layer module
            BasePhyLayer * x = FindModule<BasePhyLayer*>::findGlobalModule();
            oKnownGlobal->oRadiusEstimatorAgentPair->sensitivityPower_dbm = x->getAncestorPar("minPowerLevel").doubleValue();
            /*
            this->myData = new LocalAgent(idVeicularAgent, locality, aName.str());
            this->oIcarContext = new IcarContext(this->myData, this->oKnownGlobal, this);
            oMsgManager = new MessageManager(this);
            // temporario
            oVision = oIcarContext;
            oKnownGlobal->knownVehicles.push_back(this->oVision->getMyData());
           */
        } else exit(-1);
    }else
         if (stage == 1){
             int64_t idVeicularAgent = oKnownGlobal->knownVehicles.size();
             //agent name = vehicle creation order
             std::stringstream aName;
             aName << idVeicularAgent;
             this->myData = new LocalAgent(idVeicularAgent, locality, aName.str());
             //cout<<endl << "ID SUMO " << locality->getTraci()->getFullName() << "INDEX SUMO " << locality->getTraci()->getExternal_id();
             //declared radius in meters
             this->myData->setSetRadius(oKnownGlobal->setRadius);
             this->oIcarContext = new IcarContext(this->myData, this->oKnownGlobal, this);
             oMsgManager = new MessageManager(this);
             // temporary
             oVision = oIcarContext;
             oKnownGlobal->knownVehicles.push_back(this->oVision->getMyData());
             if (oKnownGlobal->knownVehicles.size()==1)
                 {
                 this->oKnownGlobal->fileLocalAgents << this->myData->infoTrace(true, std::to_string(this->myData->getId())) << endl;
                 this->dataMsgTeste  << this->oMsgManager->getMsgHeaderInfoTrace( NULL, "receiving", true, 0, 4, this->myData->getId()) << std::endl;
                 oVision->dataCommPerformance << "simulation;timeStamp; localId; " << this->myData->getLocalCommInfo()->getLocalAgentCommPerformance()->infoTrace(true, "") << std::endl;
                 AgentPair * tempAgentPair = new AgentPair();
                 this->oKnownGlobal->fileChannels << oIcarContext->textDataAgentPair(-1, tempAgentPair, true) << ";"  << std::endl;
                 this->oKnownGlobal->fileChannelsMinslr  << ";idLocal" << tempAgentPair->infoTrace(true) << ";" << endl;
                 dataNetwork << oMsgManager->getMsgHeaderInfoTrace( NULL,"", true, 0, 0, -1)<< std::endl;
                 }
               //schedule first to measure collect mobility
               if (oKnownGlobal->mobilityPeriod != 0){
                   cMessage *msgCollectMobility = new cMessage("collectMobility", COLLECT_MOBILITY);
                   scheduleLoad(oKnownGlobal->startSimulation, COLLECT_MOBILITY, "firstLoad", msgCollectMobility);
               }else{
                   findHost()->subscribe(BaseMobility::mobilityStateChangedSignal, this);
               }
               // period of communication performance measurement
               perforMesurementPeriod = oKnownGlobal->perforMesurementPeriod;
                //schedule first to measure communication performance
               //cMessage *msgPer = new cMessage("commperform", MEASURE_COMM_PERFORMANCE);
               //scheduleLoad(oKnownGlobal->startSimulation, MEASURE_COMM_PERFORMANCE, "firstLoad", msgPer);
               //schedule first load monitor message
               this->monitorMsg = new cMessage("firstLoad", SEND_MONITOR_EVT);
               this->loadPeriodMonitor = oKnownGlobal->monitorPeriod;
               scheduleAt((simTime().dbl()+oKnownGlobal->startSimulation+loadPeriodMonitor), monitorMsg);
               //scheduleLoad(, SEND_MONITOR_EVT, "firstLoad", this->monitorMsg);
               // vehicle amount
               vehicleAmout = oKnownGlobal->vehicleAmout;
               // general type of application
               this->vfs = oKnownGlobal->oGeneralCommunicationService;
               // period to send application messages
               loadPeriodApp = oKnownGlobal->oGeneralCommunicationService.appPeriodLoadMsg;
               //schedule first load application messages
               if (loadPeriodApp>0){
                   cMessage *msg = new cMessage("firstLoad", SEND_ICM_EVT);
                   scheduleAt((simTime().dbl()+oKnownGlobal->startSimulation+loadPeriodApp), msg);
               }
               //initialize trace
              // dataMsgTeste << ";amoutVehicle;loadPeriodApp;"
              //                   << msgInfoTraceTransmitting(NULL, "", "", true, 0) << std::endl;
              // if (oKnownGlobal->simulationDataheaderLine)
              //      dataNetwork << ";vehicleAmout;loadPeriodApp;" <<  msgInfoTraceTransmitting(NULL, "", "", true, 0)<< std::endl;
               //else dataNetwork << "";
               // get handle to phy layer
              // BaseMacLayer * macx= dynamic_cast<BaseMacLayer*>  (FindModule<Mac1609_4*>::findSubModule(getParentModule()));
              // ASSERT(macx);
               //DeciderResult80211 *macRes = dynamic_cast<DeciderResult80211 *>(PhyToMacControlInfo::getDeciderResult(m));
              // ASSERT(macRes);
              // if ((mac = FindModule<BaseMacLayer*>::findSubModule(getParentModule())) == nullptr) {
              //     throw cRuntimeError("Could not find a PHY module.");
              // }
               //cout << endl << "myMac " << macx->getMACAddress() << endl;
           }
         }
References veins::GeneralCommunicationService::appPeriodLoadMsg, COLLECT_MOBILITY, veins::IcarContext::dataCommPerformance, dataMsgTeste, dataNetwork, veins::KnownGlobal::fileChannels, veins::KnownGlobal::fileChannelsMinslr, veins::KnownGlobal::fileLocalAgents, veins::FindModule< T >::findGlobalModule(), veins::BaseModule::findHost(), veins::TraCIMobilityAccess::get(), veins::TraCIMobility::getCommandInterface(), veins::Agent::getId(), veins::LocalCommInfo::getLocalAgentCommPerformance(), veins::LocalAgent::getLocalCommInfo(), veins::MessageManager::getMsgHeaderInfoTrace(), veins::IcarContext::getMyData(), veins::TraCIMobility::getVehicleCommandInterface(), veins::AgentPair::infoTrace(), veins::LocalAgent::infoTrace(), LocalAgentCommPerformance::infoTrace(), veins::BaseApplLayer::initialize(), integratedScenario, veins::KnownGlobal::knownVehicles, loadPeriodApp, loadPeriodMonitor, locality, lostMsgAmount, mobility, veins::KnownGlobal::mobilityPeriod, veins::BaseMobility::mobilityStateChangedSignal, monitorMsg, veins::KnownGlobal::monitorPeriod, msgCollectMobility, myData, veins::KnownGlobal::oGeneralCommunicationService, oIcarContext, oKnownGlobal, oMsgManager, veins::KnownGlobal::oRadiusEstimatorAgentPair, oVision, perforMesurementPeriod, veins::KnownGlobal::perforMesurementPeriod, scheduleLoad(), SEND_ICM_EVT, SEND_MONITOR_EVT, RadiusEstimatorAgentPair::sensitivityPower_dbm, seqMsg, veins::KnownGlobal::setRadius, veins::Agent::setSetRadius(), veins::KnownGlobal::startSimulation, tempNode, veins::IcarContext::textDataAgentPair(), traciComm, traciVehicle, vehicleAmout, veins::KnownGlobal::vehicleAmout, and vfs.
loadApp()
void veins::Icarqoc::loadApp (cMessage * msg)
Definition at line 291 of file Icarqoc.cc.
 {
     //int64_t destinyNode;
     //ForwardingNode * foward = new ForwardingNode();
     oMsgManager->sendIcarMessageService(-1, -1, -1, vfs.timeToLive, msg->getKind());
     this->scheduleLoad(this->loadPeriodMonitor, SEND_MONITOR_EVT, "monitorMessage", this->monitorMsg);
 }
References loadPeriodMonitor, monitorMsg, oMsgManager, scheduleLoad(), SEND_MONITOR_EVT, veins::MessageManager::sendIcarMessageService(), veins::GeneralCommunicationService::timeToLive, and vfs.
Referenced by handleSelfMsg().
loadMonitor()
void veins::Icarqoc::loadMonitor (cMessage * msg)
Definition at line 303 of file Icarqoc.cc.
 {
     //int64_t destinyNode=-1;
     if (msg->getKind()==SEND_MONITOR_EVT)
     {
         //ForwardingNode * foward = new ForwardingNode();
         oMsgManager->sendIcarMessageService(-1, -1, -1, vfs.timeToLive, msg->getKind());
         if (this->oKnownGlobal->monitorPeriod == 0)
         {
             this->loadPeriodMonitor = (1.5 * (double(rand()%100)+1)/100) + 0.5;
         }
         this->scheduleLoad(this->loadPeriodMonitor, SEND_MONITOR_EVT, "monitorMessage", this->monitorMsg);
     }
 }
References loadPeriodMonitor, monitorMsg, veins::KnownGlobal::monitorPeriod, oKnownGlobal, oMsgManager, scheduleLoad(), SEND_MONITOR_EVT, veins::MessageManager::sendIcarMessageService(), veins::GeneralCommunicationService::timeToLive, and vfs.
Referenced by handleSelfMsg().
msgInfoTraceTransmitting()
std::string veins::Icarqoc::msgInfoTraceTransmitting (ICMessage * wsm, std::string event, std::string ruleRoute, bool header, simtime_t eventTime)
Parameters
prepareWSM()
ICMessage* veins::Icarqoc::prepareWSM (int lengthBits, AgentPair agentPair, int priority) protected
Parameters
receiveSignal()
void veins::Icarqoc::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override
Definition at line 387 of file Icarqoc.cc.
 {
     Enter_Method_Silent();
     if (signalID == BaseMobility::mobilityStateChangedSignal) {
         if (oKnownGlobal->mobilityPeriod == 0) this->changeLocalMobility();
     }
 }
References changeLocalMobility(), veins::KnownGlobal::mobilityPeriod, veins::BaseMobility::mobilityStateChangedSignal, and oKnownGlobal.
scheduleLoad()
void veins::Icarqoc::scheduleLoad (double appPeriod, int AppTypeId, string name, cMessage * m1)
Definition at line 321 of file Icarqoc.cc.
 {
     if (m1->isScheduled())
         cancelEvent(m1);
     m1->setName(name.c_str());
     m1->setKind(AppTypeId);
     simtime_t s = ((simtime_t) (simTime().dbl() + appPeriod));
     scheduleAt(s, m1);
 }
Referenced by handleSelfMsg(), initialize(), loadApp(), and loadMonitor().
scheduleLoadMobility()
void veins::Icarqoc::scheduleLoadMobility ()
Definition at line 334 of file Icarqoc.cc.
 {
     if (this->msgCollectMobility->isScheduled())
         cancelEvent(msgCollectMobility);
     msgCollectMobility->setName("collectMobility");
     msgCollectMobility->setKind(COLLECT_MOBILITY);
     simtime_t s = ((simtime_t) (simTime().dbl() + this->oKnownGlobal->mobilityPeriod));
     scheduleAt(s, msgCollectMobility);
 }
References COLLECT_MOBILITY, veins::KnownGlobal::mobilityPeriod, msgCollectMobility, and oKnownGlobal.
sendDown()
void veins::Icarqoc::sendDown (cMessage * msg) virtual
Parameters
Definition at line 373 of file Icarqoc.cc.
 {
     BaseApplLayer::sendDown(msg);
 }
References veins::BaseLayer::sendDown().
Referenced by veins::MessageManager::sendICRMessage().
sendForwardMessage()
void veins::Icarqoc::sendForwardMessage (ICMessage * pWsm) protected
Parameters
Definition at line 398 of file Icarqoc.cc.
 {
 }
sendMessageApplication()
void veins::Icarqoc::sendMessageApplication (ForwardingNode * fowardNode, int64_t destination, double timetoLiveApp, unsigned int pMsgType, int64_t lastNodeNext, int64_t lastNextNodeRequestMsg) protected
Parameters
setMyData()
void veins::Icarqoc::setMyData (LocalAgent * myData)
Definition at line 439 of file Icarqoc.cc.
{
     this->myData = myData;
 }
References myData.
verifyRuleRadiusSet()
bool veins::Icarqoc::verifyRuleRadiusSet (ICRMessage * wsm)
Definition at line 358 of file Icarqoc.cc.
{
     // when the radius of a node has a value on configuration (for example radiusSet=250m)
     double measuredDistance =0;
     measuredDistance = this->oIcarContext->oKnownGlobal->calcTraciDistanceMobility(wsm->getTransmissorNode().nodeId, this->oIcarContext->myData->getId());
     if (measuredDistance <= this->oIcarContext->myData->getSetRadius() && this->oIcarContext->myData->getSetRadius()>0)
         return true;
     else
     {
         if (this->oIcarContext->myData->getSetRadius()<=0) return true;
         else return false;
     }
 }
References veins::KnownGlobal::calcTraciDistanceMobility(), veins::Agent::getSetRadius(), veins::IcarContext::myData, oIcarContext, and veins::IcarContext::oKnownGlobal.
Member Data Documentation
constanceValues
CommState veins::Icarqoc::constanceValues
Definition at line 82 of file Icarqoc.h.
dataMsgTeste
std::stringstream veins::Icarqoc::dataMsgTeste
Definition at line 100 of file Icarqoc.h.
Referenced by finish(), handleLowerMsg(), and initialize().
dataNetwork
std::stringstream veins::Icarqoc::dataNetwork
Definition at line 63 of file Icarqoc.h.
Referenced by finish(), initialize(), and veins::MessageManager::sendICRMessage().
fileNetwork
fstream veins::Icarqoc::fileNetwork
Definition at line 103 of file Icarqoc.h.
integratedScenario
bool veins::Icarqoc::integratedScenario
Definition at line 124 of file Icarqoc.h.
Referenced by initialize().
laneTraci
TraCICommandInterface::Lane* veins::Icarqoc::laneTraci
Definition at line 120 of file Icarqoc.h.
loadPeriodApp
double veins::Icarqoc::loadPeriodApp
Definition at line 83 of file Icarqoc.h.
Referenced by handleSelfMsg(), and initialize().
loadPeriodMonitor
double veins::Icarqoc::loadPeriodMonitor
Definition at line 125 of file Icarqoc.h.
Referenced by initialize(), loadApp(), loadMonitor(), and veins::IcarContext::textDataAgentPair().
locality
LocalMobility* veins::Icarqoc::locality protected
Definition at line 78 of file Icarqoc.h.
Referenced by initialize().
lostMsgAmount
long veins::Icarqoc::lostMsgAmount
Definition at line 85 of file Icarqoc.h.
Referenced by addLostMsgAmount(), getLostMsgAmount(), initialize(), and veins::MessageManager::sendICRMessage().
managerx
TraCIScenarioManager* veins::Icarqoc::managerx
Definition at line 95 of file Icarqoc.h.
mobility
TraCIMobility* veins::Icarqoc::mobility protected
Definition at line 79 of file Icarqoc.h.
Referenced by initialize().
mobilityStateChangedSignal
const simsignal_t veins::Icarqoc::mobilityStateChangedSignal static protected
Definition at line 77 of file Icarqoc.h.
monitorMsg
cMessage* veins::Icarqoc::monitorMsg
Definition at line 90 of file Icarqoc.h.
Referenced by finish(), initialize(), loadApp(), and loadMonitor().
msgCollectMobility
cMessage* veins::Icarqoc::msgCollectMobility
Definition at line 123 of file Icarqoc.h.
Referenced by initialize(), and scheduleLoadMobility().
myData
LocalAgent* veins::Icarqoc::myData
Definition at line 94 of file Icarqoc.h.
Referenced by createVehicleTraces(), finish(), getMyData(), initialize(), and setMyData().
oIcarContext
IcarContext* veins::Icarqoc::oIcarContext
Definition at line 61 of file Icarqoc.h.
Referenced by changeLocalMobility(), createVehicleTraces(), handleLowerMsg(), initialize(), veins::MessageManager::sendIcarMessageService(), veins::MessageManager::sendICRMessage(), and verifyRuleRadiusSet().
oKnownGlobal
KnownGlobal* veins::Icarqoc::oKnownGlobal
Definition at line 65 of file Icarqoc.h.
Referenced by createVehicleTraces(), finish(), handleSelfMsg(), initialize(), loadMonitor(), receiveSignal(), scheduleLoadMobility(), and veins::MessageManager::sendICRMessage().
oMsgManager
MessageManager* veins::Icarqoc::oMsgManager
Definition at line 62 of file Icarqoc.h.
Referenced by handleLowerMsg(), initialize(), loadApp(), and loadMonitor().
oVision
IcarContext* veins::Icarqoc::oVision
Definition at line 92 of file Icarqoc.h.
Referenced by createVehicleTraces(), finish(), and initialize().
perforMesurementPeriod
double veins::Icarqoc::perforMesurementPeriod
Definition at line 89 of file Icarqoc.h.
Referenced by initialize().
seqMsg
long veins::Icarqoc::seqMsg
Definition at line 64 of file Icarqoc.h.
Referenced by initialize(), veins::MessageManager::sendIcarMessageService(), and veins::MessageManager::sendICRMessage().
tempLoadPeriodMonitor
double veins::Icarqoc::tempLoadPeriodMonitor
Definition at line 122 of file Icarqoc.h.
tempNode
int64_t veins::Icarqoc::tempNode
Definition at line 87 of file Icarqoc.h.
Referenced by initialize().
traciComm
TraCICommandInterface* veins::Icarqoc::traciComm
Definition at line 118 of file Icarqoc.h.
Referenced by initialize().
traciVehicle
TraCICommandInterface::Vehicle* veins::Icarqoc::traciVehicle
Definition at line 119 of file Icarqoc.h.
Referenced by initialize().
vehicleAmout
long veins::Icarqoc::vehicleAmout
Definition at line 88 of file Icarqoc.h.
Referenced by initialize().
vfs
GeneralCommunicationService veins::Icarqoc::vfs
Definition at line 91 of file Icarqoc.h.
Referenced by initialize(), loadApp(), and loadMonitor().
The documentation for this class was generated from the following files:
Icarqoc.h
Icarqoc.cc