My Project: veins::RemoteAgentCommInfo
veins::RemoteAgentCommInfo
#include <RemoteAgentCommInfo.h>
Public Member Functions
RemoteAgentCommInfo ()
virtual ~RemoteAgentCommInfo ()
std::string info ()
std::string infoTrace (bool header, std::string idagent)
RemoteAgentCommPerformance * getRemoteAgentCommPerformance ()
Public Member Functions inherited from veins::CommInfo
CommInfo ()
virtual ~CommInfo ()
std::string info ()
std::string infoTrace (bool header, std::string idagent)
CommPerformance * getCommPerformance ()
void setCommPerformance (CommPerformance *commPerformance)
double getRadius ()
void setRadius (double radius)
double getSenseGhz ()
void setSenseGhz (double senseGhz)
Additional Inherited Members
Protected Attributes inherited from veins::CommInfo
double radius
double senseGHZ
CommPerformance * commPerformance
Detailed Description
Definition at line 24 of file RemoteAgentCommInfo.h.
Constructor & Destructor Documentation
RemoteAgentCommInfo()
veins::RemoteAgentCommInfo::RemoteAgentCommInfo ()
Definition at line 20 of file RemoteAgentCommInfo.cc.
{
     // TODO Auto-generated constructor stub
     this->commPerformance = new RemoteAgentCommPerformance();
     this->radius = 0;
     this->senseGHZ = 0;
 }
References veins::CommInfo::commPerformance, veins::CommInfo::radius, and veins::CommInfo::senseGHZ.
~RemoteAgentCommInfo()
veins::RemoteAgentCommInfo::~RemoteAgentCommInfo () virtual
Definition at line 31 of file RemoteAgentCommInfo.cc.
{
     // TODO Auto-generated destructor stub
 }
Member Function Documentation
getRemoteAgentCommPerformance()
RemoteAgentCommPerformance * veins::RemoteAgentCommInfo::getRemoteAgentCommPerformance ()
Definition at line 27 of file RemoteAgentCommInfo.cc.
{
     return (RemoteAgentCommPerformance *) this->commPerformance;
 }
References veins::CommInfo::commPerformance.
Referenced by veins::RemoteAgentGroup::calcRemoteAgentGroupCommPerform(), and info().
info()
std::string veins::RemoteAgentCommInfo::info ()
Definition at line 35 of file RemoteAgentCommInfo.cc.
{
     std::ostringstream ost;
     ost << CommInfo::info()
         << this->getRemoteAgentCommPerformance()->info();
     return ost.str();
 }
References getRemoteAgentCommPerformance(), veins::CommInfo::info(), and RemoteAgentCommPerformance::info().
Referenced by veins::RemoteAgent::info().
infoTrace()
std::string veins::RemoteAgentCommInfo::infoTrace (bool header = false, std::string idagent = "")
Definition at line 42 of file RemoteAgentCommInfo.cc.
{
     std::ostringstream ost;
      ost << CommInfo::infoTrace(header, idagent);
         //<< this->getRemoteAgentCommPerformance()->infoTrace(header, idagent);
     return ost.str();
 }
References veins::CommInfo::infoTrace().
Referenced by veins::RemoteAgent::infoTrace().
The documentation for this class was generated from the following files:
RemoteAgentCommInfo.h
RemoteAgentCommInfo.cc