Veins: veins::MessageManager Class Reference
veins::MessageManager Class Reference
#include <MessageManager.h>
Public Member Functions
MessageManager ()
MessageManager (Icarqoc *pIcarQoc)
virtual ~MessageManager ()
std::string getMsgHeaderInfoTrace (ICRMessage *wsm, std::string evento, bool header, simtime_t pEventTime, int maxNumberHop, int myDataID)
void sendICRMessage (ICRMessage *wsm, std::string evento, std::string ruleRoute)
double getMsgRecvSnr (ICRMessage *m)
double getMsgRecvPower_dBm (ICRMessage *m)
std::string getMsgHeaderInfoTraceNode (ICRNode pNode)
ICRMessage * sendIcarMessageService (int64_t sourceId, int64_t nextId, int64_t destination, double timetoLiveApp, unsigned int pMsgType)
const ICRNode prepareICRNode (Agent *a)
Public Attributes
ICRMessage * wsm
Icarqoc * oIcarQoc
vector< Agent * > agentRoute
Detailed Description
Definition at line 46 of file MessageManager.h.
Constructor & Destructor Documentation
MessageManager() [1/2]
veins::MessageManager::MessageManager ()
Definition at line 20 of file MessageManager.cc.
{
     // TODO Auto-generated constructor stub
 }
MessageManager() [2/2]
veins::MessageManager::MessageManager (Icarqoc * pIcarQoc)
Definition at line 24 of file MessageManager.cc.
{
     this->oIcarQoc = pIcarQoc;
    // this->oIcarQoc->dataNetwork << getMsgHeaderInfoTrace( wsm,"", true, 0, 32, -1)<< std::endl;
 }
References oIcarQoc.
~MessageManager()
veins::MessageManager::~MessageManager () virtual
Definition at line 29 of file MessageManager.cc.
{
     // TODO Auto-generated destructor stub
 }
Member Function Documentation
getMsgHeaderInfoTrace()
std::string veins::MessageManager::getMsgHeaderInfoTrace (ICRMessage * wsm, std::string evento, bool header, simtime_t pEventTime, int maxNumberHop, int myDataID)
Definition at line 129 of file MessageManager.cc.
 {
    // std::cout << endl << "getMsgHeaderInfoTrace" << "   timeX= " << simTime().dbl();
     std::ostringstream ost;
     if (header){
         ost      << ";event"
                  << ";eventTime"
                  << ";localNodeID"
                  << ";messageNumber"
                  << ";MsgType"
                  << ";MSG Time"
                  //<< ";delayMSG"
                  << ";MsgLifeTime"
                  << ";hopNumber"
                  << ";ValidityDataTimeStamp";
                  //<< ";Data";
                 for (int i=0; i < 4; i++)
                 {
                     ost  << ";nodeId_" << i  // source id node - 32bits
                     << ";posX"  //source x - 32 bits
                     << ";posY" // source y - 32 bits
                     << ";posZ" // source z - 32 bits
                     << ";maxSpeed" // max speed node - 32 bits
                     << ";angle" // angulo do agente de origem -  32 bits
                     << ";aceleration"  // aceleracao do agente de origem -  32 bits
                     << ";speed"// speed value -  32 bits
                     << ";neighber" // vizinho do proximo no
                     << ";validityTimeToNext" // alcance do sinal de comunicacao do agente de origem  - 32 bits
                     << ";posTimeStamp" // timestamp da da coleta da posicao do agente antecessor
                     << ";msgTimeStamp";
                 }
     } else {
         ost     << ";" << evento
                 << ";" << pEventTime
                 << ";" << myDataID
                 << ";" << wsm->getNumMsg()
                  << ";" << wsm->getMsgType()
                 << ";" << wsm->getTimestamp()
                 //<< ";" << pEventTime - wsm->getTimestamp()
                 << ";" << wsm->getMsgLifeTime()
                 << ";" << wsm->getHopNumber()
                 << ";"<< wsm->getValidityDataTimeStamp()
                 //<< ";"<< wsm->getWsmData();
                 //<< ";"
                 //    << this->oKnownGlobal->calcTraciDistanceMobility(wsm->getRouteNodes(0).nodeId,
                 //            wsm->getRouteNodes(wsm->getRouteNodesArraySize()-1).nodeId);
                 <<  getMsgHeaderInfoTraceNode(wsm->getSourceNode())
                 <<  getMsgHeaderInfoTraceNode(wsm->getTransmissorNode())
                 <<  getMsgHeaderInfoTraceNode(wsm->getNextNode())
                 <<  getMsgHeaderInfoTraceNode(wsm->getDestinyNode());
     }
              return ost.str();
 }
References getMsgHeaderInfoTraceNode(), and wsm.
Referenced by veins::Icarqoc::handleLowerMsg(), veins::Icarqoc::initialize(), and sendICRMessage().
getMsgHeaderInfoTraceNode()
std::string veins::MessageManager::getMsgHeaderInfoTraceNode (ICRNode pNode)
Definition at line 189 of file MessageManager.cc.
 {
     std::ostringstream ost;
     ost  << ";" << pNode.nodeId  // source id node - 64bits
     << ";" << pNode.posX  //source x  32bits
     << ";" << pNode.posY // source y 32bits
     << ";" << pNode.posZ // source z - 64bits
     << ";" << pNode.maxSpeed // max speed node - 32 bits
     << ";" << pNode.angle // angulo do agente de origem -  32 bits
     << ";" << pNode.aceleration  // aceleracao do agente de origem -  32 bits
     << ";" << pNode.speed// speed value -  32 bits
     << ";" << pNode.neighber // vizinho do proximo no
     << ";" << pNode.validityTimeToNext // alcance do sinal de comunicacao do agente de origem  - 32 bits
     << ";" << pNode.posTimeStamp // timestamp da da coleta da posicao do agente antecessor
     << ";" << pNode.msgTimeStamp;
     return ost.str();
 }
References veins::ICRNode::aceleration, veins::ICRNode::angle, veins::ICRNode::maxSpeed, veins::ICRNode::msgTimeStamp, veins::ICRNode::neighber, veins::ICRNode::nodeId, veins::ICRNode::posTimeStamp, veins::ICRNode::posX, veins::ICRNode::posY, veins::ICRNode::posZ, veins::ICRNode::speed, and veins::ICRNode::validityTimeToNext.
Referenced by getMsgHeaderInfoTrace().
getMsgRecvPower_dBm()
double veins::MessageManager::getMsgRecvPower_dBm (ICRMessage * m)
Definition at line 34 of file MessageManager.cc.
{
     DeciderResult80211 *macRes = dynamic_cast<DeciderResult80211 *>(PhyToMacControlInfo::getDeciderResult(m));
     ASSERT(macRes);
     // TESTE PARA get the mac address  ainda nao resolvido...
     //PhyToMacControlInfo * x = new PhyToMacControlInfo(macRes);
     //cout << endl << "SourceAddress " << x->getSourceAddress() << endl;
     return macRes->getRecvPower_dBm();
 }
References veins::PhyToMacControlInfo::getDeciderResult(), and veins::DeciderResult80211::getRecvPower_dBm().
getMsgRecvSnr()
double veins::MessageManager::getMsgRecvSnr (ICRMessage * m)
Definition at line 44 of file MessageManager.cc.
{
     //std::cout << endl << "begin  Returns the signal to noise ratio of the transmission from message "<< endl;
     DeciderResult80211 *macRes = dynamic_cast<DeciderResult80211 *>(PhyToMacControlInfo::getDeciderResult(m));
     ASSERT(macRes);
     //std::cout << endl << "end  Returns the signal to noise ratio of the transmission from message " << macRes->getSnr() << endl;
     return macRes->getSnr();
 }
References veins::PhyToMacControlInfo::getDeciderResult(), and veins::DeciderResult80211::getSnr().
prepareICRNode()
const ICRNode veins::MessageManager::prepareICRNode (Agent * a)
Definition at line 209 of file MessageManager.cc.
{
     ICRNode node;
     node.initializeICRNode();
     if (a!=NULL){
         node.maxSpeed = a->getMobilityInfo()->getMaxSpeed();
         node.angle = a->getMobilityInfo()->getAngle();
         node.aceleration = a->getMobilityInfo()->getAcceleration();
         node.posTimeStamp = a->getMobilityInfo()->getActualMove()->getStartTime().dbl();
         node.speed = a->getMobilityInfo()->getActualMove()->getSpeed();
         node.posX = a->getMobilityInfo()->getActualMove()->getStartPos().x;
         node.posY = a->getMobilityInfo()->getActualMove()->getStartPos().y;
         node.posZ = a->getMobilityInfo()->getActualMove()->getStartPos().z;
         node.msgTimeStamp = simTime().dbl();
         node.nodeId = a->getId();
         node.validityTimeToNext = 0;
     }
     return node;
 }
References veins::ICRNode::aceleration, veins::ICRNode::angle, veins::MobilityInfo::getAcceleration(), veins::MobilityInfo::getActualMove(), veins::MobilityInfo::getAngle(), veins::Agent::getId(), veins::MobilityInfo::getMaxSpeed(), veins::Agent::getMobilityInfo(), veins::Move::getSpeed(), veins::Move::getStartPos(), veins::Move::getStartTime(), veins::ICRNode::initializeICRNode(), veins::ICRNode::maxSpeed, veins::ICRNode::msgTimeStamp, veins::ICRNode::nodeId, veins::ICRNode::posTimeStamp, veins::ICRNode::posX, veins::ICRNode::posY, veins::ICRNode::posZ, veins::ICRNode::speed, veins::ICRNode::validityTimeToNext, veins::Coord::x, veins::Coord::y, and veins::Coord::z.
Referenced by sendIcarMessageService().
sendIcarMessageService()
ICRMessage * veins::MessageManager::sendIcarMessageService (int64_t sourceId, int64_t nextId, int64_t destination, double timetoLiveApp, unsigned int pMsgType)
Definition at line 56 of file MessageManager.cc.
 {
      ICRMessage * wsm = NULL;
      wsm = new ICRMessage();
      //prepareing icmessage
      wsm->setMsgType(pMsgType);
      wsm->setNumMsg(++this->oIcarQoc->seqMsg);
      wsm->setName("data");
      //User priority with which this packet was sent (note the AC mapping rules in Mac1609_4::mapUserPriority)
      wsm->setUserPriority(7);
      //Unique number to identify the service
      wsm->setPsid(-1);
      //populateWSM(wsm);
      wsm->setKind(pMsgType);
      //Channel Number on which this packet was sent
      wsm->setChannelNumber(static_cast<int>(Channel::cch));
      wsm->setMsgLifeTime(simTime() + timetoLiveApp);
      wsm->setTimestamp(simTime());
      wsm->setHopNumber(1);
      wsm->setTransmissorNode(prepareICRNode(oIcarQoc->oIcarContext->myData));
      if (oIcarQoc->oIcarContext->myData->getId()==sourceId || sourceId==-1){
          wsm->setSourceNode(prepareICRNode(oIcarQoc->oIcarContext->myData));
      }else {
          wsm->setSourceNode(prepareICRNode(oIcarQoc->oIcarContext->agentGroup->getRemoteAgent(sourceId)));
      }
      wsm->setDestinyNode(prepareICRNode(oIcarQoc->oIcarContext->agentGroup->getRemoteAgent(destinationId)));
      wsm->setNextNode(prepareICRNode(oIcarQoc->oIcarContext->agentGroup->getRemoteAgent(nextId)));
      //sendown message
      sendICRMessage(wsm, "transmitting", "msgIcar");
      return(wsm);
 }
References veins::IcarContext::agentGroup, veins::cch, veins::Agent::getId(), veins::RemoteAgentGroup::getRemoteAgent(), veins::IcarContext::myData, veins::Icarqoc::oIcarContext, oIcarQoc, prepareICRNode(), sendICRMessage(), veins::Icarqoc::seqMsg, and wsm.
Referenced by veins::Icarqoc::loadApp(), and veins::Icarqoc::loadMonitor().
sendICRMessage()
void veins::MessageManager::sendICRMessage (ICRMessage * wsm, std::string evento, std::string ruleRoute)
Definition at line 102 of file MessageManager.cc.
 {
     int calcRang;
     if ((this->oIcarQoc->oKnownGlobal->maxMsgAmountVehicle >= this->oIcarQoc->seqMsg) )
     {
         calcRang = rand() % 2;
         if ((this->oIcarQoc->oIcarContext->oKnownGlobal->lostMessageRate!=0
                 && calcRang ==0
                 && (this->oIcarQoc->getLostMsgAmount()
                 <= (this->oIcarQoc->oKnownGlobal->lostMessageRate/100)*this->oIcarQoc->oKnownGlobal->maxMsgAmountVehicle)))
         {
             //emulating lost messages using parameter lostMessageRate
             this->oIcarQoc->addLostMsgAmount();
         }else {
             // sending message
             this->oIcarQoc->sendDown( ((cMessage*)(wsm)));
             this->oIcarQoc->dataNetwork  << this->getMsgHeaderInfoTrace( wsm,evento, false, wsm->getTimestamp(), 32, this->oIcarQoc->getMyData()->getId()) << std::endl;
             this->oIcarQoc->oIcarContext->getMyData()->getLocalCommInfo()->getLocalAgentCommPerformance()->addCorrectMsgTransmittedMsg();
         }
         std::cout  << "this->oIcarQoc->lostMsgAmount = " <<  this->oIcarQoc->lostMsgAmount <<
                 "oKnownGlobal->maxMsgAmountVehicle= " << this->oIcarQoc->oKnownGlobal->maxMsgAmountVehicle <<
                 "this->oIcarQoc->seqMsg = " << this->oIcarQoc->seqMsg << endl;
     }
 }
References LocalAgentCommPerformance::addCorrectMsgTransmittedMsg(), veins::Icarqoc::addLostMsgAmount(), veins::Icarqoc::dataNetwork, veins::LocalCommInfo::getLocalAgentCommPerformance(), veins::LocalAgent::getLocalCommInfo(), getMsgHeaderInfoTrace(), veins::IcarContext::getMyData(), veins::KnownGlobal::lostMessageRate, veins::Icarqoc::lostMsgAmount, veins::KnownGlobal::maxMsgAmountVehicle, veins::Icarqoc::oIcarContext, oIcarQoc, veins::IcarContext::oKnownGlobal, veins::Icarqoc::oKnownGlobal, veins::Icarqoc::sendDown(), veins::Icarqoc::seqMsg, and wsm.
Referenced by sendIcarMessageService().
Member Data Documentation
agentRoute
vector<Agent *> veins::MessageManager::agentRoute
Definition at line 58 of file MessageManager.h.
oIcarQoc
Icarqoc* veins::MessageManager::oIcarQoc
Definition at line 57 of file MessageManager.h.
Referenced by MessageManager(), sendIcarMessageService(), and sendICRMessage().
wsm
ICRMessage* veins::MessageManager::wsm
Definition at line 56 of file MessageManager.h.
Referenced by getMsgHeaderInfoTrace(), sendIcarMessageService(), and sendICRMessage().
The documentation for this class was generated from the following files:
MessageManager.h
MessageManager.cc