My Project: veins::MobilityInfo
veins::MobilityInfo
#include <MobilityInfo.h>
Public Member Functions
MobilityInfo ()
virtual ~MobilityInfo ()
std::string info ()
MobilityInfo (Move *mSrc)
virtual Move * getLastMove ()
float getMaxSpeed ()
Returns a string with the value of the coordinate.
void setMaxSpeed (float maxSpeed)
virtual double calcEuclideanDistanceAgentMoving ()
double calcEuclideanDistancelr (Coord l, Coord r)
virtual std::string moveInfoTrace (bool header)
Returns information about the current state.
std::string infoTrace (bool header, std::string idagent)
Returns information about the current state.
float getAcceleration ()
void setAcceleration (float acceleration)
Move * getActualMove ()
void setActualMove (Move *actualMove)
double getSensorPeriod ()
void setSensorPeriod (float sensorPeriod)
int getQuadrant (double angleRad)
float getAngle ()
Coord getPositionAtTime (simtime_t pTime)
void setAngle (float angle)
double getAge ()
void setAge (double age)
const Move * getCollectedMove ()
void setCollectedMove (Move *collectedMove)
Protected Member Functions
void setLastMove (Move *pMove)
void calcAcceleration ()
Protected Attributes
Move * actualMove = new Move()
current vehicle movement
Move * lastMove = new Move()
last vehicle movement before current position
Move * collectedMove = new Move()
collected vehicle movement
float maxSpeed =0
float sensorPeriod
float acceleration
float angle
double age
Detailed Description
Definition at line 29 of file MobilityInfo.h.
Constructor & Destructor Documentation
MobilityInfo() [1/2]
veins::MobilityInfo::MobilityInfo ()
Definition at line 20 of file MobilityInfo.cc.
{
     // TODO Auto-generated constructor stub
     //this->lastTime = 0.0;
     //this->maxSpeed = 0;
     //this->lastMove = new Move();
     //this->actualMove = new Move();
 }
~MobilityInfo()
veins::MobilityInfo::~MobilityInfo () virtual
Definition at line 46 of file MobilityInfo.cc.
{
     // TODO Auto-generated destructor stub
     //delete this;
 }
MobilityInfo() [2/2]
veins::MobilityInfo::MobilityInfo (Move * mSrc)
Definition at line 29 of file MobilityInfo.cc.
{
     // TODO Auto-generated constructor stub
     //this->lastTime = 0.0;
     this->lastMove = new Move();
     this->maxSpeed = 0;
     this->actualMove = mSrc;
 }
References actualMove, lastMove, and maxSpeed.
Member Function Documentation
calcAcceleration()
void veins::MobilityInfo::calcAcceleration () protected
Definition at line 228 of file MobilityInfo.cc.
 {
     if (this->actualMove->getSpeed()> -1 && this->lastMove->getSpeed()> -1)
     {
         this->sensorPeriod = (this->actualMove->getStartTime().dbl() - this->lastMove->getStartTime().dbl());
         //std::cout << endl << "mobility sensor delta T = " << sensorPeriod  << endl;
        if (sensorPeriod != 0)
            this->acceleration = (this->actualMove->getSpeed()- this->lastMove->getSpeed()) / sensorPeriod;
     }
     //std::cout << endl << "sensorPeriod = " << sensorPeriod;
 }
References acceleration, actualMove, veins::Move::getSpeed(), veins::Move::getStartTime(), lastMove, and sensorPeriod.
Referenced by veins::LocalMobility::updateLocalMobilityPos().
calcEuclideanDistanceAgentMoving()
double veins::MobilityInfo::calcEuclideanDistanceAgentMoving () virtual
Definition at line 88 of file MobilityInfo.cc.
{
     //std::cout << "calcEuclideanDistancelr  - lastPosition=" <<this->getLastPosition() <<  "    -- startPos=" << this->startPos << std::endl;
     return  calcEuclideanDistancelr(this->lastMove->getStartPos(), this->actualMove->getStartPos());
 }
References calcEuclideanDistancelr(), veins::Move::getStartPos(), and lastMove.
calcEuclideanDistancelr()
double veins::MobilityInfo::calcEuclideanDistancelr (Coord l, Coord r)
Definition at line 95 of file MobilityInfo.cc.
{
     return sqrt((r.x - l.x)*(r.x - l.x) + (r.y - l.y)*(r.y - l.y));
 }
References veins::Coord::x, and veins::Coord::y.
Referenced by calcEuclideanDistanceAgentMoving(), and veins::KnownGlobal::calcTraciDistanceMobility().
getAcceleration()
float veins::MobilityInfo::getAcceleration ()
Definition at line 52 of file MobilityInfo.cc.
{
     return acceleration;
 }
References acceleration.
Referenced by veins::MessageManager::prepareICRNode().
getActualMove()
Move * veins::MobilityInfo::getActualMove ()
Definition at line 60 of file MobilityInfo.cc.
{
     return actualMove;
 }
References actualMove.
Referenced by veins::AgentPairMobility::calcDistance(), veins::TimelinessAgentPair::calcLeicosseno(), veins::AgentPairList::calcMaxDistancelr(), veins::AgentPairList::calcMinDistancelr(), veins::AgentPairMobility::calcRelativeSpeed(), veins::IcarContext::changeLocalMobility(), veins::MessageManager::prepareICRNode(), and veins::RemoteAgent::updateRemoteAgent().
getAge()
double veins::MobilityInfo::getAge ()
Definition at line 245 of file MobilityInfo.cc.
{
     return age;
 }
References age.
getAngle()
float veins::MobilityInfo::getAngle ()
Definition at line 199 of file MobilityInfo.cc.
{
     return angle;
 }
References angle.
Referenced by veins::AgentPairMobility::calcRelativeSpeed(), veins::TimelinessAgentPair::calcValidityTeste(), and veins::MessageManager::prepareICRNode().
getCollectedMove()
const Move * veins::MobilityInfo::getCollectedMove ()
Definition at line 253 of file MobilityInfo.cc.
{
     return collectedMove;
 }
References collectedMove.
Referenced by veins::TimelinessAgentPair::calcAge().
getLastMove()
Move * veins::MobilityInfo::getLastMove () virtual
Reimplemented in veins::LocalMobility.
Definition at line 37 of file MobilityInfo.cc.
{
     return this->lastMove;
 }
References lastMove.
getMaxSpeed()
float veins::MobilityInfo::getMaxSpeed ()
Returns a string with the value of the coordinate.
Referenced by veins::AgentPairMobility::calcRelativeSpeed(), veins::TimelinessAgentPair::calcValidityTeste(), and veins::MessageManager::prepareICRNode().
getPositionAtTime()
Coord veins::MobilityInfo::getPositionAtTime (simtime_t pTime)
Definition at line 207 of file MobilityInfo.cc.
 {
     double dTime = pTime.dbl() - this->actualMove->getStartTime().dbl();
     //std::cout << endl << "diff time = " << dTime;
     if (dTime > 0)
     {
         double x = this->actualMove->getStartPos().x + this->actualMove->getSpeed()*cos(this->angle)*dTime +
                 (this->acceleration * dTime* dTime)/2;
         double y = this->actualMove->getStartPos().y + this->actualMove->getSpeed()*sin(this->angle)*dTime +
                 (this->acceleration * dTime* dTime)/2;
         //std::cout << endl << "aceleracao = " << this->acceleration << "   x=" << this->actualMove->getStartPosition().x << "   x.n=" << x <<  "    y=" << this->actualMove->getStartPosition().y << "   y.n=" << y;
         return Coord(x,y,this->actualMove->getStartPos().z);
     }else
         return (this->actualMove->getStartPos());
 }
References acceleration, actualMove, angle, veins::Move::getSpeed(), veins::Move::getStartPos(), veins::Move::getStartTime(), veins::Coord::x, veins::Coord::y, and veins::Coord::z.
Referenced by veins::AgentPair::setCalcRadius().
getQuadrant()
int veins::MobilityInfo::getQuadrant (double angleRad)
Definition at line 100 of file MobilityInfo.cc.
 {
     double anglec=oAngle;
     if (oAngle<0) anglec = 2*M_PI +oAngle;
     anglec = floor(anglec * 1000)/1000;
     int angleQuadrant = ceil(anglec/(M_PI/2));
     return angleQuadrant;
 }
References M_PI.
getSensorPeriod()
double veins::MobilityInfo::getSensorPeriod ()
Definition at line 69 of file MobilityInfo.cc.
{
     return sensorPeriod;
 }
References sensorPeriod.
info()
std::string veins::MobilityInfo::info ()
Definition at line 112 of file MobilityInfo.cc.
{
     std::ostringstream ost;
     ost << "MobilityInfo"
         << ";maxSpeed;" << this->maxSpeed
         << ";last Move; " << lastMove->info()
         << ";actual Move; " << actualMove->info();
 ;
     return ost.str();
 }
References actualMove, veins::Move::info(), lastMove, and maxSpeed.
infoTrace()
std::string veins::MobilityInfo::infoTrace (bool header = false, std::string idagent = "")
Returns information about the current state.
Definition at line 148 of file MobilityInfo.cc.
{
         std::ostringstream ost;
         if (header)
             ost
                 << ";ageCurrentPos" << idagent
                 << ";maxSpeed" << idagent
                 << ";currUpdatePosTime" << idagent
                 << ";acceleration" << idagent
                 << ";angleRad" << idagent
                 << ";currentPosx" << idagent
                 << ";currentPosy" << idagent
                 << ";currentPosz" << idagent
                 << ";speed" << idagent
                 << ";lastUpdatePosTime" << idagent
                      << ";lastPosx" << idagent
                      << ";lastPosy" << idagent
                      << ";lastPosz" << idagent
                      << ";lastSpeed" << idagent;
                 //       << ";nextTime" << idagent
                 //        << ";nextPosx" << idagent
                 //        << ";nextPosy" << idagent
                 //        << ";nextPosz" << idagent;
         else
         {
             ost
                 << ";" << this->age
                 << ";" << this->maxSpeed
                 << ";" << this->actualMove->getStartTime()
                 << ";" << this->acceleration
                 << ";" << this->angle
                 << ";" << this->actualMove->getStartPos().x
                 << ";" << this->actualMove->getStartPos().y
                 << ";" << this->actualMove->getStartPos().z
                 << ";" << this->actualMove->getSpeed()
                 << ";" << this->lastMove->getStartTime()
                 << ";" << this->lastMove->getStartPos().x
                 << ";" << this->lastMove->getStartPos().y
                 << ";" << this->lastMove->getStartPos().z
                 << ";" << this->lastMove->getSpeed();
                 //simtime_t nextTime = simTime();
                 //Coord c = getPositionAtTime(nextTime);
                 //ost << ";" << nextTime<< ";" << c.x << ";" << c.y << ";" << c.z;
         }
         return ost.str();
 }
References acceleration, actualMove, age, angle, veins::Move::getSpeed(), veins::Move::getStartPos(), veins::Move::getStartTime(), lastMove, maxSpeed, veins::Coord::x, veins::Coord::y, and veins::Coord::z.
Referenced by veins::Agent::infoTrace().
moveInfoTrace()
std::string veins::MobilityInfo::moveInfoTrace (bool header = false) virtual
Returns information about the current state.
Reimplemented in veins::LocalMobility.
Definition at line 142 of file MobilityInfo.cc.
{
     }
Referenced by veins::LocalMobility::moveInfoTrace().
setAcceleration()
void veins::MobilityInfo::setAcceleration (float acceleration)
Definition at line 56 of file MobilityInfo.cc.
{
     this->acceleration = acceleration;
 }
References acceleration.
Referenced by veins::RemoteMobility::updateMobilityInfo().
setActualMove()
void veins::MobilityInfo::setActualMove (Move * actualMove)
Definition at line 64 of file MobilityInfo.cc.
{
     this->lastMove =   this->actualMove;
     this->actualMove = pActualMove;
 }
References actualMove, and lastMove.
Referenced by veins::RemoteMobility::RemoteMobility(), and veins::RemoteMobility::updateMobilityInfo().
setAge()
void veins::MobilityInfo::setAge (double age)
Definition at line 249 of file MobilityInfo.cc.
{
     this->age = age;
 }
References age.
Referenced by veins::RemoteAgent::createAgent(), veins::RemoteAgent::RemoteAgent(), and veins::RemoteAgent::updateRemoteAgent().
setAngle()
void veins::MobilityInfo::setAngle (float angle)
Definition at line 203 of file MobilityInfo.cc.
{
     this->angle = angle;
 }
References angle.
Referenced by veins::RemoteMobility::updateMobilityInfo().
setCollectedMove()
void veins::MobilityInfo::setCollectedMove (Move * collectedMove)
Definition at line 257 of file MobilityInfo.cc.
{
     this->collectedMove = collectedMove;
 }
References collectedMove.
Referenced by veins::LocalMobility::updateLocalMobilityPos(), and veins::RemoteMobility::updateMobilityInfo().
setLastMove()
void veins::MobilityInfo::setLastMove (Move * pMove) protected
Definition at line 42 of file MobilityInfo.cc.
{
     this->lastMove = pMove;
 }
References lastMove.
setMaxSpeed()
void veins::MobilityInfo::setMaxSpeed (float maxSpeed)
Definition at line 83 of file MobilityInfo.cc.
{
     this->maxSpeed = maxSpeed;
 }
References maxSpeed.
Referenced by veins::LocalMobility::LocalMobility(), veins::LocalAgent::updateLocalAgent(), and veins::RemoteMobility::updateMobilityInfo().
setSensorPeriod()
void veins::MobilityInfo::setSensorPeriod (float sensorPeriod)
Definition at line 73 of file MobilityInfo.cc.
{
     this->sensorPeriod = sensorPeriod;
 }
References sensorPeriod.
Member Data Documentation
acceleration
float veins::MobilityInfo::acceleration protected
Definition at line 51 of file MobilityInfo.h.
Referenced by calcAcceleration(), getAcceleration(), getPositionAtTime(), infoTrace(), veins::RemoteMobility::RemoteMobility(), and setAcceleration().
actualMove
Move* veins::MobilityInfo::actualMove = new Move() protected
current vehicle movement
Definition at line 36 of file MobilityInfo.h.
Referenced by calcAcceleration(), getActualMove(), veins::LocalMobility::getMove(), getPositionAtTime(), info(), infoTrace(), veins::LocalMobility::LocalMobility(), MobilityInfo(), setActualMove(), and veins::LocalMobility::updateLocalMobilityPos().
age
double veins::MobilityInfo::age protected
Definition at line 57 of file MobilityInfo.h.
Referenced by getAge(), infoTrace(), setAge(), and veins::LocalMobility::updateLocalMobilityPos().
angle
float veins::MobilityInfo::angle protected
Definition at line 54 of file MobilityInfo.h.
Referenced by getAngle(), getPositionAtTime(), infoTrace(), veins::RemoteMobility::RemoteMobility(), setAngle(), and veins::LocalMobility::updateLocalMobilityPos().
collectedMove
Move* veins::MobilityInfo::collectedMove = new Move() protected
collected vehicle movement
Definition at line 42 of file MobilityInfo.h.
Referenced by getCollectedMove(), and setCollectedMove().
lastMove
Move* veins::MobilityInfo::lastMove = new Move() protected
last vehicle movement before current position
Definition at line 39 of file MobilityInfo.h.
Referenced by calcAcceleration(), calcEuclideanDistanceAgentMoving(), veins::LocalMobility::getLastMove(), getLastMove(), info(), infoTrace(), MobilityInfo(), setActualMove(), setLastMove(), and veins::LocalMobility::updateLocalMobilityPos().
maxSpeed
float veins::MobilityInfo::maxSpeed =0 protected
Definition at line 45 of file MobilityInfo.h.
Referenced by info(), infoTrace(), MobilityInfo(), veins::RemoteMobility::RemoteMobility(), and setMaxSpeed().
sensorPeriod
float veins::MobilityInfo::sensorPeriod protected
Definition at line 48 of file MobilityInfo.h.
Referenced by calcAcceleration(), veins::LocalMobility::getSensorPeriod(), getSensorPeriod(), veins::LocalMobility::LocalMobility(), veins::LocalMobility::setSensorPeriod(), and setSensorPeriod().
The documentation for this class was generated from the following files:
MobilityInfo.h
MobilityInfo.cc