My Project: veins::ForwardingNode
veins::ForwardingNode
#include <ForwardingNode.h>
Public Member Functions
ForwardingNode ()
virtual ~ForwardingNode ()
void update (std::string rule, int fowardingAgent, AgentPair *c, double periodvalidty)
void update (std::string rule, Agent *fowardingAgent, AgentPair *c, double periodvalidty)
double getDataValidity ()
void setDataValidity (double dataValidity)
int64_t getFowardId ()
void setFowardId (int64_t afowardId)
std::string getRule ()
void setRule (std::string rule)
const simtime_t getTimeoutValidity ()
void setTimeoutValidity (simtime_t timeoutValidity)
AgentPair * getAgentPair ()
void setAgentPair (AgentPair *agentPair)
Private Attributes
int64_t fowardId
double dataValidity
simtime_t timeoutValidity
std::string rule
AgentPair * agentPair
Agent * fowardingAgent
Detailed Description
Definition at line 29 of file ForwardingNode.h.
Constructor & Destructor Documentation
ForwardingNode()
veins::ForwardingNode::ForwardingNode ()
Definition at line 20 of file ForwardingNode.cc.
{
     // TODO Auto-generated constructor stub
     this->rule="-1";
     this->fowardId = -1;
     this->agentPair = NULL;
 }
References agentPair, fowardId, and rule.
~ForwardingNode()
veins::ForwardingNode::~ForwardingNode () virtual
Definition at line 91 of file ForwardingNode.cc.
{
     // TODO Auto-generated destructor stub
 }
Member Function Documentation
getAgentPair()
AgentPair * veins::ForwardingNode::getAgentPair ()
Definition at line 79 of file ForwardingNode.cc.
{
     return agentPair;
 }
References agentPair.
getDataValidity()
double veins::ForwardingNode::getDataValidity ()
Definition at line 28 of file ForwardingNode.cc.
{
     return dataValidity;
 }
References dataValidity.
getFowardId()
int64_t veins::ForwardingNode::getFowardId ()
Definition at line 59 of file ForwardingNode.cc.
{
     return fowardId;
 }
References fowardId.
Referenced by veins::Routing::rule2(), veins::Routing::rule3(), veins::Routing::rule4(), veins::Routing::searchNode(), and veins::Routing::verifyAgentPairAneib().
getRule()
std::string veins::ForwardingNode::getRule ()
Definition at line 67 of file ForwardingNode.cc.
{
     return rule;
 }
References rule.
getTimeoutValidity()
const simtime_t veins::ForwardingNode::getTimeoutValidity ()
Definition at line 75 of file ForwardingNode.cc.
{
     return timeoutValidity;
 }
References timeoutValidity.
setAgentPair()
void veins::ForwardingNode::setAgentPair (AgentPair * agentPair)
Definition at line 83 of file ForwardingNode.cc.
{
     this->agentPair = agentPair;
 }
References agentPair.
Referenced by veins::Routing::rule4().
setDataValidity()
void veins::ForwardingNode::setDataValidity (double dataValidity)
Definition at line 55 of file ForwardingNode.cc.
{
     this->dataValidity = dataValidity;
 }
References dataValidity.
Referenced by update().
setFowardId()
void veins::ForwardingNode::setFowardId (int64_t afowardId)
Definition at line 63 of file ForwardingNode.cc.
{
     this->fowardId = fowardId;
 }
References fowardId.
Referenced by veins::Routing::rule4(), and update().
setRule()
void veins::ForwardingNode::setRule (std::string rule)
Definition at line 71 of file ForwardingNode.cc.
{
     this->rule = rule;
 }
References rule.
Referenced by update().
setTimeoutValidity()
void veins::ForwardingNode::setTimeoutValidity (simtime_t timeoutValidity)
Definition at line 87 of file ForwardingNode.cc.
{
     this->timeoutValidity = timeoutValidity;
 }
References timeoutValidity.
Referenced by update().
update() [1/2]
void veins::ForwardingNode::update (std::string rule, Agent * fowardingAgent, AgentPair * c, double periodvalidty)
Definition at line 43 of file ForwardingNode.cc.
{
     this->setFowardId(fowardingAgent->getId());
     this->setDataValidity(c->getQoCAgentPair()->getTimeliness()->getValidityNow());
     //this->setDataValidity(periodvalidty);
     //this->setTimeoutValidity(((simtime_t)(simTime() + periodvalidty)));
     this->setTimeoutValidity(c->getQoCAgentPair()->getTimeliness()->getTimeoutValidity());
     this->setRule(rule);
     this->agentPair = c;
     this->fowardingAgent = fowardingAgent;
 }
References agentPair, fowardingAgent, veins::Agent::getId(), veins::AgentPair::getQoCAgentPair(), veins::QoCInfo::getTimeliness(), Timeliness::getTimeoutValidity(), Timeliness::getValidityNow(), setDataValidity(), setFowardId(), setRule(), and setTimeoutValidity().
update() [2/2]
void veins::ForwardingNode::update (std::string rule, int fowardingAgent, AgentPair * c, double periodvalidty)
Definition at line 32 of file ForwardingNode.cc.
{
     this->setFowardId(fowardingAgent);
     this->setDataValidity(c->getQoCAgentPair()->getTimeliness()->getValidityNow());
     //this->setDataValidity(periodvalidty);
     //this->setTimeoutValidity(((simtime_t)(simTime() + periodvalidty)));
     this->setTimeoutValidity(c->getQoCAgentPair()->getTimeliness()->getTimeoutValidity());
     this->setRule(rule);
     this->agentPair = c;
 }
References agentPair, veins::AgentPair::getQoCAgentPair(), veins::QoCInfo::getTimeliness(), Timeliness::getTimeoutValidity(), Timeliness::getValidityNow(), setDataValidity(), setFowardId(), setRule(), and setTimeoutValidity().
Referenced by veins::IcarRouting::getFowardNode(), veins::Routing::rule2(), veins::Routing::searchNode(), veins::Routing::verifyConditionForwardAgent(), and veins::Routing::verifyConditionForwardNotNeighbor().
Member Data Documentation
agentPair
AgentPair* veins::ForwardingNode::agentPair private
Definition at line 35 of file ForwardingNode.h.
Referenced by ForwardingNode(), getAgentPair(), setAgentPair(), and update().
dataValidity
double veins::ForwardingNode::dataValidity private
Definition at line 32 of file ForwardingNode.h.
Referenced by getDataValidity(), and setDataValidity().
fowardId
int64_t veins::ForwardingNode::fowardId private
Definition at line 31 of file ForwardingNode.h.
Referenced by ForwardingNode(), getFowardId(), and setFowardId().
fowardingAgent
Agent* veins::ForwardingNode::fowardingAgent private
Definition at line 36 of file ForwardingNode.h.
Referenced by update().
rule
std::string veins::ForwardingNode::rule private
Definition at line 34 of file ForwardingNode.h.
Referenced by ForwardingNode(), getRule(), and setRule().
timeoutValidity
simtime_t veins::ForwardingNode::timeoutValidity private
Definition at line 33 of file ForwardingNode.h.
Referenced by getTimeoutValidity(), and setTimeoutValidity().
The documentation for this class was generated from the following files:
ForwardingNode.h
ForwardingNode.cc