My Project: veins::RemoteAgentGroup
veins::RemoteAgentGroup
#include <RemoteAgentGroup.h>
Public Member Functions
RemoteAgentGroup ()
virtual ~RemoteAgentGroup ()
double getMaxMessageTTime ()
void setMaxMessageTTime (double maxMessageTTime)
double getMinApplicationTime ()
void setMinApplicationTime (double minApplicationTime)
double getMinMessageTTime ()
void setMinMessageTTime (double minMessageTTime)
RemoteAgent * getRemoteAgent (int64_t id)
int getRemoteAgentIndex (int64_t id)
std::string calcRemoteAgentGroupCommPerform (bool header)
Public Attributes
vector< RemoteAgent * > knownRemoteAgents
Private Attributes
double maxMessageTTime
double minMessageTTime
double minApplicationTime
double maxApplicationTime
double maxDistancelr
double minDistancelr
double maxSlr
double minSlr
Detailed Description
Definition at line 25 of file RemoteAgentGroup.h.
Constructor & Destructor Documentation
RemoteAgentGroup()
veins::RemoteAgentGroup::RemoteAgentGroup ()
Definition at line 20 of file RemoteAgentGroup.cc.
{
     // TODO Auto-generated constructor stub
     maxMessageTTime=0;
     minApplicationTime=0;
     minMessageTTime=0;
 }
References maxMessageTTime, minApplicationTime, and minMessageTTime.
~RemoteAgentGroup()
veins::RemoteAgentGroup::~RemoteAgentGroup () virtual
Definition at line 51 of file RemoteAgentGroup.cc.
{
     // TODO Auto-generated destructor stub
     delete (this);
 }
Member Function Documentation
calcRemoteAgentGroupCommPerform()
std::string veins::RemoteAgentGroup::calcRemoteAgentGroupCommPerform (bool header)
Definition at line 95 of file RemoteAgentGroup.cc.
{
     RemoteAgent *a=NULL;
     std::ostringstream ost;
     unsigned int i = 0;
     while (this->knownRemoteAgents.size()> i)
     {
         a = dynamic_cast<RemoteAgent*>(knownRemoteAgents[i]);
         if (i==0) ost << a->infoTrace(true, "Remote")<<std::endl;
         if (a->getRemoteAgentCommInfo()->getRemoteAgentCommPerformance()->getRateCorrectTransmittedMsgTemp()>0)
         {
             a->getRemoteAgentCommInfo()->getRemoteAgentCommPerformance()->calRateCorrectTransmittedMsgPerPeriod();
             ost << a->infoTrace(false, "")<<std::endl;
         }
         ++i;
      }
     return ost.str();
 }
References RemoteAgentCommPerformance::calRateCorrectTransmittedMsgPerPeriod(), RemoteAgentCommPerformance::getRateCorrectTransmittedMsgTemp(), veins::RemoteAgent::getRemoteAgentCommInfo(), veins::RemoteAgentCommInfo::getRemoteAgentCommPerformance(), veins::RemoteAgent::infoTrace(), and knownRemoteAgents.
getMaxMessageTTime()
double veins::RemoteAgentGroup::getMaxMessageTTime ()
Definition at line 27 of file RemoteAgentGroup.cc.
{
     return maxMessageTTime;
 }
References maxMessageTTime.
getMinApplicationTime()
double veins::RemoteAgentGroup::getMinApplicationTime ()
Definition at line 35 of file RemoteAgentGroup.cc.
{
     return minApplicationTime;
 }
References minApplicationTime.
getMinMessageTTime()
double veins::RemoteAgentGroup::getMinMessageTTime ()
Definition at line 43 of file RemoteAgentGroup.cc.
{
     return minMessageTTime;
 }
References minMessageTTime.
getRemoteAgent()
RemoteAgent * veins::RemoteAgentGroup::getRemoteAgent (int64_t id)
Definition at line 56 of file RemoteAgentGroup.cc.
{
     RemoteAgent *a=NULL;
     bool find=false;
     unsigned int index = 0;
     while (id!=-1 && !find && this->knownRemoteAgents.size()> index)
     {
         a = dynamic_cast<RemoteAgent*>(knownRemoteAgents[index]);
         if (a->getId() == id)
            find=true;
         else
             {
                 a=NULL;
             }
         ++index;
     }
     //if (a!=NULL) cout << std::endl << this->knownRemoteAgents.size()<< " - id " << a->getId() << " = " << id << std::endl;
      return a;
 }
References veins::Agent::getId(), and knownRemoteAgents.
Referenced by veins::Routing::searchNode(), veins::MessageManager::sendIcarMessageService(), and veins::IcarContext::updateAgentGroup().
getRemoteAgentIndex()
int veins::RemoteAgentGroup::getRemoteAgentIndex (int64_t id)
Definition at line 78 of file RemoteAgentGroup.cc.
{
     RemoteAgent *a=NULL;
     int index = -1;
     unsigned int i = 0;
     while (index==-1 && this->knownRemoteAgents.size()> i)
     {
         a = dynamic_cast<RemoteAgent*>(knownRemoteAgents[i]);
         if (a->getId() == id) index = i;
         ++i;
      }
     return index;
 }
References veins::Agent::getId(), and knownRemoteAgents.
setMaxMessageTTime()
void veins::RemoteAgentGroup::setMaxMessageTTime (double maxMessageTTime)
Definition at line 31 of file RemoteAgentGroup.cc.
{
     this->maxMessageTTime = maxMessageTTime;
 }
References maxMessageTTime.
setMinApplicationTime()
void veins::RemoteAgentGroup::setMinApplicationTime (double minApplicationTime)
Definition at line 39 of file RemoteAgentGroup.cc.
{
     this->minApplicationTime = minApplicationTime;
 }
References minApplicationTime.
setMinMessageTTime()
void veins::RemoteAgentGroup::setMinMessageTTime (double minMessageTTime)
Definition at line 47 of file RemoteAgentGroup.cc.
{
     this->minMessageTTime = minMessageTTime;
 }
References minMessageTTime.
Member Data Documentation
knownRemoteAgents
vector<RemoteAgent*> veins::RemoteAgentGroup::knownRemoteAgents
Definition at line 48 of file RemoteAgentGroup.h.
Referenced by calcRemoteAgentGroupCommPerform(), getRemoteAgent(), getRemoteAgentIndex(), and veins::IcarContext::updateAgentGroup().
maxApplicationTime
double veins::RemoteAgentGroup::maxApplicationTime private
Definition at line 30 of file RemoteAgentGroup.h.
maxDistancelr
double veins::RemoteAgentGroup::maxDistancelr private
Definition at line 31 of file RemoteAgentGroup.h.
maxMessageTTime
double veins::RemoteAgentGroup::maxMessageTTime private
Definition at line 27 of file RemoteAgentGroup.h.
Referenced by getMaxMessageTTime(), RemoteAgentGroup(), and setMaxMessageTTime().
maxSlr
double veins::RemoteAgentGroup::maxSlr private
Definition at line 33 of file RemoteAgentGroup.h.
minApplicationTime
double veins::RemoteAgentGroup::minApplicationTime private
Definition at line 29 of file RemoteAgentGroup.h.
Referenced by getMinApplicationTime(), RemoteAgentGroup(), and setMinApplicationTime().
minDistancelr
double veins::RemoteAgentGroup::minDistancelr private
Definition at line 32 of file RemoteAgentGroup.h.
minMessageTTime
double veins::RemoteAgentGroup::minMessageTTime private
Definition at line 28 of file RemoteAgentGroup.h.
Referenced by getMinMessageTTime(), RemoteAgentGroup(), and setMinMessageTTime().
minSlr
double veins::RemoteAgentGroup::minSlr private
Definition at line 34 of file RemoteAgentGroup.h.
The documentation for this class was generated from the following files:
RemoteAgentGroup.h
RemoteAgentGroup.cc